
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.vidal.merlin.wsclient.asmr;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:21 CET 2013
 * Generated source version: 2.2.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "AsmrService",
                      portName = "AsmrServiceHttpPort",
                      targetNamespace = "urn:Vidal",
                      wsdlLocation = "http://localhost:8011/merlin-service/services/AsmrService?wsdl",
                      endpointInterface = "com.vidal.merlin.wsclient.asmr.AsmrService")
                      
public class AsmrServiceImpl implements AsmrService {

    private static final Logger LOG = Logger.getLogger(AsmrServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.asmr.AsmrService#searchBySmrId(java.lang.Integer  smrId )*
     */
    public com.vidal.merlin.wsclient.asmr.ArrayOfAsmr searchBySmrId(java.lang.Integer smrId) { 
        LOG.info("Executing operation searchBySmrId");
        System.out.println(smrId);
        try {
            com.vidal.merlin.wsclient.asmr.ArrayOfAsmr _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
