package com.vidal.merlin.wsclient.smr;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:32 CET 2013
 * Generated source version: 2.2.6
 * 
 */
 
@WebService(targetNamespace = "urn:Vidal", name = "smrService")
@XmlSeeAlso({ObjectFactory.class})
public interface SmrService {

    @WebResult(name = "smrList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByProductId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.smr.SearchByProductId")
    @ResponseWrapper(localName = "searchByProductIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.smr.SearchByProductIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.smr.ArrayOfSmr searchByProductId(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        java.lang.Integer productId
    );

    @WebResult(name = "smrAsmrAsHTML", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getSmrAsmrAsHTML", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.smr.GetSmrAsmrAsHTML")
    @ResponseWrapper(localName = "getSmrAsmrAsHTMLResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.smr.GetSmrAsmrAsHTMLResponse")
    @WebMethod
    public java.lang.String getSmrAsmrAsHTML(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        java.lang.Integer productId
    );
}
