
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.vidal.merlin.wsclient.company;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:23 CET 2013
 * Generated source version: 2.2.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "CompanyService",
                      portName = "CompanyServiceHttpPort",
                      targetNamespace = "urn:Vidal",
                      wsdlLocation = "http://localhost:8011/merlin-service/services/CompanyService?wsdl",
                      endpointInterface = "com.vidal.merlin.wsclient.company.CompanyService")
                      
public class CompanyServiceImpl implements CompanyService {

    private static final Logger LOG = Logger.getLogger(CompanyServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.company.CompanyService#getAllCompanies(java.lang.Integer  pageNumber ,)java.lang.Integer  pageSize )*
     */
    public com.vidal.merlin.wsclient.company.PagedResultCompany getAllCompanies(java.lang.Integer pageNumber,java.lang.Integer pageSize) { 
        LOG.info("Executing operation getAllCompanies");
        System.out.println(pageNumber);
        System.out.println(pageSize);
        try {
            com.vidal.merlin.wsclient.company.PagedResultCompany _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.company.CompanyService#searchByProductId(java.lang.Integer  productId )*
     */
    public com.vidal.merlin.wsclient.company.Company searchByProductId(java.lang.Integer productId) { 
        LOG.info("Executing operation searchByProductId");
        System.out.println(productId);
        try {
            com.vidal.merlin.wsclient.company.Company _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.company.CompanyService#searchByName(java.lang.String  name )*
     */
    public com.vidal.merlin.wsclient.company.ArrayOfCompany searchByName(java.lang.String name) { 
        LOG.info("Executing operation searchByName");
        System.out.println(name);
        try {
            com.vidal.merlin.wsclient.company.ArrayOfCompany _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.company.CompanyService#searchByPackId(java.lang.Integer  packId )*
     */
    public com.vidal.merlin.wsclient.company.ArrayOfCompanyCompanyTypeCouple searchByPackId(java.lang.Integer packId) { 
        LOG.info("Executing operation searchByPackId");
        System.out.println(packId);
        try {
            com.vidal.merlin.wsclient.company.ArrayOfCompanyCompanyTypeCouple _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.company.CompanyService#searchById(java.lang.Integer  companyId )*
     */
    public com.vidal.merlin.wsclient.company.Company searchById(java.lang.Integer companyId) { 
        LOG.info("Executing operation searchById");
        System.out.println(companyId);
        try {
            com.vidal.merlin.wsclient.company.Company _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.company.CompanyService#searchByPackageId(java.lang.Integer  packageId )*
     */
    public com.vidal.merlin.wsclient.company.ArrayOfCompanyCompanyTypeCouple searchByPackageId(java.lang.Integer packageId) { 
        LOG.info("Executing operation searchByPackageId");
        System.out.println(packageId);
        try {
            com.vidal.merlin.wsclient.company.ArrayOfCompanyCompanyTypeCouple _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
