package com.vidal.merlin.wsclient.cim10;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:22 CET 2013
 * Generated source version: 2.2.6
 * 
 */
 
@WebService(targetNamespace = "urn:Vidal", name = "cim10Service")
@XmlSeeAlso({ObjectFactory.class})
public interface Cim10Service {

    @WebResult(name = "cim10List", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByCode", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.cim10.SearchByCode")
    @ResponseWrapper(localName = "searchByCodeResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.cim10.SearchByCodeResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.cim10.ArrayOfCim10 searchByCode(
        @WebParam(name = "code", targetNamespace = "urn:Vidal")
        java.lang.String code
    );

    @WebResult(name = "indicationGroupList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getIndicationGroup", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.cim10.GetIndicationGroup")
    @ResponseWrapper(localName = "getIndicationGroupResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.cim10.GetIndicationGroupResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.cim10.ArrayOfIndicationGroup getIndicationGroup(
        @WebParam(name = "cim10Id", targetNamespace = "urn:Vidal")
        java.lang.Integer cim10Id
    );

    @WebResult(name = "cim10List", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getCim10sByGIPMSIFiltered", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.cim10.GetCim10SByGIPMSIFiltered")
    @ResponseWrapper(localName = "getCim10sByGIPMSIFilteredResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.cim10.GetCim10SByGIPMSIFilteredResponse")
    @WebMethod(operationName = "getCim10sByGIPMSIFiltered")
    public com.vidal.merlin.wsclient.cim10.ArrayOfCim10 getCim10SByGIPMSIFiltered(
        @WebParam(name = "indicationGroupId", targetNamespace = "urn:Vidal")
        java.lang.Integer indicationGroupId
    );

    @WebResult(name = "cim10List", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByName", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.cim10.SearchByName")
    @ResponseWrapper(localName = "searchByNameResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.cim10.SearchByNameResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.cim10.ArrayOfCim10 searchByName(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        java.lang.String name
    );

    @WebResult(name = "cim10List", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getChildren", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.cim10.GetChildren")
    @ResponseWrapper(localName = "getChildrenResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.cim10.GetChildrenResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.cim10.ArrayOfCim10 getChildren(
        @WebParam(name = "cim10Id", targetNamespace = "urn:Vidal")
        java.lang.Integer cim10Id
    );

    @WebResult(name = "cim10", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getRootNode", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.cim10.GetRootNode")
    @ResponseWrapper(localName = "getRootNodeResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.cim10.GetRootNodeResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.cim10.Cim10 getRootNode();

    @WebResult(name = "cim10List", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByIndicationGroupId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.cim10.SearchByIndicationGroupId")
    @ResponseWrapper(localName = "searchByIndicationGroupIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.cim10.SearchByIndicationGroupIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.cim10.ArrayOfCim10 searchByIndicationGroupId(
        @WebParam(name = "indicationGroupId", targetNamespace = "urn:Vidal")
        java.lang.Integer indicationGroupId
    );

    @WebResult(name = "cim10List", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByContraIndicationId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.cim10.SearchByContraIndicationId")
    @ResponseWrapper(localName = "searchByContraIndicationIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.cim10.SearchByContraIndicationIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.cim10.ArrayOfCim10 searchByContraIndicationId(
        @WebParam(name = "contraIndicationId", targetNamespace = "urn:Vidal")
        java.lang.Integer contraIndicationId
    );

    @WebResult(name = "cim10", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchById", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.cim10.SearchById")
    @ResponseWrapper(localName = "searchByIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.cim10.SearchByIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.cim10.Cim10 searchById(
        @WebParam(name = "cim10Id", targetNamespace = "urn:Vidal")
        java.lang.Integer cim10Id
    );

    @WebResult(name = "cim10", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getParent", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.cim10.GetParent")
    @ResponseWrapper(localName = "getParentResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.cim10.GetParentResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.cim10.Cim10 getParent(
        @WebParam(name = "cim10Id", targetNamespace = "urn:Vidal")
        java.lang.Integer cim10Id
    );

    @WebResult(name = "contraIndicationList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getContraIndication", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.cim10.GetContraIndication")
    @ResponseWrapper(localName = "getContraIndicationResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.cim10.GetContraIndicationResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.cim10.ArrayOfContraIndication getContraIndication(
        @WebParam(name = "cim10Id", targetNamespace = "urn:Vidal")
        java.lang.Integer cim10Id
    );

    @WebResult(name = "pagedResultCim10", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getAllCim10s", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.cim10.GetAllCim10S")
    @ResponseWrapper(localName = "getAllCim10sResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.cim10.GetAllCim10SResponse")
    @WebMethod(operationName = "getAllCim10s")
    public com.vidal.merlin.wsclient.cim10.PagedResultCim10 getAllCim10S(
        @WebParam(name = "pageNumber", targetNamespace = "urn:Vidal")
        java.lang.Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "urn:Vidal")
        java.lang.Integer pageSize
    );
}
