
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.vidal.merlin.wsclient.cim10;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:22 CET 2013
 * Generated source version: 2.2.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "Cim10Service",
                      portName = "Cim10ServiceHttpPort",
                      targetNamespace = "urn:Vidal",
                      wsdlLocation = "http://localhost:8011/merlin-service/services/Cim10Service?wsdl",
                      endpointInterface = "com.vidal.merlin.wsclient.cim10.Cim10Service")
                      
public class Cim10ServiceImpl implements Cim10Service {

    private static final Logger LOG = Logger.getLogger(Cim10ServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.cim10.Cim10Service#searchByCode(java.lang.String  code )*
     */
    public com.vidal.merlin.wsclient.cim10.ArrayOfCim10 searchByCode(java.lang.String code) { 
        LOG.info("Executing operation searchByCode");
        System.out.println(code);
        try {
            com.vidal.merlin.wsclient.cim10.ArrayOfCim10 _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.cim10.Cim10Service#getIndicationGroup(java.lang.Integer  cim10Id )*
     */
    public com.vidal.merlin.wsclient.cim10.ArrayOfIndicationGroup getIndicationGroup(java.lang.Integer cim10Id) { 
        LOG.info("Executing operation getIndicationGroup");
        System.out.println(cim10Id);
        try {
            com.vidal.merlin.wsclient.cim10.ArrayOfIndicationGroup _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.cim10.Cim10Service#getCim10SByGIPMSIFiltered(java.lang.Integer  indicationGroupId )*
     */
    public com.vidal.merlin.wsclient.cim10.ArrayOfCim10 getCim10SByGIPMSIFiltered(java.lang.Integer indicationGroupId) { 
        LOG.info("Executing operation getCim10SByGIPMSIFiltered");
        System.out.println(indicationGroupId);
        try {
            com.vidal.merlin.wsclient.cim10.ArrayOfCim10 _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.cim10.Cim10Service#searchByName(java.lang.String  name )*
     */
    public com.vidal.merlin.wsclient.cim10.ArrayOfCim10 searchByName(java.lang.String name) { 
        LOG.info("Executing operation searchByName");
        System.out.println(name);
        try {
            com.vidal.merlin.wsclient.cim10.ArrayOfCim10 _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.cim10.Cim10Service#getChildren(java.lang.Integer  cim10Id )*
     */
    public com.vidal.merlin.wsclient.cim10.ArrayOfCim10 getChildren(java.lang.Integer cim10Id) { 
        LOG.info("Executing operation getChildren");
        System.out.println(cim10Id);
        try {
            com.vidal.merlin.wsclient.cim10.ArrayOfCim10 _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.cim10.Cim10Service#getRootNode(*
     */
    public com.vidal.merlin.wsclient.cim10.Cim10 getRootNode() { 
        LOG.info("Executing operation getRootNode");
        try {
            com.vidal.merlin.wsclient.cim10.Cim10 _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.cim10.Cim10Service#searchByIndicationGroupId(java.lang.Integer  indicationGroupId )*
     */
    public com.vidal.merlin.wsclient.cim10.ArrayOfCim10 searchByIndicationGroupId(java.lang.Integer indicationGroupId) { 
        LOG.info("Executing operation searchByIndicationGroupId");
        System.out.println(indicationGroupId);
        try {
            com.vidal.merlin.wsclient.cim10.ArrayOfCim10 _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.cim10.Cim10Service#searchByContraIndicationId(java.lang.Integer  contraIndicationId )*
     */
    public com.vidal.merlin.wsclient.cim10.ArrayOfCim10 searchByContraIndicationId(java.lang.Integer contraIndicationId) { 
        LOG.info("Executing operation searchByContraIndicationId");
        System.out.println(contraIndicationId);
        try {
            com.vidal.merlin.wsclient.cim10.ArrayOfCim10 _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.cim10.Cim10Service#searchById(java.lang.Integer  cim10Id )*
     */
    public com.vidal.merlin.wsclient.cim10.Cim10 searchById(java.lang.Integer cim10Id) { 
        LOG.info("Executing operation searchById");
        System.out.println(cim10Id);
        try {
            com.vidal.merlin.wsclient.cim10.Cim10 _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.cim10.Cim10Service#getParent(java.lang.Integer  cim10Id )*
     */
    public com.vidal.merlin.wsclient.cim10.Cim10 getParent(java.lang.Integer cim10Id) { 
        LOG.info("Executing operation getParent");
        System.out.println(cim10Id);
        try {
            com.vidal.merlin.wsclient.cim10.Cim10 _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.cim10.Cim10Service#getContraIndication(java.lang.Integer  cim10Id )*
     */
    public com.vidal.merlin.wsclient.cim10.ArrayOfContraIndication getContraIndication(java.lang.Integer cim10Id) { 
        LOG.info("Executing operation getContraIndication");
        System.out.println(cim10Id);
        try {
            com.vidal.merlin.wsclient.cim10.ArrayOfContraIndication _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.cim10.Cim10Service#getAllCim10S(java.lang.Integer  pageNumber ,)java.lang.Integer  pageSize )*
     */
    public com.vidal.merlin.wsclient.cim10.PagedResultCim10 getAllCim10S(java.lang.Integer pageNumber,java.lang.Integer pageSize) { 
        LOG.info("Executing operation getAllCim10S");
        System.out.println(pageNumber);
        System.out.println(pageSize);
        try {
            com.vidal.merlin.wsclient.cim10.PagedResultCim10 _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
