
/*
 * 
 */

package com.vidal.merlin.wsclient.cim10;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:22 CET 2013
 * Generated source version: 2.2.6
 * 
 */


@WebServiceClient(name = "Cim10Service", 
                  wsdlLocation = "http://localhost:8011/merlin-service/services/Cim10Service?wsdl",
                  targetNamespace = "urn:Vidal") 
public class Cim10Service_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("urn:Vidal", "Cim10Service");
    public final static QName Cim10ServiceHttpPort = new QName("urn:Vidal", "Cim10ServiceHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8011/merlin-service/services/Cim10Service?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8011/merlin-service/services/Cim10Service?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public Cim10Service_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Cim10Service_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Cim10Service_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns Cim10Service
     */
    @WebEndpoint(name = "Cim10ServiceHttpPort")
    public Cim10Service getCim10ServiceHttpPort() {
        return super.getPort(Cim10ServiceHttpPort, Cim10Service.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Cim10Service
     */
    @WebEndpoint(name = "Cim10ServiceHttpPort")
    public Cim10Service getCim10ServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(Cim10ServiceHttpPort, Cim10Service.class, features);
    }

}
