
package com.vidal.merlin.wsclient.galenicForm;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:27 CET 2013
 * Generated source version: 2.2.6
 * 
 */

public final class GalenicFormService_GalenicFormServiceHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("urn:Vidal", "GalenicFormService");

    private GalenicFormService_GalenicFormServiceHttpPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = GalenicFormService_Service.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        GalenicFormService_Service ss = new GalenicFormService_Service(wsdlURL, SERVICE_NAME);
        GalenicFormService port = ss.getGalenicFormServiceHttpPort();  
        
        {
        System.out.println("Invoking getAllGalenicForms...");
        java.lang.Integer _getAllGalenicForms_pageNumber = null;
        java.lang.Integer _getAllGalenicForms_pageSize = null;
        com.vidal.merlin.wsclient.galenicForm.PagedResultGalenicForm _getAllGalenicForms__return = port.getAllGalenicForms(_getAllGalenicForms_pageNumber, _getAllGalenicForms_pageSize);
        System.out.println("getAllGalenicForms.result=" + _getAllGalenicForms__return);


        }
        {
        System.out.println("Invoking searchByName...");
        java.lang.String _searchByName_name = "";
        com.vidal.merlin.wsclient.galenicForm.ArrayOfGalenicForm _searchByName__return = port.searchByName(_searchByName_name);
        System.out.println("searchByName.result=" + _searchByName__return);


        }
        {
        System.out.println("Invoking searchByIds...");
        com.vidal.merlin.wsclient.galenicForm.ArrayOfInt _searchByIds_galenicFormIds = null;
        com.vidal.merlin.wsclient.galenicForm.ArrayOfGalenicForm _searchByIds__return = port.searchByIds(_searchByIds_galenicFormIds);
        System.out.println("searchByIds.result=" + _searchByIds__return);


        }

        System.exit(0);
    }

}
