package com.vidal.merlin.wsclient.interaction;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:27 CET 2013
 * Generated source version: 2.2.6
 * 
 */
 
@WebService(targetNamespace = "urn:Vidal", name = "interactionService")
@XmlSeeAlso({ObjectFactory.class})
public interface InteractionService {

    @WebResult(name = "interaction", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByInteractionId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.interaction.SearchByInteractionId")
    @ResponseWrapper(localName = "searchByInteractionIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.interaction.SearchByInteractionIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.interaction.Interaction searchByInteractionId(
        @WebParam(name = "interactionId", targetNamespace = "urn:Vidal")
        java.lang.Integer interactionId
    );

    @WebResult(name = "interactionResult", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchInteractionCouplesForProductIds", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.interaction.SearchInteractionCouplesForProductIds")
    @ResponseWrapper(localName = "searchInteractionCouplesForProductIdsResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.interaction.SearchInteractionCouplesForProductIdsResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.interaction.InteractionResult searchInteractionCouplesForProductIds(
        @WebParam(name = "productIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.interaction.ArrayOfInt productIds,
        @WebParam(name = "severity", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.interaction.InteractionSeverityType severity
    );

    @WebResult(name = "interactionCommonNameGroupResult", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getInteractionCouplesForCommonNameGroupIds", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.interaction.GetInteractionCouplesForCommonNameGroupIds")
    @ResponseWrapper(localName = "getInteractionCouplesForCommonNameGroupIdsResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.interaction.GetInteractionCouplesForCommonNameGroupIdsResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.interaction.InteractionCommonNameGroupResult getInteractionCouplesForCommonNameGroupIds(
        @WebParam(name = "commonNameGroupIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.interaction.ArrayOfInt commonNameGroupIds,
        @WebParam(name = "severity", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.interaction.InteractionSeverityType severity
    );

    @WebResult(name = "interactionCommonNameGroupResult", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchInteractionCouplesForCommonNameGroupId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.interaction.SearchInteractionCouplesForCommonNameGroupId")
    @ResponseWrapper(localName = "searchInteractionCouplesForCommonNameGroupIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.interaction.SearchInteractionCouplesForCommonNameGroupIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.interaction.InteractionCommonNameGroupResult searchInteractionCouplesForCommonNameGroupId(
        @WebParam(name = "commonNameGroupId", targetNamespace = "urn:Vidal")
        java.lang.Integer commonNameGroupId,
        @WebParam(name = "commonNameGroupIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.interaction.ArrayOfInt commonNameGroupIds,
        @WebParam(name = "severity", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.interaction.InteractionSeverityType severity
    );

    @WebResult(name = "interactionResult", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchInteractionCouplesForProductId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.interaction.SearchInteractionCouplesForProductId")
    @ResponseWrapper(localName = "searchInteractionCouplesForProductIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.interaction.SearchInteractionCouplesForProductIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.interaction.InteractionResult searchInteractionCouplesForProductId(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        java.lang.Integer productId,
        @WebParam(name = "productIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.interaction.ArrayOfInt productIds,
        @WebParam(name = "severity", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.interaction.InteractionSeverityType severity
    );

    @WebResult(name = "interactionCommonNameGroupResult", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchInteractionCouplesForCommonNameGroupIds", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.interaction.SearchInteractionCouplesForCommonNameGroupIds")
    @ResponseWrapper(localName = "searchInteractionCouplesForCommonNameGroupIdsResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.interaction.SearchInteractionCouplesForCommonNameGroupIdsResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.interaction.InteractionCommonNameGroupResult searchInteractionCouplesForCommonNameGroupIds(
        @WebParam(name = "commonNameGroupIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.interaction.ArrayOfInt commonNameGroupIds,
        @WebParam(name = "severity", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.interaction.InteractionSeverityType severity
    );

    @WebResult(name = "interactionResult", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getInteractionCouplesForOneProductId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.interaction.GetInteractionCouplesForOneProductId")
    @ResponseWrapper(localName = "getInteractionCouplesForOneProductIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.interaction.GetInteractionCouplesForOneProductIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.interaction.InteractionResult getInteractionCouplesForOneProductId(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        java.lang.Integer productId,
        @WebParam(name = "productIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.interaction.ArrayOfInt productIds,
        @WebParam(name = "severity", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.interaction.InteractionSeverityType severity
    );

    @WebResult(name = "interactionResult", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getInteractionCouplesForProductIds", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.interaction.GetInteractionCouplesForProductIds")
    @ResponseWrapper(localName = "getInteractionCouplesForProductIdsResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.interaction.GetInteractionCouplesForProductIdsResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.interaction.InteractionResult getInteractionCouplesForProductIds(
        @WebParam(name = "productIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.interaction.ArrayOfInt productIds,
        @WebParam(name = "severity", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.interaction.InteractionSeverityType severity
    );
}
