
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.vidal.merlin.wsclient.interaction;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:27 CET 2013
 * Generated source version: 2.2.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "InteractionService",
                      portName = "InteractionServiceHttpPort",
                      targetNamespace = "urn:Vidal",
                      wsdlLocation = "http://localhost:8011/merlin-service/services/InteractionService?wsdl",
                      endpointInterface = "com.vidal.merlin.wsclient.interaction.InteractionService")
                      
public class InteractionServiceImpl implements InteractionService {

    private static final Logger LOG = Logger.getLogger(InteractionServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.interaction.InteractionService#searchByInteractionId(java.lang.Integer  interactionId )*
     */
    public com.vidal.merlin.wsclient.interaction.Interaction searchByInteractionId(java.lang.Integer interactionId) { 
        LOG.info("Executing operation searchByInteractionId");
        System.out.println(interactionId);
        try {
            com.vidal.merlin.wsclient.interaction.Interaction _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.interaction.InteractionService#searchInteractionCouplesForProductIds(com.vidal.merlin.wsclient.interaction.ArrayOfInt  productIds ,)com.vidal.merlin.wsclient.interaction.InteractionSeverityType  severity )*
     */
    public com.vidal.merlin.wsclient.interaction.InteractionResult searchInteractionCouplesForProductIds(com.vidal.merlin.wsclient.interaction.ArrayOfInt productIds,com.vidal.merlin.wsclient.interaction.InteractionSeverityType severity) { 
        LOG.info("Executing operation searchInteractionCouplesForProductIds");
        System.out.println(productIds);
        System.out.println(severity);
        try {
            com.vidal.merlin.wsclient.interaction.InteractionResult _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.interaction.InteractionService#getInteractionCouplesForCommonNameGroupIds(com.vidal.merlin.wsclient.interaction.ArrayOfInt  commonNameGroupIds ,)com.vidal.merlin.wsclient.interaction.InteractionSeverityType  severity )*
     */
    public com.vidal.merlin.wsclient.interaction.InteractionCommonNameGroupResult getInteractionCouplesForCommonNameGroupIds(com.vidal.merlin.wsclient.interaction.ArrayOfInt commonNameGroupIds,com.vidal.merlin.wsclient.interaction.InteractionSeverityType severity) { 
        LOG.info("Executing operation getInteractionCouplesForCommonNameGroupIds");
        System.out.println(commonNameGroupIds);
        System.out.println(severity);
        try {
            com.vidal.merlin.wsclient.interaction.InteractionCommonNameGroupResult _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.interaction.InteractionService#searchInteractionCouplesForCommonNameGroupId(java.lang.Integer  commonNameGroupId ,)com.vidal.merlin.wsclient.interaction.ArrayOfInt  commonNameGroupIds ,)com.vidal.merlin.wsclient.interaction.InteractionSeverityType  severity )*
     */
    public com.vidal.merlin.wsclient.interaction.InteractionCommonNameGroupResult searchInteractionCouplesForCommonNameGroupId(java.lang.Integer commonNameGroupId,com.vidal.merlin.wsclient.interaction.ArrayOfInt commonNameGroupIds,com.vidal.merlin.wsclient.interaction.InteractionSeverityType severity) { 
        LOG.info("Executing operation searchInteractionCouplesForCommonNameGroupId");
        System.out.println(commonNameGroupId);
        System.out.println(commonNameGroupIds);
        System.out.println(severity);
        try {
            com.vidal.merlin.wsclient.interaction.InteractionCommonNameGroupResult _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.interaction.InteractionService#searchInteractionCouplesForProductId(java.lang.Integer  productId ,)com.vidal.merlin.wsclient.interaction.ArrayOfInt  productIds ,)com.vidal.merlin.wsclient.interaction.InteractionSeverityType  severity )*
     */
    public com.vidal.merlin.wsclient.interaction.InteractionResult searchInteractionCouplesForProductId(java.lang.Integer productId,com.vidal.merlin.wsclient.interaction.ArrayOfInt productIds,com.vidal.merlin.wsclient.interaction.InteractionSeverityType severity) { 
        LOG.info("Executing operation searchInteractionCouplesForProductId");
        System.out.println(productId);
        System.out.println(productIds);
        System.out.println(severity);
        try {
            com.vidal.merlin.wsclient.interaction.InteractionResult _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.interaction.InteractionService#searchInteractionCouplesForCommonNameGroupIds(com.vidal.merlin.wsclient.interaction.ArrayOfInt  commonNameGroupIds ,)com.vidal.merlin.wsclient.interaction.InteractionSeverityType  severity )*
     */
    public com.vidal.merlin.wsclient.interaction.InteractionCommonNameGroupResult searchInteractionCouplesForCommonNameGroupIds(com.vidal.merlin.wsclient.interaction.ArrayOfInt commonNameGroupIds,com.vidal.merlin.wsclient.interaction.InteractionSeverityType severity) { 
        LOG.info("Executing operation searchInteractionCouplesForCommonNameGroupIds");
        System.out.println(commonNameGroupIds);
        System.out.println(severity);
        try {
            com.vidal.merlin.wsclient.interaction.InteractionCommonNameGroupResult _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.interaction.InteractionService#getInteractionCouplesForOneProductId(java.lang.Integer  productId ,)com.vidal.merlin.wsclient.interaction.ArrayOfInt  productIds ,)com.vidal.merlin.wsclient.interaction.InteractionSeverityType  severity )*
     */
    public com.vidal.merlin.wsclient.interaction.InteractionResult getInteractionCouplesForOneProductId(java.lang.Integer productId,com.vidal.merlin.wsclient.interaction.ArrayOfInt productIds,com.vidal.merlin.wsclient.interaction.InteractionSeverityType severity) { 
        LOG.info("Executing operation getInteractionCouplesForOneProductId");
        System.out.println(productId);
        System.out.println(productIds);
        System.out.println(severity);
        try {
            com.vidal.merlin.wsclient.interaction.InteractionResult _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.interaction.InteractionService#getInteractionCouplesForProductIds(com.vidal.merlin.wsclient.interaction.ArrayOfInt  productIds ,)com.vidal.merlin.wsclient.interaction.InteractionSeverityType  severity )*
     */
    public com.vidal.merlin.wsclient.interaction.InteractionResult getInteractionCouplesForProductIds(com.vidal.merlin.wsclient.interaction.ArrayOfInt productIds,com.vidal.merlin.wsclient.interaction.InteractionSeverityType severity) { 
        LOG.info("Executing operation getInteractionCouplesForProductIds");
        System.out.println(productIds);
        System.out.println(severity);
        try {
            com.vidal.merlin.wsclient.interaction.InteractionResult _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
