
package com.vidal.merlin.wsclient.prescriptionAnalysis;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:26 CET 2013
 * Generated source version: 2.2.6
 * 
 */
 
public class DrugPrescriptionAnalysisService_DrugPrescriptionAnalysisServiceHttpPort_Server{

    protected DrugPrescriptionAnalysisService_DrugPrescriptionAnalysisServiceHttpPort_Server() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new DrugPrescriptionAnalysisServiceImpl();
        String address = "CHANGE_ME";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws Exception { 
        new DrugPrescriptionAnalysisService_DrugPrescriptionAnalysisServiceHttpPort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
