package com.vidal.merlin.wsclient.prescriptionAnalysis;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:26 CET 2013
 * Generated source version: 2.2.6
 * 
 */
 
@WebService(targetNamespace = "urn:Vidal", name = "drugPrescriptionAnalysisService")
@XmlSeeAlso({ObjectFactory.class})
public interface DrugPrescriptionAnalysisService {

    @WebResult(name = "patientFromObjToJson", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "patientFromObjToJson", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.prescriptionAnalysis.PatientFromObjToJson")
    @ResponseWrapper(localName = "patientFromObjToJsonResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.prescriptionAnalysis.PatientFromObjToJsonResponse")
    @WebMethod
    public java.lang.String patientFromObjToJson(
        @WebParam(name = "dateOfBirth", targetNamespace = "urn:Vidal")
        javax.xml.datatype.XMLGregorianCalendar dateOfBirth,
        @WebParam(name = "gender", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.Gender gender,
        @WebParam(name = "weight", targetNamespace = "urn:Vidal")
        java.lang.Integer weight,
        @WebParam(name = "height", targetNamespace = "urn:Vidal")
        java.lang.Integer height,
        @WebParam(name = "weeksOfAmenorrhea", targetNamespace = "urn:Vidal")
        java.lang.Integer weeksOfAmenorrhea,
        @WebParam(name = "breastFeeding", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.Breastfeeding breastFeeding,
        @WebParam(name = "creatin", targetNamespace = "urn:Vidal")
        java.lang.Integer creatin,
        @WebParam(name = "hepaticInsufficiency", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.HepaticInsufficiency hepaticInsufficiency,
        @WebParam(name = "allergyIdList", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.ArrayOfInt allergyIdList,
        @WebParam(name = "moleculeIdList", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.ArrayOfInt moleculeIdList,
        @WebParam(name = "pathologyCim10IdList", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.ArrayOfInt pathologyCim10IdList
    );

    @WebResult(name = "filteredAlerts", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getAlertsWithoutAlertTypes", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.prescriptionAnalysis.GetAlertsWithoutAlertTypes")
    @ResponseWrapper(localName = "getAlertsWithoutAlertTypesResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.prescriptionAnalysis.GetAlertsWithoutAlertTypesResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.prescriptionAnalysis.PrescriptionAnalysis getAlertsWithoutAlertTypes(
        @WebParam(name = "patient", targetNamespace = "urn:Vidal")
        java.lang.String patient,
        @WebParam(name = "prescriptionLineList", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.ArrayOfString prescriptionLineList,
        @WebParam(name = "withoutAlertTypes", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.ArrayOfAlertType withoutAlertTypes
    );

    @WebResult(name = "alertsAsHTML", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getAlertsAsHTML", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.prescriptionAnalysis.GetAlertsAsHTML")
    @ResponseWrapper(localName = "getAlertsAsHTMLResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.prescriptionAnalysis.GetAlertsAsHTMLResponse")
    @WebMethod
    public java.lang.String getAlertsAsHTML(
        @WebParam(name = "patient", targetNamespace = "urn:Vidal")
        java.lang.String patient,
        @WebParam(name = "prescriptionLineList", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.ArrayOfString prescriptionLineList
    );

    @WebResult(name = "prescriptionLineInActivePrincipleDosesFromObjToJson", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "prescriptionLineInActivePrincipleDosesFromObjToJson", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.prescriptionAnalysis.PrescriptionLineInActivePrincipleDosesFromObjToJson")
    @ResponseWrapper(localName = "prescriptionLineInActivePrincipleDosesFromObjToJsonResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.prescriptionAnalysis.PrescriptionLineInActivePrincipleDosesFromObjToJsonResponse")
    @WebMethod
    public java.lang.String prescriptionLineInActivePrincipleDosesFromObjToJson(
        @WebParam(name = "dose", targetNamespace = "urn:Vidal")
        java.lang.Double dose,
        @WebParam(name = "doseUnit", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.DoseUnit doseUnit,
        @WebParam(name = "frequencyType", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.PosologyFrequencyType frequencyType,
        @WebParam(name = "indicationIdList", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.ArrayOfInt indicationIdList,
        @WebParam(name = "routeIdList", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.ArrayOfInt routeIdList,
        @WebParam(name = "drugId", targetNamespace = "urn:Vidal")
        java.lang.Integer drugId,
        @WebParam(name = "drugType", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.DrugType drugType,
        @WebParam(name = "duration", targetNamespace = "urn:Vidal")
        java.lang.Integer duration,
        @WebParam(name = "durationType", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.DurationType durationType
    );

    @WebResult(name = "prescriptionLineFromObjToJsonUsingDrugCodes", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "prescriptionLineFromObjToJsonUsingDrugCodes", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.prescriptionAnalysis.PrescriptionLineFromObjToJsonUsingDrugCodes")
    @ResponseWrapper(localName = "prescriptionLineFromObjToJsonUsingDrugCodesResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.prescriptionAnalysis.PrescriptionLineFromObjToJsonUsingDrugCodesResponse")
    @WebMethod
    public java.lang.String prescriptionLineFromObjToJsonUsingDrugCodes(
        @WebParam(name = "dose", targetNamespace = "urn:Vidal")
        java.lang.Double dose,
        @WebParam(name = "unitId", targetNamespace = "urn:Vidal")
        java.lang.Integer unitId,
        @WebParam(name = "frequencyType", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.PosologyFrequencyType frequencyType,
        @WebParam(name = "indicationIdList", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.ArrayOfInt indicationIdList,
        @WebParam(name = "routeIdList", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.ArrayOfInt routeIdList,
        @WebParam(name = "drugCode", targetNamespace = "urn:Vidal")
        java.lang.String drugCode,
        @WebParam(name = "drugCodeType", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.DrugCodeType drugCodeType,
        @WebParam(name = "duration", targetNamespace = "urn:Vidal")
        java.lang.Integer duration,
        @WebParam(name = "durationType", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.DurationType durationType
    );

    @WebResult(name = "prescriptionLineFromObjToJson", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "prescriptionLineFromObjToJson", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.prescriptionAnalysis.PrescriptionLineFromObjToJson")
    @ResponseWrapper(localName = "prescriptionLineFromObjToJsonResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.prescriptionAnalysis.PrescriptionLineFromObjToJsonResponse")
    @WebMethod
    public java.lang.String prescriptionLineFromObjToJson(
        @WebParam(name = "dose", targetNamespace = "urn:Vidal")
        java.lang.Double dose,
        @WebParam(name = "unitId", targetNamespace = "urn:Vidal")
        java.lang.Integer unitId,
        @WebParam(name = "frequencyType", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.PosologyFrequencyType frequencyType,
        @WebParam(name = "indicationIdList", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.ArrayOfInt indicationIdList,
        @WebParam(name = "routeIdList", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.ArrayOfInt routeIdList,
        @WebParam(name = "drugId", targetNamespace = "urn:Vidal")
        java.lang.Integer drugId,
        @WebParam(name = "drugType", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.DrugType drugType
    );

    @WebResult(name = "recos", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchRecosByPrescriptions", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.prescriptionAnalysis.SearchRecosByPrescriptions")
    @ResponseWrapper(localName = "searchRecosByPrescriptionsResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.prescriptionAnalysis.SearchRecosByPrescriptionsResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.prescriptionAnalysis.ArrayOfCodedReco searchRecosByPrescriptions(
        @WebParam(name = "patient", targetNamespace = "urn:Vidal")
        java.lang.String patient,
        @WebParam(name = "prescriptionLineList", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.ArrayOfString prescriptionLineList
    );

    @WebResult(name = "prescriptionCostAnalysis", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getPrescriptionCostAnalysis", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.prescriptionAnalysis.GetPrescriptionCostAnalysis")
    @ResponseWrapper(localName = "getPrescriptionCostAnalysisResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.prescriptionAnalysis.GetPrescriptionCostAnalysisResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.prescriptionAnalysis.PrescriptionCostAnalysis getPrescriptionCostAnalysis(
        @WebParam(name = "prescriptionLines", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.ArrayOfString prescriptionLines
    );

    @WebResult(name = "prescriptionLineInDosesFromObjToJson", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "prescriptionLineInDosesFromObjToJson", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.prescriptionAnalysis.PrescriptionLineInDosesFromObjToJson")
    @ResponseWrapper(localName = "prescriptionLineInDosesFromObjToJsonResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.prescriptionAnalysis.PrescriptionLineInDosesFromObjToJsonResponse")
    @WebMethod
    public java.lang.String prescriptionLineInDosesFromObjToJson(
        @WebParam(name = "dose", targetNamespace = "urn:Vidal")
        java.lang.Double dose,
        @WebParam(name = "unitId", targetNamespace = "urn:Vidal")
        java.lang.Integer unitId,
        @WebParam(name = "frequencyType", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.PosologyFrequencyType frequencyType,
        @WebParam(name = "indicationIdList", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.ArrayOfInt indicationIdList,
        @WebParam(name = "routeIdList", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.ArrayOfInt routeIdList,
        @WebParam(name = "drugId", targetNamespace = "urn:Vidal")
        java.lang.Integer drugId,
        @WebParam(name = "drugType", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.DrugType drugType,
        @WebParam(name = "duration", targetNamespace = "urn:Vidal")
        java.lang.Integer duration,
        @WebParam(name = "durationType", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.DurationType durationType
    );

    @WebResult(name = "alerts", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getAlerts", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.prescriptionAnalysis.GetAlerts")
    @ResponseWrapper(localName = "getAlertsResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.prescriptionAnalysis.GetAlertsResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.prescriptionAnalysis.PrescriptionAnalysis getAlerts(
        @WebParam(name = "patient", targetNamespace = "urn:Vidal")
        java.lang.String patient,
        @WebParam(name = "prescriptionLineList", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.ArrayOfString prescriptionLineList
    );

    @WebResult(name = "patientFromObjToJsonUsingPathologyCodes", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "patientFromObjToJsonUsingPathologyCodes", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.prescriptionAnalysis.PatientFromObjToJsonUsingPathologyCodes")
    @ResponseWrapper(localName = "patientFromObjToJsonUsingPathologyCodesResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.prescriptionAnalysis.PatientFromObjToJsonUsingPathologyCodesResponse")
    @WebMethod
    public java.lang.String patientFromObjToJsonUsingPathologyCodes(
        @WebParam(name = "dateOfBirth", targetNamespace = "urn:Vidal")
        javax.xml.datatype.XMLGregorianCalendar dateOfBirth,
        @WebParam(name = "gender", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.Gender gender,
        @WebParam(name = "weight", targetNamespace = "urn:Vidal")
        java.lang.Double weight,
        @WebParam(name = "height", targetNamespace = "urn:Vidal")
        java.lang.Double height,
        @WebParam(name = "weeksOfAmenorrhea", targetNamespace = "urn:Vidal")
        java.lang.Integer weeksOfAmenorrhea,
        @WebParam(name = "breastFeeding", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.Breastfeeding breastFeeding,
        @WebParam(name = "creatin", targetNamespace = "urn:Vidal")
        java.lang.Integer creatin,
        @WebParam(name = "hepaticInsufficiency", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.HepaticInsufficiency hepaticInsufficiency,
        @WebParam(name = "allergyIdList", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.ArrayOfInt allergyIdList,
        @WebParam(name = "moleculeIdList", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.ArrayOfInt moleculeIdList,
        @WebParam(name = "pathologyCodes", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.ArrayOfString pathologyCodes
    );

    @WebResult(name = "summarizedAlert", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getSummarizedAlert", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.prescriptionAnalysis.GetSummarizedAlert")
    @ResponseWrapper(localName = "getSummarizedAlertResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.prescriptionAnalysis.GetSummarizedAlertResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.prescriptionAnalysis.ArrayOfDrugSummarizedAlertCouple getSummarizedAlert(
        @WebParam(name = "patient", targetNamespace = "urn:Vidal")
        java.lang.String patient,
        @WebParam(name = "prescriptionLineList", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.ArrayOfString prescriptionLineList
    );

    @WebResult(name = "getAlertsFull", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getAlertsFull", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.prescriptionAnalysis.GetAlertsFull")
    @ResponseWrapper(localName = "getAlertsFullResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.prescriptionAnalysis.GetAlertsFullResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.prescriptionAnalysis.PrescriptionAnalysisFull getAlertsFull(
        @WebParam(name = "patient", targetNamespace = "urn:Vidal")
        java.lang.String patient,
        @WebParam(name = "prescriptionLineList", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.ArrayOfString prescriptionLineList,
        @WebParam(name = "alertOutputList", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.prescriptionAnalysis.ArrayOfAlertOutput alertOutputList
    );
}
