
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.vidal.merlin.wsclient.genericGroup;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:27 CET 2013
 * Generated source version: 2.2.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "GenericGroupService",
                      portName = "GenericGroupServiceHttpPort",
                      targetNamespace = "urn:Vidal",
                      wsdlLocation = "http://localhost:8011/merlin-service/services/GenericGroupService?wsdl",
                      endpointInterface = "com.vidal.merlin.wsclient.genericGroup.GenericGroupService")
                      
public class GenericGroupServiceImpl implements GenericGroupService {

    private static final Logger LOG = Logger.getLogger(GenericGroupServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.genericGroup.GenericGroupService#searchByProductId(java.lang.Integer  productId )*
     */
    public com.vidal.merlin.wsclient.genericGroup.ArrayOfProductGenericGroup searchByProductId(java.lang.Integer productId) { 
        LOG.info("Executing operation searchByProductId");
        System.out.println(productId);
        try {
            com.vidal.merlin.wsclient.genericGroup.ArrayOfProductGenericGroup _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.genericGroup.GenericGroupService#searchByName(java.lang.String  name )*
     */
    public com.vidal.merlin.wsclient.genericGroup.ArrayOfGenericGroup searchByName(java.lang.String name) { 
        LOG.info("Executing operation searchByName");
        System.out.println(name);
        try {
            com.vidal.merlin.wsclient.genericGroup.ArrayOfGenericGroup _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.genericGroup.GenericGroupService#searchById(java.lang.Integer  genericGroupId )*
     */
    public com.vidal.merlin.wsclient.genericGroup.GenericGroup searchById(java.lang.Integer genericGroupId) { 
        LOG.info("Executing operation searchById");
        System.out.println(genericGroupId);
        try {
            com.vidal.merlin.wsclient.genericGroup.GenericGroup _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
