
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.vidal.merlin.wsclient.indicationGroup;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:27 CET 2013
 * Generated source version: 2.2.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "IndicationGroupService",
                      portName = "IndicationGroupServiceHttpPort",
                      targetNamespace = "urn:Vidal",
                      wsdlLocation = "http://localhost:8011/merlin-service/services/IndicationGroupService?wsdl",
                      endpointInterface = "com.vidal.merlin.wsclient.indicationGroup.IndicationGroupService")
                      
public class IndicationGroupServiceImpl implements IndicationGroupService {

    private static final Logger LOG = Logger.getLogger(IndicationGroupServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.indicationGroup.IndicationGroupService#searchByCispId(java.lang.Integer  cispId )*
     */
    public com.vidal.merlin.wsclient.indicationGroup.ArrayOfIndicationGroup searchByCispId(java.lang.Integer cispId) { 
        LOG.info("Executing operation searchByCispId");
        System.out.println(cispId);
        try {
            com.vidal.merlin.wsclient.indicationGroup.ArrayOfIndicationGroup _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.indicationGroup.IndicationGroupService#searchByProductId(java.lang.Integer  productId )*
     */
    public com.vidal.merlin.wsclient.indicationGroup.ArrayOfIndicationGroup searchByProductId(java.lang.Integer productId) { 
        LOG.info("Executing operation searchByProductId");
        System.out.println(productId);
        try {
            com.vidal.merlin.wsclient.indicationGroup.ArrayOfIndicationGroup _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.indicationGroup.IndicationGroupService#searchByName(java.lang.String  name )*
     */
    public com.vidal.merlin.wsclient.indicationGroup.ArrayOfIndicationGroup searchByName(java.lang.String name) { 
        LOG.info("Executing operation searchByName");
        System.out.println(name);
        try {
            com.vidal.merlin.wsclient.indicationGroup.ArrayOfIndicationGroup _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.indicationGroup.IndicationGroupService#postIndexingHealthTerminologyByProductIds(com.vidal.merlin.wsclient.indicationGroup.ArrayOfInt  productIds )*
     */
    public com.vidal.merlin.wsclient.indicationGroup.ArrayOfIndicationGroupScore postIndexingHealthTerminologyByProductIds(com.vidal.merlin.wsclient.indicationGroup.ArrayOfInt productIds) { 
        LOG.info("Executing operation postIndexingHealthTerminologyByProductIds");
        System.out.println(productIds);
        try {
            com.vidal.merlin.wsclient.indicationGroup.ArrayOfIndicationGroupScore _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.indicationGroup.IndicationGroupService#searchBySfmgId(java.lang.Integer  sfmgId )*
     */
    public com.vidal.merlin.wsclient.indicationGroup.ArrayOfIndicationGroup searchBySfmgId(java.lang.Integer sfmgId) { 
        LOG.info("Executing operation searchBySfmgId");
        System.out.println(sfmgId);
        try {
            com.vidal.merlin.wsclient.indicationGroup.ArrayOfIndicationGroup _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.indicationGroup.IndicationGroupService#searchById(java.lang.Integer  indicationGroupId )*
     */
    public com.vidal.merlin.wsclient.indicationGroup.IndicationGroup searchById(java.lang.Integer indicationGroupId) { 
        LOG.info("Executing operation searchById");
        System.out.println(indicationGroupId);
        try {
            com.vidal.merlin.wsclient.indicationGroup.IndicationGroup _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.indicationGroup.IndicationGroupService#searchByIndicationId(java.lang.Integer  indicationId )*
     */
    public com.vidal.merlin.wsclient.indicationGroup.ArrayOfIndicationGroup searchByIndicationId(java.lang.Integer indicationId) { 
        LOG.info("Executing operation searchByIndicationId");
        System.out.println(indicationId);
        try {
            com.vidal.merlin.wsclient.indicationGroup.ArrayOfIndicationGroup _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.indicationGroup.IndicationGroupService#searchByCim10Id(java.lang.Integer  cim10Id )*
     */
    public com.vidal.merlin.wsclient.indicationGroup.ArrayOfIndicationGroup searchByCim10Id(java.lang.Integer cim10Id) { 
        LOG.info("Executing operation searchByCim10Id");
        System.out.println(cim10Id);
        try {
            com.vidal.merlin.wsclient.indicationGroup.ArrayOfIndicationGroup _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.indicationGroup.IndicationGroupService#searchByCommonNameGroupId(java.lang.Integer  commonNameGroupId )*
     */
    public com.vidal.merlin.wsclient.indicationGroup.ArrayOfIndicationGroup searchByCommonNameGroupId(java.lang.Integer commonNameGroupId) { 
        LOG.info("Executing operation searchByCommonNameGroupId");
        System.out.println(commonNameGroupId);
        try {
            com.vidal.merlin.wsclient.indicationGroup.ArrayOfIndicationGroup _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
