
package com.vidal.merlin.wsclient.indicationGroup;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:27 CET 2013
 * Generated source version: 2.2.6
 * 
 */

public final class IndicationGroupService_IndicationGroupServiceHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("urn:Vidal", "IndicationGroupService");

    private IndicationGroupService_IndicationGroupServiceHttpPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = IndicationGroupService_Service.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        IndicationGroupService_Service ss = new IndicationGroupService_Service(wsdlURL, SERVICE_NAME);
        IndicationGroupService port = ss.getIndicationGroupServiceHttpPort();  
        
        {
        System.out.println("Invoking searchByCispId...");
        java.lang.Integer _searchByCispId_cispId = null;
        com.vidal.merlin.wsclient.indicationGroup.ArrayOfIndicationGroup _searchByCispId__return = port.searchByCispId(_searchByCispId_cispId);
        System.out.println("searchByCispId.result=" + _searchByCispId__return);


        }
        {
        System.out.println("Invoking searchByProductId...");
        java.lang.Integer _searchByProductId_productId = null;
        com.vidal.merlin.wsclient.indicationGroup.ArrayOfIndicationGroup _searchByProductId__return = port.searchByProductId(_searchByProductId_productId);
        System.out.println("searchByProductId.result=" + _searchByProductId__return);


        }
        {
        System.out.println("Invoking searchByName...");
        java.lang.String _searchByName_name = "";
        com.vidal.merlin.wsclient.indicationGroup.ArrayOfIndicationGroup _searchByName__return = port.searchByName(_searchByName_name);
        System.out.println("searchByName.result=" + _searchByName__return);


        }
        {
        System.out.println("Invoking postIndexingHealthTerminologyByProductIds...");
        com.vidal.merlin.wsclient.indicationGroup.ArrayOfInt _postIndexingHealthTerminologyByProductIds_productIds = null;
        com.vidal.merlin.wsclient.indicationGroup.ArrayOfIndicationGroupScore _postIndexingHealthTerminologyByProductIds__return = port.postIndexingHealthTerminologyByProductIds(_postIndexingHealthTerminologyByProductIds_productIds);
        System.out.println("postIndexingHealthTerminologyByProductIds.result=" + _postIndexingHealthTerminologyByProductIds__return);


        }
        {
        System.out.println("Invoking searchBySfmgId...");
        java.lang.Integer _searchBySfmgId_sfmgId = null;
        com.vidal.merlin.wsclient.indicationGroup.ArrayOfIndicationGroup _searchBySfmgId__return = port.searchBySfmgId(_searchBySfmgId_sfmgId);
        System.out.println("searchBySfmgId.result=" + _searchBySfmgId__return);


        }
        {
        System.out.println("Invoking searchById...");
        java.lang.Integer _searchById_indicationGroupId = null;
        com.vidal.merlin.wsclient.indicationGroup.IndicationGroup _searchById__return = port.searchById(_searchById_indicationGroupId);
        System.out.println("searchById.result=" + _searchById__return);


        }
        {
        System.out.println("Invoking searchByIndicationId...");
        java.lang.Integer _searchByIndicationId_indicationId = null;
        com.vidal.merlin.wsclient.indicationGroup.ArrayOfIndicationGroup _searchByIndicationId__return = port.searchByIndicationId(_searchByIndicationId_indicationId);
        System.out.println("searchByIndicationId.result=" + _searchByIndicationId__return);


        }
        {
        System.out.println("Invoking searchByCim10Id...");
        java.lang.Integer _searchByCim10Id_cim10Id = null;
        com.vidal.merlin.wsclient.indicationGroup.ArrayOfIndicationGroup _searchByCim10Id__return = port.searchByCim10Id(_searchByCim10Id_cim10Id);
        System.out.println("searchByCim10Id.result=" + _searchByCim10Id__return);


        }
        {
        System.out.println("Invoking searchByCommonNameGroupId...");
        java.lang.Integer _searchByCommonNameGroupId_commonNameGroupId = null;
        com.vidal.merlin.wsclient.indicationGroup.ArrayOfIndicationGroup _searchByCommonNameGroupId__return = port.searchByCommonNameGroupId(_searchByCommonNameGroupId_commonNameGroupId);
        System.out.println("searchByCommonNameGroupId.result=" + _searchByCommonNameGroupId__return);


        }

        System.exit(0);
    }

}
