
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.vidal.merlin.wsclient.drugInteractionClass;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:25 CET 2013
 * Generated source version: 2.2.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "DrugInteractionClassService",
                      portName = "DrugInteractionClassServiceHttpPort",
                      targetNamespace = "urn:Vidal",
                      wsdlLocation = "http://localhost:8011/merlin-service/services/DrugInteractionClassService?wsdl",
                      endpointInterface = "com.vidal.merlin.wsclient.drugInteractionClass.DrugInteractionClassService")
                      
public class DrugInteractionClassServiceImpl implements DrugInteractionClassService {

    private static final Logger LOG = Logger.getLogger(DrugInteractionClassServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.drugInteractionClass.DrugInteractionClassService#searchAllInteractingClassesWithDrugInteractionClassId(java.lang.Integer  drugInteractionClassId )*
     */
    public com.vidal.merlin.wsclient.drugInteractionClass.ArrayOfDrugInteractionClassSeverityCouple searchAllInteractingClassesWithDrugInteractionClassId(java.lang.Integer drugInteractionClassId) { 
        LOG.info("Executing operation searchAllInteractingClassesWithDrugInteractionClassId");
        System.out.println(drugInteractionClassId);
        try {
            com.vidal.merlin.wsclient.drugInteractionClass.ArrayOfDrugInteractionClassSeverityCouple _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.drugInteractionClass.DrugInteractionClassService#searchByInteractionId(java.lang.Integer  interactionId )*
     */
    public com.vidal.merlin.wsclient.drugInteractionClass.ArrayOfDrugInteractionClass searchByInteractionId(java.lang.Integer interactionId) { 
        LOG.info("Executing operation searchByInteractionId");
        System.out.println(interactionId);
        try {
            com.vidal.merlin.wsclient.drugInteractionClass.ArrayOfDrugInteractionClass _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.drugInteractionClass.DrugInteractionClassService#searchByProductId(java.lang.Integer  productId )*
     */
    public com.vidal.merlin.wsclient.drugInteractionClass.ArrayOfDrugInteractionClass searchByProductId(java.lang.Integer productId) { 
        LOG.info("Executing operation searchByProductId");
        System.out.println(productId);
        try {
            com.vidal.merlin.wsclient.drugInteractionClass.ArrayOfDrugInteractionClass _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.drugInteractionClass.DrugInteractionClassService#searchByName(java.lang.String  name )*
     */
    public com.vidal.merlin.wsclient.drugInteractionClass.ArrayOfDrugInteractionClass searchByName(java.lang.String name) { 
        LOG.info("Executing operation searchByName");
        System.out.println(name);
        try {
            com.vidal.merlin.wsclient.drugInteractionClass.ArrayOfDrugInteractionClass _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.drugInteractionClass.DrugInteractionClassService#searchById(java.lang.Integer  drugInteractionClassId )*
     */
    public com.vidal.merlin.wsclient.drugInteractionClass.DrugInteractionClass searchById(java.lang.Integer drugInteractionClassId) { 
        LOG.info("Executing operation searchById");
        System.out.println(drugInteractionClassId);
        try {
            com.vidal.merlin.wsclient.drugInteractionClass.DrugInteractionClass _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.drugInteractionClass.DrugInteractionClassService#searchByCommonNameGroupId(java.lang.Integer  commonNameGroupId )*
     */
    public com.vidal.merlin.wsclient.drugInteractionClass.CommonNameGroupDrugInteractionClassList searchByCommonNameGroupId(java.lang.Integer commonNameGroupId) { 
        LOG.info("Executing operation searchByCommonNameGroupId");
        System.out.println(commonNameGroupId);
        try {
            com.vidal.merlin.wsclient.drugInteractionClass.CommonNameGroupDrugInteractionClassList _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
