package com.vidal.merlin.wsclient.semp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:32 CET 2013
 * Generated source version: 2.2.6
 * 
 */
 
@WebService(targetNamespace = "urn:Vidal", name = "sempService")
@XmlSeeAlso({ObjectFactory.class})
public interface SempService {

    @WebResult(name = "sempList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByProductId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.semp.SearchByProductId")
    @ResponseWrapper(localName = "searchByProductIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.semp.SearchByProductIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.semp.ArrayOfSemp searchByProductId(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        java.lang.Integer productId
    );

    @WebResult(name = "sempList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByName", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.semp.SearchByName")
    @ResponseWrapper(localName = "searchByNameResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.semp.SearchByNameResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.semp.ArrayOfSemp searchByName(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        java.lang.String name
    );

    @WebResult(name = "sempList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getChildren", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.semp.GetChildren")
    @ResponseWrapper(localName = "getChildrenResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.semp.GetChildrenResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.semp.ArrayOfSemp getChildren(
        @WebParam(name = "sempId", targetNamespace = "urn:Vidal")
        java.lang.Integer sempId
    );

    @WebResult(name = "semp", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getRootNode", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.semp.GetRootNode")
    @ResponseWrapper(localName = "getRootNodeResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.semp.GetRootNodeResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.semp.Semp getRootNode();

    @WebResult(name = "semp", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchById", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.semp.SearchById")
    @ResponseWrapper(localName = "searchByIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.semp.SearchByIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.semp.Semp searchById(
        @WebParam(name = "sempId", targetNamespace = "urn:Vidal")
        java.lang.Integer sempId
    );

    @WebResult(name = "semp", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getParent", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.semp.GetParent")
    @ResponseWrapper(localName = "getParentResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.semp.GetParentResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.semp.Semp getParent(
        @WebParam(name = "sempId", targetNamespace = "urn:Vidal")
        java.lang.Integer sempId
    );
}
