
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.vidal.merlin.wsclient.semp;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:32 CET 2013
 * Generated source version: 2.2.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "SempService",
                      portName = "SempServiceHttpPort",
                      targetNamespace = "urn:Vidal",
                      wsdlLocation = "http://localhost:8011/merlin-service/services/SempService?wsdl",
                      endpointInterface = "com.vidal.merlin.wsclient.semp.SempService")
                      
public class SempServiceImpl implements SempService {

    private static final Logger LOG = Logger.getLogger(SempServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.semp.SempService#searchByProductId(java.lang.Integer  productId )*
     */
    public com.vidal.merlin.wsclient.semp.ArrayOfSemp searchByProductId(java.lang.Integer productId) { 
        LOG.info("Executing operation searchByProductId");
        System.out.println(productId);
        try {
            com.vidal.merlin.wsclient.semp.ArrayOfSemp _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.semp.SempService#searchByName(java.lang.String  name )*
     */
    public com.vidal.merlin.wsclient.semp.ArrayOfSemp searchByName(java.lang.String name) { 
        LOG.info("Executing operation searchByName");
        System.out.println(name);
        try {
            com.vidal.merlin.wsclient.semp.ArrayOfSemp _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.semp.SempService#getChildren(java.lang.Integer  sempId )*
     */
    public com.vidal.merlin.wsclient.semp.ArrayOfSemp getChildren(java.lang.Integer sempId) { 
        LOG.info("Executing operation getChildren");
        System.out.println(sempId);
        try {
            com.vidal.merlin.wsclient.semp.ArrayOfSemp _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.semp.SempService#getRootNode(*
     */
    public com.vidal.merlin.wsclient.semp.Semp getRootNode() { 
        LOG.info("Executing operation getRootNode");
        try {
            com.vidal.merlin.wsclient.semp.Semp _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.semp.SempService#searchById(java.lang.Integer  sempId )*
     */
    public com.vidal.merlin.wsclient.semp.Semp searchById(java.lang.Integer sempId) { 
        LOG.info("Executing operation searchById");
        System.out.println(sempId);
        try {
            com.vidal.merlin.wsclient.semp.Semp _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.semp.SempService#getParent(java.lang.Integer  sempId )*
     */
    public com.vidal.merlin.wsclient.semp.Semp getParent(java.lang.Integer sempId) { 
        LOG.info("Executing operation getParent");
        System.out.println(sempId);
        try {
            com.vidal.merlin.wsclient.semp.Semp _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
