
package com.vidal.merlin.wsclient.contraIndication;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:24 CET 2013
 * Generated source version: 2.2.6
 * 
 */

public final class ContraIndicationService_ContraIndicationServiceHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("urn:Vidal", "ContraIndicationService");

    private ContraIndicationService_ContraIndicationServiceHttpPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = ContraIndicationService_Service.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ContraIndicationService_Service ss = new ContraIndicationService_Service(wsdlURL, SERVICE_NAME);
        ContraIndicationService port = ss.getContraIndicationServiceHttpPort();  
        
        {
        System.out.println("Invoking searchContraIndicationProductCoupleById...");
        java.lang.Integer _searchContraIndicationProductCoupleById_productId = null;
        com.vidal.merlin.wsclient.contraIndication.ArrayOfContraIndicationProductCouple _searchContraIndicationProductCoupleById__return = port.searchContraIndicationProductCoupleById(_searchContraIndicationProductCoupleById_productId);
        System.out.println("searchContraIndicationProductCoupleById.result=" + _searchContraIndicationProductCoupleById__return);


        }
        {
        System.out.println("Invoking searchContraIndicationCim10CoupleByIds...");
        com.vidal.merlin.wsclient.contraIndication.ArrayOfInt _searchContraIndicationCim10CoupleByIds_productIds = null;
        com.vidal.merlin.wsclient.contraIndication.ArrayOfInt _searchContraIndicationCim10CoupleByIds_cim10Ids = null;
        com.vidal.merlin.wsclient.contraIndication.ArrayOfContraIndicationCim10Couple _searchContraIndicationCim10CoupleByIds__return = port.searchContraIndicationCim10CoupleByIds(_searchContraIndicationCim10CoupleByIds_productIds, _searchContraIndicationCim10CoupleByIds_cim10Ids);
        System.out.println("searchContraIndicationCim10CoupleByIds.result=" + _searchContraIndicationCim10CoupleByIds__return);


        }
        {
        System.out.println("Invoking searchByProductId...");
        java.lang.Integer _searchByProductId_productId = null;
        com.vidal.merlin.wsclient.contraIndication.ArrayOfContraIndicationProductCouple _searchByProductId__return = port.searchByProductId(_searchByProductId_productId);
        System.out.println("searchByProductId.result=" + _searchByProductId__return);


        }
        {
        System.out.println("Invoking searchByCommonNameGroupIdsAndEpp...");
        com.vidal.merlin.wsclient.contraIndication.ArrayOfInt _searchByCommonNameGroupIdsAndEpp_commonNameGroupIds = null;
        javax.xml.datatype.XMLGregorianCalendar _searchByCommonNameGroupIdsAndEpp_dateOfBirth = null;
        java.lang.Integer _searchByCommonNameGroupIdsAndEpp_weight = null;
        com.vidal.merlin.wsclient.contraIndication.Breastfeeding _searchByCommonNameGroupIdsAndEpp_breastfeeding = null;
        java.lang.Integer _searchByCommonNameGroupIdsAndEpp_weeksOfAmenorrhoea = null;
        java.lang.Integer _searchByCommonNameGroupIdsAndEpp_creatinClearance = null;
        com.vidal.merlin.wsclient.contraIndication.Gender _searchByCommonNameGroupIdsAndEpp_gender = null;
        com.vidal.merlin.wsclient.contraIndication.CommonNameGroupContraIndicationEppList _searchByCommonNameGroupIdsAndEpp__return = port.searchByCommonNameGroupIdsAndEpp(_searchByCommonNameGroupIdsAndEpp_commonNameGroupIds, _searchByCommonNameGroupIdsAndEpp_dateOfBirth, _searchByCommonNameGroupIdsAndEpp_weight, _searchByCommonNameGroupIdsAndEpp_breastfeeding, _searchByCommonNameGroupIdsAndEpp_weeksOfAmenorrhoea, _searchByCommonNameGroupIdsAndEpp_creatinClearance, _searchByCommonNameGroupIdsAndEpp_gender);
        System.out.println("searchByCommonNameGroupIdsAndEpp.result=" + _searchByCommonNameGroupIdsAndEpp__return);


        }
        {
        System.out.println("Invoking searchContraIndicationEPPCoupleByIds...");
        com.vidal.merlin.wsclient.contraIndication.ArrayOfInt _searchContraIndicationEPPCoupleByIds_productIds = null;
        javax.xml.datatype.XMLGregorianCalendar _searchContraIndicationEPPCoupleByIds_dateOfBirth = null;
        java.lang.Integer _searchContraIndicationEPPCoupleByIds_weight = null;
        com.vidal.merlin.wsclient.contraIndication.Breastfeeding _searchContraIndicationEPPCoupleByIds_breastfeeding = null;
        java.lang.Integer _searchContraIndicationEPPCoupleByIds_weeksOfAmenorrhoea = null;
        java.lang.Integer _searchContraIndicationEPPCoupleByIds_creatinClearance = null;
        com.vidal.merlin.wsclient.contraIndication.Gender _searchContraIndicationEPPCoupleByIds_gender = null;
        com.vidal.merlin.wsclient.contraIndication.ArrayOfContraIndicationEPPCouple _searchContraIndicationEPPCoupleByIds__return = port.searchContraIndicationEPPCoupleByIds(_searchContraIndicationEPPCoupleByIds_productIds, _searchContraIndicationEPPCoupleByIds_dateOfBirth, _searchContraIndicationEPPCoupleByIds_weight, _searchContraIndicationEPPCoupleByIds_breastfeeding, _searchContraIndicationEPPCoupleByIds_weeksOfAmenorrhoea, _searchContraIndicationEPPCoupleByIds_creatinClearance, _searchContraIndicationEPPCoupleByIds_gender);
        System.out.println("searchContraIndicationEPPCoupleByIds.result=" + _searchContraIndicationEPPCoupleByIds__return);


        }
        {
        System.out.println("Invoking searchByName...");
        java.lang.String _searchByName_name = "";
        com.vidal.merlin.wsclient.contraIndication.ArrayOfContraIndication _searchByName__return = port.searchByName(_searchByName_name);
        System.out.println("searchByName.result=" + _searchByName__return);


        }
        {
        System.out.println("Invoking searchByCommonNameGroupIdAndCim10Ids...");
        java.lang.Integer _searchByCommonNameGroupIdAndCim10Ids_commonNameGroupId = null;
        com.vidal.merlin.wsclient.contraIndication.ArrayOfInt _searchByCommonNameGroupIdAndCim10Ids_cim10Ids = null;
        com.vidal.merlin.wsclient.contraIndication.CommonNameGroupContraIndicationCim10List _searchByCommonNameGroupIdAndCim10Ids__return = port.searchByCommonNameGroupIdAndCim10Ids(_searchByCommonNameGroupIdAndCim10Ids_commonNameGroupId, _searchByCommonNameGroupIdAndCim10Ids_cim10Ids);
        System.out.println("searchByCommonNameGroupIdAndCim10Ids.result=" + _searchByCommonNameGroupIdAndCim10Ids__return);


        }
        {
        System.out.println("Invoking searchByCommonNameGroupIdAndEpp...");
        java.lang.Integer _searchByCommonNameGroupIdAndEpp_commonNameGroupId = null;
        javax.xml.datatype.XMLGregorianCalendar _searchByCommonNameGroupIdAndEpp_dateOfBirth = null;
        java.lang.Integer _searchByCommonNameGroupIdAndEpp_weight = null;
        com.vidal.merlin.wsclient.contraIndication.Breastfeeding _searchByCommonNameGroupIdAndEpp_breastfeeding = null;
        java.lang.Integer _searchByCommonNameGroupIdAndEpp_weeksOfAmenorrhoea = null;
        java.lang.Integer _searchByCommonNameGroupIdAndEpp_creatinClearance = null;
        com.vidal.merlin.wsclient.contraIndication.Gender _searchByCommonNameGroupIdAndEpp_gender = null;
        com.vidal.merlin.wsclient.contraIndication.CommonNameGroupContraIndicationEppList _searchByCommonNameGroupIdAndEpp__return = port.searchByCommonNameGroupIdAndEpp(_searchByCommonNameGroupIdAndEpp_commonNameGroupId, _searchByCommonNameGroupIdAndEpp_dateOfBirth, _searchByCommonNameGroupIdAndEpp_weight, _searchByCommonNameGroupIdAndEpp_breastfeeding, _searchByCommonNameGroupIdAndEpp_weeksOfAmenorrhoea, _searchByCommonNameGroupIdAndEpp_creatinClearance, _searchByCommonNameGroupIdAndEpp_gender);
        System.out.println("searchByCommonNameGroupIdAndEpp.result=" + _searchByCommonNameGroupIdAndEpp__return);


        }
        {
        System.out.println("Invoking searchContraIndicationCim10CoupleAndChildrenByIds...");
        com.vidal.merlin.wsclient.contraIndication.ArrayOfInt _searchContraIndicationCim10CoupleAndChildrenByIds_productIds = null;
        com.vidal.merlin.wsclient.contraIndication.ArrayOfInt _searchContraIndicationCim10CoupleAndChildrenByIds_cim10Ids = null;
        com.vidal.merlin.wsclient.contraIndication.ArrayOfContraIndicationCim10Couple _searchContraIndicationCim10CoupleAndChildrenByIds__return = port.searchContraIndicationCim10CoupleAndChildrenByIds(_searchContraIndicationCim10CoupleAndChildrenByIds_productIds, _searchContraIndicationCim10CoupleAndChildrenByIds_cim10Ids);
        System.out.println("searchContraIndicationCim10CoupleAndChildrenByIds.result=" + _searchContraIndicationCim10CoupleAndChildrenByIds__return);


        }
        {
        System.out.println("Invoking searchByCommonNameGroupIdAndCim10IdsWithChildren...");
        java.lang.Integer _searchByCommonNameGroupIdAndCim10IdsWithChildren_commonNameGroupId = null;
        com.vidal.merlin.wsclient.contraIndication.ArrayOfInt _searchByCommonNameGroupIdAndCim10IdsWithChildren_cim10Ids = null;
        com.vidal.merlin.wsclient.contraIndication.CommonNameGroupContraIndicationCim10List _searchByCommonNameGroupIdAndCim10IdsWithChildren__return = port.searchByCommonNameGroupIdAndCim10IdsWithChildren(_searchByCommonNameGroupIdAndCim10IdsWithChildren_commonNameGroupId, _searchByCommonNameGroupIdAndCim10IdsWithChildren_cim10Ids);
        System.out.println("searchByCommonNameGroupIdAndCim10IdsWithChildren.result=" + _searchByCommonNameGroupIdAndCim10IdsWithChildren__return);


        }
        {
        System.out.println("Invoking searchBySfmgId...");
        java.lang.Integer _searchBySfmgId_sfmgId = null;
        com.vidal.merlin.wsclient.contraIndication.ArrayOfContraIndication _searchBySfmgId__return = port.searchBySfmgId(_searchBySfmgId_sfmgId);
        System.out.println("searchBySfmgId.result=" + _searchBySfmgId__return);


        }
        {
        System.out.println("Invoking searchById...");
        java.lang.Integer _searchById_contraIndicationId = null;
        com.vidal.merlin.wsclient.contraIndication.ContraIndication _searchById__return = port.searchById(_searchById_contraIndicationId);
        System.out.println("searchById.result=" + _searchById__return);


        }
        {
        System.out.println("Invoking searchByCim10Id...");
        java.lang.Integer _searchByCim10Id_cim10Id = null;
        com.vidal.merlin.wsclient.contraIndication.ArrayOfContraIndication _searchByCim10Id__return = port.searchByCim10Id(_searchByCim10Id_cim10Id);
        System.out.println("searchByCim10Id.result=" + _searchByCim10Id__return);


        }
        {
        System.out.println("Invoking searchByProductsIdsAndEpp...");
        com.vidal.merlin.wsclient.contraIndication.ArrayOfInt _searchByProductsIdsAndEpp_productIds = null;
        javax.xml.datatype.XMLGregorianCalendar _searchByProductsIdsAndEpp_dateOfBirth = null;
        java.lang.Integer _searchByProductsIdsAndEpp_weight = null;
        com.vidal.merlin.wsclient.contraIndication.Breastfeeding _searchByProductsIdsAndEpp_breastfeeding = null;
        java.lang.Integer _searchByProductsIdsAndEpp_weeksOfAmenorrhoea = null;
        java.lang.Integer _searchByProductsIdsAndEpp_creatinClearance = null;
        com.vidal.merlin.wsclient.contraIndication.Gender _searchByProductsIdsAndEpp_gender = null;
        com.vidal.merlin.wsclient.contraIndication.ProductContraIndicationEppList _searchByProductsIdsAndEpp__return = port.searchByProductsIdsAndEpp(_searchByProductsIdsAndEpp_productIds, _searchByProductsIdsAndEpp_dateOfBirth, _searchByProductsIdsAndEpp_weight, _searchByProductsIdsAndEpp_breastfeeding, _searchByProductsIdsAndEpp_weeksOfAmenorrhoea, _searchByProductsIdsAndEpp_creatinClearance, _searchByProductsIdsAndEpp_gender);
        System.out.println("searchByProductsIdsAndEpp.result=" + _searchByProductsIdsAndEpp__return);


        }
        {
        System.out.println("Invoking searchByCommonNameGroupId...");
        java.lang.Integer _searchByCommonNameGroupId_commonNameGroupId = null;
        com.vidal.merlin.wsclient.contraIndication.CommonNameGroupContraIndicationList _searchByCommonNameGroupId__return = port.searchByCommonNameGroupId(_searchByCommonNameGroupId_commonNameGroupId);
        System.out.println("searchByCommonNameGroupId.result=" + _searchByCommonNameGroupId__return);


        }

        System.exit(0);
    }

}
