
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.vidal.merlin.wsclient.redundantInteraction;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:32 CET 2013
 * Generated source version: 2.2.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "RedundantInteractionService",
                      portName = "RedundantInteractionServiceHttpPort",
                      targetNamespace = "urn:Vidal",
                      wsdlLocation = "http://localhost:8011/merlin-service/services/RedundantInteractionService?wsdl",
                      endpointInterface = "com.vidal.merlin.wsclient.redundantInteraction.RedundantInteractionService")
                      
public class RedundantInteractionServiceImpl implements RedundantInteractionService {

    private static final Logger LOG = Logger.getLogger(RedundantInteractionServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.redundantInteraction.RedundantInteractionService#searchRedundantInteractionByCommonNameGroupIds(com.vidal.merlin.wsclient.redundantInteraction.ArrayOfInt  commonNameGroupIds )*
     */
    public com.vidal.merlin.wsclient.redundantInteraction.ArrayOfRedundantInteractionCommonNameGroupCouple searchRedundantInteractionByCommonNameGroupIds(com.vidal.merlin.wsclient.redundantInteraction.ArrayOfInt commonNameGroupIds) { 
        LOG.info("Executing operation searchRedundantInteractionByCommonNameGroupIds");
        System.out.println(commonNameGroupIds);
        try {
            com.vidal.merlin.wsclient.redundantInteraction.ArrayOfRedundantInteractionCommonNameGroupCouple _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.redundantInteraction.RedundantInteractionService#searchRedundantInteraction(com.vidal.merlin.wsclient.redundantInteraction.ArrayOfInt  productIds )*
     */
    public com.vidal.merlin.wsclient.redundantInteraction.ArrayOfRedundantInteractionCouple searchRedundantInteraction(com.vidal.merlin.wsclient.redundantInteraction.ArrayOfInt productIds) { 
        LOG.info("Executing operation searchRedundantInteraction");
        System.out.println(productIds);
        try {
            com.vidal.merlin.wsclient.redundantInteraction.ArrayOfRedundantInteractionCouple _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.redundantInteraction.RedundantInteractionService#searchRedundantInteractionByProductIds(com.vidal.merlin.wsclient.redundantInteraction.ArrayOfInt  productIds )*
     */
    public com.vidal.merlin.wsclient.redundantInteraction.ArrayOfRedundantInteractionCouple searchRedundantInteractionByProductIds(com.vidal.merlin.wsclient.redundantInteraction.ArrayOfInt productIds) { 
        LOG.info("Executing operation searchRedundantInteractionByProductIds");
        System.out.println(productIds);
        try {
            com.vidal.merlin.wsclient.redundantInteraction.ArrayOfRedundantInteractionCouple _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
