package com.vidal.merlin.wsclient.physicoChemicalInteraction;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:29 CET 2013
 * Generated source version: 2.2.6
 * 
 */
 
@WebService(targetNamespace = "urn:Vidal", name = "physicoChemicalInteractionService")
@XmlSeeAlso({ObjectFactory.class})
public interface PhysicoChemicalInteractionService {

    @WebResult(name = "physicoChemicalInteractionList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchCommentByProductId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.physicoChemicalInteraction.SearchCommentByProductId")
    @ResponseWrapper(localName = "searchCommentByProductIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.physicoChemicalInteraction.SearchCommentByProductIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.physicoChemicalInteraction.ArrayOfPhysicoChemicalInteractionCommentCouple searchCommentByProductId(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        java.lang.Integer productId
    );

    @WebResult(name = "physicoChemicalInteractionList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByProductId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.physicoChemicalInteraction.SearchByProductId")
    @ResponseWrapper(localName = "searchByProductIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.physicoChemicalInteraction.SearchByProductIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.physicoChemicalInteraction.ArrayOfPhysicoChemicalInteraction searchByProductId(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        java.lang.Integer productId
    );

    @WebResult(name = "physicoChemicalInteractionList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByName", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.physicoChemicalInteraction.SearchByName")
    @ResponseWrapper(localName = "searchByNameResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.physicoChemicalInteraction.SearchByNameResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.physicoChemicalInteraction.ArrayOfPhysicoChemicalInteraction searchByName(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        java.lang.String name
    );

    @WebResult(name = "physicoChemicalInteraction", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchById", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.physicoChemicalInteraction.SearchById")
    @ResponseWrapper(localName = "searchByIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.physicoChemicalInteraction.SearchByIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.physicoChemicalInteraction.PhysicoChemicalInteraction searchById(
        @WebParam(name = "physicoChemicalInteractionId", targetNamespace = "urn:Vidal")
        java.lang.Integer physicoChemicalInteractionId
    );

    @WebResult(name = "physicoChemicalInteraction", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchOneByName", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.physicoChemicalInteraction.SearchOneByName")
    @ResponseWrapper(localName = "searchOneByNameResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.physicoChemicalInteraction.SearchOneByNameResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.physicoChemicalInteraction.PhysicoChemicalInteraction searchOneByName(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        java.lang.String name
    );

    @WebResult(name = "physicoChemicalInteractionList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByCommonNameGroupId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.physicoChemicalInteraction.SearchByCommonNameGroupId")
    @ResponseWrapper(localName = "searchByCommonNameGroupIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.physicoChemicalInteraction.SearchByCommonNameGroupIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.physicoChemicalInteraction.ArrayOfPhysicoChemicalInteractionCommentCouple searchByCommonNameGroupId(
        @WebParam(name = "commonNameGroupId", targetNamespace = "urn:Vidal")
        java.lang.Integer commonNameGroupId
    );
}
