
/*
 * 
 */

package com.vidal.merlin.wsclient.ald;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:20 CET 2013
 * Generated source version: 2.2.6
 * 
 */


@WebServiceClient(name = "AldService", 
                  wsdlLocation = "http://localhost:8011/merlin-service/services/AldService?wsdl",
                  targetNamespace = "urn:Vidal") 
public class AldService_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("urn:Vidal", "AldService");
    public final static QName AldServiceHttpPort = new QName("urn:Vidal", "AldServiceHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8011/merlin-service/services/AldService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8011/merlin-service/services/AldService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public AldService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AldService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AldService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns AldService
     */
    @WebEndpoint(name = "AldServiceHttpPort")
    public AldService getAldServiceHttpPort() {
        return super.getPort(AldServiceHttpPort, AldService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AldService
     */
    @WebEndpoint(name = "AldServiceHttpPort")
    public AldService getAldServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(AldServiceHttpPort, AldService.class, features);
    }

}
