
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.vidal.merlin.wsclient.ald;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:20 CET 2013
 * Generated source version: 2.2.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "AldService",
                      portName = "AldServiceHttpPort",
                      targetNamespace = "urn:Vidal",
                      wsdlLocation = "http://localhost:8011/merlin-service/services/AldService?wsdl",
                      endpointInterface = "com.vidal.merlin.wsclient.ald.AldService")
                      
public class AldServiceImpl implements AldService {

    private static final Logger LOG = Logger.getLogger(AldServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.ald.AldService#searchByProductIds(com.vidal.merlin.wsclient.ald.ArrayOfInt  productIds )*
     */
    public com.vidal.merlin.wsclient.ald.ArrayOfProductAldAtcListCouple searchByProductIds(com.vidal.merlin.wsclient.ald.ArrayOfInt productIds) { 
        LOG.info("Executing operation searchByProductIds");
        System.out.println(productIds);
        try {
            com.vidal.merlin.wsclient.ald.ArrayOfProductAldAtcListCouple _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
