package com.vidal.merlin.wsclient.product;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:31 CET 2013
 * Generated source version: 2.2.6
 * 
 */
 
@WebService(targetNamespace = "urn:Vidal", name = "productService")
@XmlSeeAlso({ObjectFactory.class})
public interface ProductService {

    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchWithoutInteractionsByVidalId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchWithoutInteractionsByVidalId")
    @ResponseWrapper(localName = "searchWithoutInteractionsByVidalIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchWithoutInteractionsByVidalIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfProduct searchWithoutInteractionsByVidalId(
        @WebParam(name = "productIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.product.ArrayOfInt productIds,
        @WebParam(name = "vidalId", targetNamespace = "urn:Vidal")
        java.lang.Integer vidalId
    );

    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByDrugInteractionClassId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByDrugInteractionClassId")
    @ResponseWrapper(localName = "searchByDrugInteractionClassIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByDrugInteractionClassIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfProduct searchByDrugInteractionClassId(
        @WebParam(name = "drugInteractionClassId", targetNamespace = "urn:Vidal")
        java.lang.Integer drugInteractionClassId
    );

    @WebResult(name = "productFullList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getProductFullByIds", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.GetProductFullByIds")
    @ResponseWrapper(localName = "getProductFullByIdsResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.GetProductFullByIdsResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfProductFull getProductFullByIds(
        @WebParam(name = "productIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.product.ArrayOfInt productIds,
        @WebParam(name = "aggregates", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.product.ArrayOfAggregate aggregates
    );

    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByMoleculeIdAndType", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByMoleculeIdAndType")
    @ResponseWrapper(localName = "searchByMoleculeIdAndTypeResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByMoleculeIdAndTypeResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfProduct searchByMoleculeIdAndType(
        @WebParam(name = "moleculeId", targetNamespace = "urn:Vidal")
        java.lang.Integer moleculeId,
        @WebParam(name = "substanceType", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.product.SubstanceType substanceType
    );

    @WebResult(name = "galenicForm", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getGalenicForm", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.GetGalenicForm")
    @ResponseWrapper(localName = "getGalenicFormResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.GetGalenicFormResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.GalenicForm getGalenicForm(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        java.lang.Integer productId
    );

    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByMoleculeId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByMoleculeId")
    @ResponseWrapper(localName = "searchByMoleculeIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByMoleculeIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfProduct searchByMoleculeId(
        @WebParam(name = "moleculeId", targetNamespace = "urn:Vidal")
        java.lang.Integer moleculeId
    );

    @WebResult(name = "pagedResultProductFull", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getAllProductFull", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.GetAllProductFull")
    @ResponseWrapper(localName = "getAllProductFullResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.GetAllProductFullResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.PagedResultProductFull getAllProductFull(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        java.lang.String name,
        @WebParam(name = "marketStatuses", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.product.ArrayOfMarketStatus marketStatuses,
        @WebParam(name = "productApiFilter", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.product.ProductApiFilter productApiFilter,
        @WebParam(name = "types", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.product.ArrayOfProductType types,
        @WebParam(name = "aggregates", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.product.ArrayOfAggregate aggregates,
        @WebParam(name = "pageNumber", targetNamespace = "urn:Vidal")
        java.lang.Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "urn:Vidal")
        java.lang.Integer pageSize
    );

    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByCodes", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByCodes")
    @ResponseWrapper(localName = "searchByCodesResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByCodesResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfProduct searchByCodes(
        @WebParam(name = "cis", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.product.ArrayOfString cis
    );

    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByName", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByName")
    @ResponseWrapper(localName = "searchByNameResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByNameResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfProduct searchByName(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        java.lang.String name
    );

    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByPrecautionId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByPrecautionId")
    @ResponseWrapper(localName = "searchByPrecautionIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByPrecautionIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfProduct searchByPrecautionId(
        @WebParam(name = "precautionId", targetNamespace = "urn:Vidal")
        java.lang.Integer precautionId
    );

    @WebResult(name = "product", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByPackId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByPackId")
    @ResponseWrapper(localName = "searchByPackIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByPackIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.Product searchByPackId(
        @WebParam(name = "packId", targetNamespace = "urn:Vidal")
        java.lang.Integer packId
    );

    @WebResult(name = "routeList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getRoute", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.GetRoute")
    @ResponseWrapper(localName = "getRouteResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.GetRouteResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfRoute getRoute(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        java.lang.Integer productId
    );

    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchProductsByUcdId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchProductsByUcdId")
    @ResponseWrapper(localName = "searchProductsByUcdIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchProductsByUcdIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfProduct searchProductsByUcdId(
        @WebParam(name = "ucdId", targetNamespace = "urn:Vidal")
        java.lang.Integer ucdId
    );

    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchBySaumonIds", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchBySaumonIds")
    @ResponseWrapper(localName = "searchBySaumonIdsResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchBySaumonIdsResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfProduct searchBySaumonIds(
        @WebParam(name = "saumonIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.product.ArrayOfInt saumonIds
    );

    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchWithoutInteractionsByIndicationId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchWithoutInteractionsByIndicationId")
    @ResponseWrapper(localName = "searchWithoutInteractionsByIndicationIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchWithoutInteractionsByIndicationIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfProduct searchWithoutInteractionsByIndicationId(
        @WebParam(name = "productIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.product.ArrayOfInt productIds,
        @WebParam(name = "indicationId", targetNamespace = "urn:Vidal")
        java.lang.Integer indicationId
    );

    @WebResult(name = "productIndicatorsList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchProductIndicatorsByProductIds", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchProductIndicatorsByProductIds")
    @ResponseWrapper(localName = "searchProductIndicatorsByProductIdsResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchProductIndicatorsByProductIdsResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfProductIndicators searchProductIndicatorsByProductIds(
        @WebParam(name = "productIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.product.ArrayOfInt productIds
    );

    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchBySaumonId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchBySaumonId")
    @ResponseWrapper(localName = "searchBySaumonIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchBySaumonIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfProduct searchBySaumonId(
        @WebParam(name = "saumonId", targetNamespace = "urn:Vidal")
        java.lang.Integer saumonId
    );

    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchNewlyAvailableProducts", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchNewlyAvailableProducts")
    @ResponseWrapper(localName = "searchNewlyAvailableProductsResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchNewlyAvailableProductsResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfProduct searchNewlyAvailableProducts();

    @WebResult(name = "ProductRouteListCoupleList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchProductRoutesCouplesByProductIds", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchProductRoutesCouplesByProductIds")
    @ResponseWrapper(localName = "searchProductRoutesCouplesByProductIdsResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchProductRoutesCouplesByProductIdsResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfProductRouteListCouple searchProductRoutesCouplesByProductIds(
        @WebParam(name = "productIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.product.ArrayOfInt productIds
    );

    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByIndicationGroupId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByIndicationGroupId")
    @ResponseWrapper(localName = "searchByIndicationGroupIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByIndicationGroupIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfProduct searchByIndicationGroupId(
        @WebParam(name = "indicationGroupId", targetNamespace = "urn:Vidal")
        java.lang.Integer indicationGroupId
    );

    @WebResult(name = "pagedResultProduct", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByNameWithPagedResult", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByNameWithPagedResult")
    @ResponseWrapper(localName = "searchByNameWithPagedResultResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByNameWithPagedResultResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.PagedResultProduct searchByNameWithPagedResult(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        java.lang.String name,
        @WebParam(name = "types", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.product.ArrayOfProductType types,
        @WebParam(name = "marketStatuses", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.product.ArrayOfMarketStatus marketStatuses,
        @WebParam(name = "pageNumber", targetNamespace = "urn:Vidal")
        java.lang.Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "urn:Vidal")
        java.lang.Integer pageSize
    );

    @WebResult(name = "safetyAlertStatus", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "hasCommonNameGroupSafetyAlert", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.HasCommonNameGroupSafetyAlert")
    @ResponseWrapper(localName = "hasCommonNameGroupSafetyAlertResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.HasCommonNameGroupSafetyAlertResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.SafetyAlertStatus hasCommonNameGroupSafetyAlert(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        java.lang.Integer productId
    );

    @WebResult(name = "asmrList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getAsmr", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.GetAsmr")
    @ResponseWrapper(localName = "getAsmrResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.GetAsmrResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfAsmr getAsmr(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        java.lang.Integer productId
    );

    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByContraIndicationId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByContraIndicationId")
    @ResponseWrapper(localName = "searchByContraIndicationIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByContraIndicationIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfProduct searchByContraIndicationId(
        @WebParam(name = "contraIndicationId", targetNamespace = "urn:Vidal")
        java.lang.Integer contraIndicationId
    );

    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByEphmraId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByEphmraId")
    @ResponseWrapper(localName = "searchByEphmraIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByEphmraIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfProduct searchByEphmraId(
        @WebParam(name = "ephmraId", targetNamespace = "urn:Vidal")
        java.lang.Integer ephmraId
    );

    @WebResult(name = "product", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchById", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchById")
    @ResponseWrapper(localName = "searchByIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.Product searchById(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        java.lang.Integer productId
    );

    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByNameAndType", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByNameAndType")
    @ResponseWrapper(localName = "searchByNameAndTypeResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByNameAndTypeResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfProduct searchByNameAndType(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        java.lang.String name,
        @WebParam(name = "type", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.product.ProductType type
    );

    @WebResult(name = "smrList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getSmr", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.GetSmr")
    @ResponseWrapper(localName = "getSmrResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.GetSmrResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfSmr getSmr(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        java.lang.Integer productId
    );

    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "directSearchByName", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.DirectSearchByName")
    @ResponseWrapper(localName = "directSearchByNameResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.DirectSearchByNameResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfProduct directSearchByName(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        java.lang.String name
    );

    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByIndicationsGroupId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByIndicationsGroupId")
    @ResponseWrapper(localName = "searchByIndicationsGroupIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByIndicationsGroupIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfProduct searchByIndicationsGroupId(
        @WebParam(name = "indicationsGroupId", targetNamespace = "urn:Vidal")
        java.lang.Integer indicationsGroupId
    );

    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByGenericGroupId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByGenericGroupId")
    @ResponseWrapper(localName = "searchByGenericGroupIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByGenericGroupIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfProduct searchByGenericGroupId(
        @WebParam(name = "genericGroupId", targetNamespace = "urn:Vidal")
        java.lang.Integer genericGroupId
    );

    @WebResult(name = "ProductRangeProductCoupleList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByProductRangeIds", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByProductRangeIds")
    @ResponseWrapper(localName = "searchByProductRangeIdsResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByProductRangeIdsResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfProductRangeProductCouple searchByProductRangeIds(
        @WebParam(name = "productRangeIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.product.ArrayOfInt productRangeIds
    );

    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByVidalId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByVidalId")
    @ResponseWrapper(localName = "searchByVidalIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByVidalIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfProduct searchByVidalId(
        @WebParam(name = "vidalId", targetNamespace = "urn:Vidal")
        java.lang.Integer vidalId
    );

    @WebResult(name = "product", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByCis", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByCis")
    @ResponseWrapper(localName = "searchByCisResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByCisResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.Product searchByCis(
        @WebParam(name = "cis", targetNamespace = "urn:Vidal")
        java.lang.String cis
    );

    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchBySempIds", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchBySempIds")
    @ResponseWrapper(localName = "searchBySempIdsResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchBySempIdsResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfProduct searchBySempIds(
        @WebParam(name = "sempIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.product.ArrayOfInt sempIds
    );

    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByIndicationId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByIndicationId")
    @ResponseWrapper(localName = "searchByIndicationIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByIndicationIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfProduct searchByIndicationId(
        @WebParam(name = "indicationId", targetNamespace = "urn:Vidal")
        java.lang.Integer indicationId
    );

    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByWarningId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByWarningId")
    @ResponseWrapper(localName = "searchByWarningIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByWarningIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfProduct searchByWarningId(
        @WebParam(name = "warningId", targetNamespace = "urn:Vidal")
        java.lang.Integer warningId
    );

    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByVidalIds", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByVidalIds")
    @ResponseWrapper(localName = "searchByVidalIdsResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByVidalIdsResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfProduct searchByVidalIds(
        @WebParam(name = "vidalIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.product.ArrayOfInt vidalIds
    );

    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByNameWithTypes", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByNameWithTypes")
    @ResponseWrapper(localName = "searchByNameWithTypesResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByNameWithTypesResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfProduct searchByNameWithTypes(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        java.lang.String name,
        @WebParam(name = "types", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.product.ArrayOfProductType types
    );

    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchBySideEffectId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchBySideEffectId")
    @ResponseWrapper(localName = "searchBySideEffectIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchBySideEffectIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfProduct searchBySideEffectId(
        @WebParam(name = "sideEffectId", targetNamespace = "urn:Vidal")
        java.lang.Integer sideEffectId
    );

    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByAtcIds", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByAtcIds")
    @ResponseWrapper(localName = "searchByAtcIdsResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByAtcIdsResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfProduct searchByAtcIds(
        @WebParam(name = "atcIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.product.ArrayOfInt atcIds
    );

    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByMoleculeIds", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByMoleculeIds")
    @ResponseWrapper(localName = "searchByMoleculeIdsResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByMoleculeIdsResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfProduct searchByMoleculeIds(
        @WebParam(name = "moleculeIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.product.ArrayOfInt moleculeIds,
        @WebParam(name = "substanceTypes", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.product.ArrayOfSubstanceType substanceTypes
    );

    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByIds", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByIds")
    @ResponseWrapper(localName = "searchByIdsResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByIdsResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfProduct searchByIds(
        @WebParam(name = "productIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.product.ArrayOfInt productIds
    );

    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByAtcId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByAtcId")
    @ResponseWrapper(localName = "searchByAtcIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByAtcIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfProduct searchByAtcId(
        @WebParam(name = "atcId", targetNamespace = "urn:Vidal")
        java.lang.Integer atcId
    );

    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByCompanyId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByCompanyId")
    @ResponseWrapper(localName = "searchByCompanyIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByCompanyIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfProduct searchByCompanyId(
        @WebParam(name = "companyId", targetNamespace = "urn:Vidal")
        java.lang.Integer companyId
    );

    @WebResult(name = "pagedResultProduct", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getAllProducts", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.GetAllProducts")
    @ResponseWrapper(localName = "getAllProductsResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.GetAllProductsResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.PagedResultProduct getAllProducts(
        @WebParam(name = "productApiFilter", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.product.ProductApiFilter productApiFilter,
        @WebParam(name = "types", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.product.ArrayOfProductType types,
        @WebParam(name = "marketStatuses", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.product.ArrayOfMarketStatus marketStatuses,
        @WebParam(name = "pageNumber", targetNamespace = "urn:Vidal")
        java.lang.Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "urn:Vidal")
        java.lang.Integer pageSize
    );

    @WebResult(name = "prescriptionMode", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getPrescriptionMode", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.GetPrescriptionMode")
    @ResponseWrapper(localName = "getPrescriptionModeResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.GetPrescriptionModeResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.PrescriptionMode getPrescriptionMode(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        java.lang.Integer productId
    );

    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByFoodInteractionId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByFoodInteractionId")
    @ResponseWrapper(localName = "searchByFoodInteractionIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByFoodInteractionIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfProduct searchByFoodInteractionId(
        @WebParam(name = "foodInteractionId", targetNamespace = "urn:Vidal")
        java.lang.Integer foodInteractionId
    );

    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchBySempId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchBySempId")
    @ResponseWrapper(localName = "searchBySempIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchBySempIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfProduct searchBySempId(
        @WebParam(name = "sempId", targetNamespace = "urn:Vidal")
        java.lang.Integer sempId
    );

    @WebResult(name = "productList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByCommonNameGroupId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByCommonNameGroupId")
    @ResponseWrapper(localName = "searchByCommonNameGroupIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByCommonNameGroupIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.ArrayOfProduct searchByCommonNameGroupId(
        @WebParam(name = "commonNameGroupId", targetNamespace = "urn:Vidal")
        java.lang.Integer commonNameGroupId
    );

    @WebResult(name = "product", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByUcdId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByUcdId")
    @ResponseWrapper(localName = "searchByUcdIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.product.SearchByUcdIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.product.Product searchByUcdId(
        @WebParam(name = "ucdId", targetNamespace = "urn:Vidal")
        java.lang.Integer ucdId
    );
}
