package com.vidal.merlin.wsclient.sfmg;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:32 CET 2013
 * Generated source version: 2.2.6
 * 
 */
 
@WebService(targetNamespace = "urn:Vidal", name = "sfmgService")
@XmlSeeAlso({ObjectFactory.class})
public interface SfmgService {

    @WebResult(name = "sfmgList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByCode", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.sfmg.SearchByCode")
    @ResponseWrapper(localName = "searchByCodeResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.sfmg.SearchByCodeResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.sfmg.ArrayOfSfmg searchByCode(
        @WebParam(name = "code", targetNamespace = "urn:Vidal")
        java.lang.String code
    );

    @WebResult(name = "indicationGroupList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getIndicationGroup", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.sfmg.GetIndicationGroup")
    @ResponseWrapper(localName = "getIndicationGroupResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.sfmg.GetIndicationGroupResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.sfmg.ArrayOfIndicationGroup getIndicationGroup(
        @WebParam(name = "sfmgId", targetNamespace = "urn:Vidal")
        java.lang.Integer sfmgId
    );

    @WebResult(name = "sfmgList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByName", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.sfmg.SearchByName")
    @ResponseWrapper(localName = "searchByNameResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.sfmg.SearchByNameResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.sfmg.ArrayOfSfmg searchByName(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        java.lang.String name
    );

    @WebResult(name = "sfmgList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByIndicationGroupId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.sfmg.SearchByIndicationGroupId")
    @ResponseWrapper(localName = "searchByIndicationGroupIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.sfmg.SearchByIndicationGroupIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.sfmg.ArrayOfSfmg searchByIndicationGroupId(
        @WebParam(name = "indicationGroupId", targetNamespace = "urn:Vidal")
        java.lang.Integer indicationGroupId
    );

    @WebResult(name = "sfmg", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchById", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.sfmg.SearchById")
    @ResponseWrapper(localName = "searchByIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.sfmg.SearchByIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.sfmg.Sfmg searchById(
        @WebParam(name = "sfmgId", targetNamespace = "urn:Vidal")
        java.lang.Integer sfmgId
    );

    @WebResult(name = "contraIndicationList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getContraIndication", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.sfmg.GetContraIndication")
    @ResponseWrapper(localName = "getContraIndicationResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.sfmg.GetContraIndicationResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.sfmg.ArrayOfContraIndication getContraIndication(
        @WebParam(name = "sfmgId", targetNamespace = "urn:Vidal")
        java.lang.Integer sfmgId
    );
}
