package com.vidal.merlin.wsclient.utilities;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:33 CET 2013
 * Generated source version: 2.2.6
 * 
 */
 
@WebService(targetNamespace = "urn:Vidal", name = "utilitiesService")
@XmlSeeAlso({ObjectFactory.class})
public interface UtilitiesService {

    @WebResult(name = "compositeIdList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getCompositeIdsFromHMKContraIndication", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.utilities.GetCompositeIdsFromHMKContraIndication")
    @ResponseWrapper(localName = "getCompositeIdsFromHMKContraIndicationResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.utilities.GetCompositeIdsFromHMKContraIndicationResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.utilities.ArrayOfCompositeId getCompositeIdsFromHMKContraIndication(
        @WebParam(name = "hmkCiId", targetNamespace = "urn:Vidal")
        java.lang.String hmkCiId
    );

    @WebResult(name = "compositeIdMap", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getCompositeIdFromHMK", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.utilities.GetCompositeIdFromHMK")
    @ResponseWrapper(localName = "getCompositeIdFromHMKResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.utilities.GetCompositeIdFromHMKResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.utilities.String2CompositeIdMap getCompositeIdFromHMK(
        @WebParam(name = "hmkIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.utilities.ArrayOfString hmkIds
    );
}
