
package com.vidal.merlin.wsclient.reco;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:31 CET 2013
 * Generated source version: 2.2.6
 * 
 */

public final class RecoService_RecoServiceHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("urn:Vidal", "RecoService");

    private RecoService_RecoServiceHttpPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = RecoService_Service.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        RecoService_Service ss = new RecoService_Service(wsdlURL, SERVICE_NAME);
        RecoService port = ss.getRecoServiceHttpPort();  
        
        {
        System.out.println("Invoking searchByName...");
        java.lang.String _searchByName_name = "";
        com.vidal.merlin.wsclient.reco.ArrayOfReco _searchByName__return = port.searchByName(_searchByName_name);
        System.out.println("searchByName.result=" + _searchByName__return);


        }
        {
        System.out.println("Invoking searchDomainByName...");
        java.lang.String _searchDomainByName_name = "";
        com.vidal.merlin.wsclient.reco.ArrayOfRecoDomain _searchDomainByName__return = port.searchDomainByName(_searchDomainByName_name);
        System.out.println("searchDomainByName.result=" + _searchDomainByName__return);


        }
        {
        System.out.println("Invoking searchDomainById...");
        java.lang.Integer _searchDomainById_recoDomainId = null;
        com.vidal.merlin.wsclient.reco.RecoDomain _searchDomainById__return = port.searchDomainById(_searchDomainById_recoDomainId);
        System.out.println("searchDomainById.result=" + _searchDomainById__return);


        }
        {
        System.out.println("Invoking searchAllRecosByProductIds...");
        com.vidal.merlin.wsclient.reco.ArrayOfInt _searchAllRecosByProductIds_productIds = null;
        com.vidal.merlin.wsclient.reco.ArrayOfReco _searchAllRecosByProductIds__return = port.searchAllRecosByProductIds(_searchAllRecosByProductIds_productIds);
        System.out.println("searchAllRecosByProductIds.result=" + _searchAllRecosByProductIds__return);


        }
        {
        System.out.println("Invoking searchById...");
        java.lang.Integer _searchById_recoId = null;
        com.vidal.merlin.wsclient.reco.Reco _searchById__return = port.searchById(_searchById_recoId);
        System.out.println("searchById.result=" + _searchById__return);


        }
        {
        System.out.println("Invoking searchAllDomains...");
        com.vidal.merlin.wsclient.reco.ArrayOfRecoDomain _searchAllDomains__return = port.searchAllDomains();
        System.out.println("searchAllDomains.result=" + _searchAllDomains__return);


        }
        {
        System.out.println("Invoking searchByIndicationGroupIds...");
        com.vidal.merlin.wsclient.reco.ArrayOfInt _searchByIndicationGroupIds_indicationGroupIds = null;
        com.vidal.merlin.wsclient.reco.ArrayOfReco _searchByIndicationGroupIds__return = port.searchByIndicationGroupIds(_searchByIndicationGroupIds_indicationGroupIds);
        System.out.println("searchByIndicationGroupIds.result=" + _searchByIndicationGroupIds__return);


        }
        {
        System.out.println("Invoking getRecoUrl...");
        java.lang.Integer _getRecoUrl_recoId = null;
        java.lang.String _getRecoUrl__return = port.getRecoUrl(_getRecoUrl_recoId);
        System.out.println("getRecoUrl.result=" + _getRecoUrl__return);


        }
        {
        System.out.println("Invoking searchAllRecos...");
        com.vidal.merlin.wsclient.reco.ArrayOfReco _searchAllRecos__return = port.searchAllRecos();
        System.out.println("searchAllRecos.result=" + _searchAllRecos__return);


        }
        {
        System.out.println("Invoking searchByDomainIds...");
        com.vidal.merlin.wsclient.reco.ArrayOfInt _searchByDomainIds_recoDomainIds = null;
        com.vidal.merlin.wsclient.reco.ArrayOfReco _searchByDomainIds__return = port.searchByDomainIds(_searchByDomainIds_recoDomainIds);
        System.out.println("searchByDomainIds.result=" + _searchByDomainIds__return);


        }

        System.exit(0);
    }

}
