
package com.vidal.merlin.wsclient.document;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:25 CET 2013
 * Generated source version: 2.2.6
 * 
 */

public final class DocumentService_DocumentServiceHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("urn:Vidal", "DocumentService");

    private DocumentService_DocumentServiceHttpPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = DocumentService_Service.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        DocumentService_Service ss = new DocumentService_Service(wsdlURL, SERVICE_NAME);
        DocumentService port = ss.getDocumentServiceHttpPort();  
        
        {
        System.out.println("Invoking getBumForUcdId...");
        java.lang.Integer _getBumForUcdId_ucdId = null;
        com.vidal.merlin.wsclient.document.ArrayOfDocument _getBumForUcdId__return = port.getBumForUcdId(_getBumForUcdId_ucdId);
        System.out.println("getBumForUcdId.result=" + _getBumForUcdId__return);


        }
        {
        System.out.println("Invoking getVdfForPackageId...");
        java.lang.Integer _getVdfForPackageId_packId = null;
        com.vidal.merlin.wsclient.document.Document _getVdfForPackageId__return = port.getVdfForPackageId(_getVdfForPackageId_packId);
        System.out.println("getVdfForPackageId.result=" + _getVdfForPackageId__return);


        }
        {
        System.out.println("Invoking getDocumentsByDocumentTypesForProductId...");
        com.vidal.merlin.wsclient.document.ArrayOfDocumentType _getDocumentsByDocumentTypesForProductId_documentTypeList = null;
        java.lang.Integer _getDocumentsByDocumentTypesForProductId_productId = null;
        com.vidal.merlin.wsclient.document.ArrayOfDocument _getDocumentsByDocumentTypesForProductId__return = port.getDocumentsByDocumentTypesForProductId(_getDocumentsByDocumentTypesForProductId_documentTypeList, _getDocumentsByDocumentTypesForProductId_productId);
        System.out.println("getDocumentsByDocumentTypesForProductId.result=" + _getDocumentsByDocumentTypesForProductId__return);


        }
        {
        System.out.println("Invoking getPgrForProductId...");
        java.lang.Integer _getPgrForProductId_productId = null;
        com.vidal.merlin.wsclient.document.ArrayOfDocument _getPgrForProductId__return = port.getPgrForProductId(_getPgrForProductId_productId);
        System.out.println("getPgrForProductId.result=" + _getPgrForProductId__return);


        }
        {
        System.out.println("Invoking getPgrForPackId...");
        java.lang.Integer _getPgrForPackId_packId = null;
        com.vidal.merlin.wsclient.document.ArrayOfDocument _getPgrForPackId__return = port.getPgrForPackId(_getPgrForPackId_packId);
        System.out.println("getPgrForPackId.result=" + _getPgrForPackId__return);


        }
        {
        System.out.println("Invoking getVdfForProductId...");
        java.lang.Integer _getVdfForProductId_productId = null;
        com.vidal.merlin.wsclient.document.Document _getVdfForProductId__return = port.getVdfForProductId(_getVdfForProductId_productId);
        System.out.println("getVdfForProductId.result=" + _getVdfForProductId__return);


        }
        {
        System.out.println("Invoking getVdfForPackId...");
        java.lang.Integer _getVdfForPackId_packId = null;
        com.vidal.merlin.wsclient.document.Document _getVdfForPackId__return = port.getVdfForPackId(_getVdfForPackId_packId);
        System.out.println("getVdfForPackId.result=" + _getVdfForPackId__return);


        }
        {
        System.out.println("Invoking getMonoForProductId...");
        java.lang.Integer _getMonoForProductId_productId = null;
        com.vidal.merlin.wsclient.document.Document _getMonoForProductId__return = port.getMonoForProductId(_getMonoForProductId_productId);
        System.out.println("getMonoForProductId.result=" + _getMonoForProductId__return);


        }
        {
        System.out.println("Invoking getVidalRcpForUcdId...");
        java.lang.Integer _getVidalRcpForUcdId_ucdId = null;
        com.vidal.merlin.wsclient.document.ArrayOfDocument _getVidalRcpForUcdId__return = port.getVidalRcpForUcdId(_getVidalRcpForUcdId_ucdId);
        System.out.println("getVidalRcpForUcdId.result=" + _getVidalRcpForUcdId__return);


        }
        {
        System.out.println("Invoking getFitForUcdId...");
        java.lang.Integer _getFitForUcdId_ucdId = null;
        com.vidal.merlin.wsclient.document.ArrayOfDocument _getFitForUcdId__return = port.getFitForUcdId(_getFitForUcdId_ucdId);
        System.out.println("getFitForUcdId.result=" + _getFitForUcdId__return);


        }
        {
        System.out.println("Invoking getAllDocumentForProductId...");
        java.lang.Integer _getAllDocumentForProductId_productId = null;
        com.vidal.merlin.wsclient.document.ArrayOfDocument _getAllDocumentForProductId__return = port.getAllDocumentForProductId(_getAllDocumentForProductId_productId);
        System.out.println("getAllDocumentForProductId.result=" + _getAllDocumentForProductId__return);


        }
        {
        System.out.println("Invoking getBumForPackId...");
        java.lang.Integer _getBumForPackId_packId = null;
        com.vidal.merlin.wsclient.document.ArrayOfDocument _getBumForPackId__return = port.getBumForPackId(_getBumForPackId_packId);
        System.out.println("getBumForPackId.result=" + _getBumForPackId__return);


        }
        {
        System.out.println("Invoking getAllDocumentForUcdId...");
        java.lang.Integer _getAllDocumentForUcdId_ucdId = null;
        com.vidal.merlin.wsclient.document.ArrayOfDocument _getAllDocumentForUcdId__return = port.getAllDocumentForUcdId(_getAllDocumentForUcdId_ucdId);
        System.out.println("getAllDocumentForUcdId.result=" + _getAllDocumentForUcdId__return);


        }
        {
        System.out.println("Invoking getDocumentsByDocumentTypesForPackId...");
        com.vidal.merlin.wsclient.document.ArrayOfDocumentType _getDocumentsByDocumentTypesForPackId_documentTypeList = null;
        java.lang.Integer _getDocumentsByDocumentTypesForPackId_packId = null;
        com.vidal.merlin.wsclient.document.ArrayOfDocument _getDocumentsByDocumentTypesForPackId__return = port.getDocumentsByDocumentTypesForPackId(_getDocumentsByDocumentTypesForPackId_documentTypeList, _getDocumentsByDocumentTypesForPackId_packId);
        System.out.println("getDocumentsByDocumentTypesForPackId.result=" + _getDocumentsByDocumentTypesForPackId__return);


        }
        {
        System.out.println("Invoking getAllDocumentForPackId...");
        java.lang.Integer _getAllDocumentForPackId_packId = null;
        com.vidal.merlin.wsclient.document.ArrayOfDocument _getAllDocumentForPackId__return = port.getAllDocumentForPackId(_getAllDocumentForPackId_packId);
        System.out.println("getAllDocumentForPackId.result=" + _getAllDocumentForPackId__return);


        }
        {
        System.out.println("Invoking getPttForProductId...");
        java.lang.Integer _getPttForProductId_productId = null;
        com.vidal.merlin.wsclient.document.ArrayOfDocument _getPttForProductId__return = port.getPttForProductId(_getPttForProductId_productId);
        System.out.println("getPttForProductId.result=" + _getPttForProductId__return);


        }
        {
        System.out.println("Invoking getPgrForUcdId...");
        java.lang.Integer _getPgrForUcdId_ucdId = null;
        com.vidal.merlin.wsclient.document.ArrayOfDocument _getPgrForUcdId__return = port.getPgrForUcdId(_getPgrForUcdId_ucdId);
        System.out.println("getPgrForUcdId.result=" + _getPgrForUcdId__return);


        }
        {
        System.out.println("Invoking searchById...");
        java.lang.Integer _searchById_documentId = null;
        com.vidal.merlin.wsclient.document.Document _searchById__return = port.searchById(_searchById_documentId);
        System.out.println("searchById.result=" + _searchById__return);


        }
        {
        System.out.println("Invoking getVdfForUcdId...");
        java.lang.Integer _getVdfForUcdId_ucdId = null;
        com.vidal.merlin.wsclient.document.Document _getVdfForUcdId__return = port.getVdfForUcdId(_getVdfForUcdId_ucdId);
        System.out.println("getVdfForUcdId.result=" + _getVdfForUcdId__return);


        }
        {
        System.out.println("Invoking getVidalRcpForPackId...");
        java.lang.Integer _getVidalRcpForPackId_packId = null;
        com.vidal.merlin.wsclient.document.ArrayOfDocument _getVidalRcpForPackId__return = port.getVidalRcpForPackId(_getVidalRcpForPackId_packId);
        System.out.println("getVidalRcpForPackId.result=" + _getVidalRcpForPackId__return);


        }
        {
        System.out.println("Invoking getPttForPackId...");
        java.lang.Integer _getPttForPackId_packId = null;
        com.vidal.merlin.wsclient.document.ArrayOfDocument _getPttForPackId__return = port.getPttForPackId(_getPttForPackId_packId);
        System.out.println("getPttForPackId.result=" + _getPttForPackId__return);


        }
        {
        System.out.println("Invoking getDocumentsByDocumentTypesForUcdId...");
        com.vidal.merlin.wsclient.document.ArrayOfDocumentType _getDocumentsByDocumentTypesForUcdId_documentTypeList = null;
        java.lang.Integer _getDocumentsByDocumentTypesForUcdId_ucdId = null;
        com.vidal.merlin.wsclient.document.ArrayOfDocument _getDocumentsByDocumentTypesForUcdId__return = port.getDocumentsByDocumentTypesForUcdId(_getDocumentsByDocumentTypesForUcdId_documentTypeList, _getDocumentsByDocumentTypesForUcdId_ucdId);
        System.out.println("getDocumentsByDocumentTypesForUcdId.result=" + _getDocumentsByDocumentTypesForUcdId__return);


        }
        {
        System.out.println("Invoking getFitForPackId...");
        java.lang.Integer _getFitForPackId_packId = null;
        com.vidal.merlin.wsclient.document.ArrayOfDocument _getFitForPackId__return = port.getFitForPackId(_getFitForPackId_packId);
        System.out.println("getFitForPackId.result=" + _getFitForPackId__return);


        }
        {
        System.out.println("Invoking getMonoForUcdId...");
        java.lang.Integer _getMonoForUcdId_ucdId = null;
        com.vidal.merlin.wsclient.document.Document _getMonoForUcdId__return = port.getMonoForUcdId(_getMonoForUcdId_ucdId);
        System.out.println("getMonoForUcdId.result=" + _getMonoForUcdId__return);


        }
        {
        System.out.println("Invoking getMonoForPackId...");
        java.lang.Integer _getMonoForPackId_packId = null;
        com.vidal.merlin.wsclient.document.Document _getMonoForPackId__return = port.getMonoForPackId(_getMonoForPackId_packId);
        System.out.println("getMonoForPackId.result=" + _getMonoForPackId__return);


        }
        {
        System.out.println("Invoking getPttForUcdId...");
        java.lang.Integer _getPttForUcdId_ucdId = null;
        com.vidal.merlin.wsclient.document.ArrayOfDocument _getPttForUcdId__return = port.getPttForUcdId(_getPttForUcdId_ucdId);
        System.out.println("getPttForUcdId.result=" + _getPttForUcdId__return);


        }
        {
        System.out.println("Invoking getVidalRcpForProductId...");
        java.lang.Integer _getVidalRcpForProductId_productId = null;
        com.vidal.merlin.wsclient.document.ArrayOfDocument _getVidalRcpForProductId__return = port.getVidalRcpForProductId(_getVidalRcpForProductId_productId);
        System.out.println("getVidalRcpForProductId.result=" + _getVidalRcpForProductId__return);


        }
        {
        System.out.println("Invoking getMonoForPackageId...");
        java.lang.Integer _getMonoForPackageId_packId = null;
        com.vidal.merlin.wsclient.document.Document _getMonoForPackageId__return = port.getMonoForPackageId(_getMonoForPackageId_packId);
        System.out.println("getMonoForPackageId.result=" + _getMonoForPackageId__return);


        }
        {
        System.out.println("Invoking getBumForProductId...");
        java.lang.Integer _getBumForProductId_productId = null;
        com.vidal.merlin.wsclient.document.ArrayOfDocument _getBumForProductId__return = port.getBumForProductId(_getBumForProductId_productId);
        System.out.println("getBumForProductId.result=" + _getBumForProductId__return);


        }
        {
        System.out.println("Invoking getFitForProductId...");
        java.lang.Integer _getFitForProductId_productId = null;
        com.vidal.merlin.wsclient.document.ArrayOfDocument _getFitForProductId__return = port.getFitForProductId(_getFitForProductId_productId);
        System.out.println("getFitForProductId.result=" + _getFitForProductId__return);


        }
        {
        System.out.println("Invoking searchByCommonNameGroupId...");
        java.lang.Integer _searchByCommonNameGroupId_commonNameGroupId = null;
        com.vidal.merlin.wsclient.document.ArrayOfDocument _searchByCommonNameGroupId__return = port.searchByCommonNameGroupId(_searchByCommonNameGroupId_commonNameGroupId);
        System.out.println("searchByCommonNameGroupId.result=" + _searchByCommonNameGroupId__return);


        }

        System.exit(0);
    }

}
