package com.vidal.merlin.wsclient.document;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:25 CET 2013
 * Generated source version: 2.2.6
 * 
 */
 
@WebService(targetNamespace = "urn:Vidal", name = "documentService")
@XmlSeeAlso({ObjectFactory.class})
public interface DocumentService {

    @WebResult(name = "documentList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getBumForUcdId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetBumForUcdId")
    @ResponseWrapper(localName = "getBumForUcdIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetBumForUcdIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.document.ArrayOfDocument getBumForUcdId(
        @WebParam(name = "ucdId", targetNamespace = "urn:Vidal")
        java.lang.Integer ucdId
    );

    @WebResult(name = "document", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getVdfForPackageId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetVdfForPackageId")
    @ResponseWrapper(localName = "getVdfForPackageIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetVdfForPackageIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.document.Document getVdfForPackageId(
        @WebParam(name = "packId", targetNamespace = "urn:Vidal")
        java.lang.Integer packId
    );

    @WebResult(name = "documentList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getDocumentsByDocumentTypesForProductId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetDocumentsByDocumentTypesForProductId")
    @ResponseWrapper(localName = "getDocumentsByDocumentTypesForProductIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetDocumentsByDocumentTypesForProductIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.document.ArrayOfDocument getDocumentsByDocumentTypesForProductId(
        @WebParam(name = "documentTypeList", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.document.ArrayOfDocumentType documentTypeList,
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        java.lang.Integer productId
    );

    @WebResult(name = "documentList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getPgrForProductId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetPgrForProductId")
    @ResponseWrapper(localName = "getPgrForProductIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetPgrForProductIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.document.ArrayOfDocument getPgrForProductId(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        java.lang.Integer productId
    );

    @WebResult(name = "documentList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getPgrForPackId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetPgrForPackId")
    @ResponseWrapper(localName = "getPgrForPackIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetPgrForPackIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.document.ArrayOfDocument getPgrForPackId(
        @WebParam(name = "packId", targetNamespace = "urn:Vidal")
        java.lang.Integer packId
    );

    @WebResult(name = "document", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getVdfForProductId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetVdfForProductId")
    @ResponseWrapper(localName = "getVdfForProductIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetVdfForProductIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.document.Document getVdfForProductId(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        java.lang.Integer productId
    );

    @WebResult(name = "document", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getVdfForPackId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetVdfForPackId")
    @ResponseWrapper(localName = "getVdfForPackIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetVdfForPackIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.document.Document getVdfForPackId(
        @WebParam(name = "packId", targetNamespace = "urn:Vidal")
        java.lang.Integer packId
    );

    @WebResult(name = "document", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getMonoForProductId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetMonoForProductId")
    @ResponseWrapper(localName = "getMonoForProductIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetMonoForProductIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.document.Document getMonoForProductId(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        java.lang.Integer productId
    );

    @WebResult(name = "documentList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getVidalRcpForUcdId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetVidalRcpForUcdId")
    @ResponseWrapper(localName = "getVidalRcpForUcdIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetVidalRcpForUcdIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.document.ArrayOfDocument getVidalRcpForUcdId(
        @WebParam(name = "ucdId", targetNamespace = "urn:Vidal")
        java.lang.Integer ucdId
    );

    @WebResult(name = "documentList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getFitForUcdId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetFitForUcdId")
    @ResponseWrapper(localName = "getFitForUcdIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetFitForUcdIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.document.ArrayOfDocument getFitForUcdId(
        @WebParam(name = "ucdId", targetNamespace = "urn:Vidal")
        java.lang.Integer ucdId
    );

    @WebResult(name = "documentList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getAllDocumentForProductId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetAllDocumentForProductId")
    @ResponseWrapper(localName = "getAllDocumentForProductIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetAllDocumentForProductIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.document.ArrayOfDocument getAllDocumentForProductId(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        java.lang.Integer productId
    );

    @WebResult(name = "documentList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getBumForPackId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetBumForPackId")
    @ResponseWrapper(localName = "getBumForPackIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetBumForPackIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.document.ArrayOfDocument getBumForPackId(
        @WebParam(name = "packId", targetNamespace = "urn:Vidal")
        java.lang.Integer packId
    );

    @WebResult(name = "documentList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getAllDocumentForUcdId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetAllDocumentForUcdId")
    @ResponseWrapper(localName = "getAllDocumentForUcdIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetAllDocumentForUcdIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.document.ArrayOfDocument getAllDocumentForUcdId(
        @WebParam(name = "ucdId", targetNamespace = "urn:Vidal")
        java.lang.Integer ucdId
    );

    @WebResult(name = "documentList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getDocumentsByDocumentTypesForPackId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetDocumentsByDocumentTypesForPackId")
    @ResponseWrapper(localName = "getDocumentsByDocumentTypesForPackIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetDocumentsByDocumentTypesForPackIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.document.ArrayOfDocument getDocumentsByDocumentTypesForPackId(
        @WebParam(name = "documentTypeList", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.document.ArrayOfDocumentType documentTypeList,
        @WebParam(name = "packId", targetNamespace = "urn:Vidal")
        java.lang.Integer packId
    );

    @WebResult(name = "documentList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getAllDocumentForPackId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetAllDocumentForPackId")
    @ResponseWrapper(localName = "getAllDocumentForPackIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetAllDocumentForPackIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.document.ArrayOfDocument getAllDocumentForPackId(
        @WebParam(name = "packId", targetNamespace = "urn:Vidal")
        java.lang.Integer packId
    );

    @WebResult(name = "documentList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getPttForProductId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetPttForProductId")
    @ResponseWrapper(localName = "getPttForProductIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetPttForProductIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.document.ArrayOfDocument getPttForProductId(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        java.lang.Integer productId
    );

    @WebResult(name = "documentList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getPgrForUcdId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetPgrForUcdId")
    @ResponseWrapper(localName = "getPgrForUcdIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetPgrForUcdIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.document.ArrayOfDocument getPgrForUcdId(
        @WebParam(name = "ucdId", targetNamespace = "urn:Vidal")
        java.lang.Integer ucdId
    );

    @WebResult(name = "document", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchById", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.SearchById")
    @ResponseWrapper(localName = "searchByIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.SearchByIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.document.Document searchById(
        @WebParam(name = "documentId", targetNamespace = "urn:Vidal")
        java.lang.Integer documentId
    );

    @WebResult(name = "document", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getVdfForUcdId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetVdfForUcdId")
    @ResponseWrapper(localName = "getVdfForUcdIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetVdfForUcdIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.document.Document getVdfForUcdId(
        @WebParam(name = "ucdId", targetNamespace = "urn:Vidal")
        java.lang.Integer ucdId
    );

    @WebResult(name = "documentList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getVidalRcpForPackId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetVidalRcpForPackId")
    @ResponseWrapper(localName = "getVidalRcpForPackIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetVidalRcpForPackIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.document.ArrayOfDocument getVidalRcpForPackId(
        @WebParam(name = "packId", targetNamespace = "urn:Vidal")
        java.lang.Integer packId
    );

    @WebResult(name = "documentList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getPttForPackId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetPttForPackId")
    @ResponseWrapper(localName = "getPttForPackIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetPttForPackIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.document.ArrayOfDocument getPttForPackId(
        @WebParam(name = "packId", targetNamespace = "urn:Vidal")
        java.lang.Integer packId
    );

    @WebResult(name = "documentList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getDocumentsByDocumentTypesForUcdId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetDocumentsByDocumentTypesForUcdId")
    @ResponseWrapper(localName = "getDocumentsByDocumentTypesForUcdIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetDocumentsByDocumentTypesForUcdIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.document.ArrayOfDocument getDocumentsByDocumentTypesForUcdId(
        @WebParam(name = "documentTypeList", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.document.ArrayOfDocumentType documentTypeList,
        @WebParam(name = "UcdId", targetNamespace = "urn:Vidal")
        java.lang.Integer ucdId
    );

    @WebResult(name = "documentList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getFitForPackId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetFitForPackId")
    @ResponseWrapper(localName = "getFitForPackIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetFitForPackIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.document.ArrayOfDocument getFitForPackId(
        @WebParam(name = "packId", targetNamespace = "urn:Vidal")
        java.lang.Integer packId
    );

    @WebResult(name = "document", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getMonoForUcdId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetMonoForUcdId")
    @ResponseWrapper(localName = "getMonoForUcdIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetMonoForUcdIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.document.Document getMonoForUcdId(
        @WebParam(name = "ucdId", targetNamespace = "urn:Vidal")
        java.lang.Integer ucdId
    );

    @WebResult(name = "document", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getMonoForPackId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetMonoForPackId")
    @ResponseWrapper(localName = "getMonoForPackIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetMonoForPackIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.document.Document getMonoForPackId(
        @WebParam(name = "packId", targetNamespace = "urn:Vidal")
        java.lang.Integer packId
    );

    @WebResult(name = "documentList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getPttForUcdId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetPttForUcdId")
    @ResponseWrapper(localName = "getPttForUcdIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetPttForUcdIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.document.ArrayOfDocument getPttForUcdId(
        @WebParam(name = "ucdId", targetNamespace = "urn:Vidal")
        java.lang.Integer ucdId
    );

    @WebResult(name = "documentList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getVidalRcpForProductId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetVidalRcpForProductId")
    @ResponseWrapper(localName = "getVidalRcpForProductIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetVidalRcpForProductIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.document.ArrayOfDocument getVidalRcpForProductId(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        java.lang.Integer productId
    );

    @WebResult(name = "document", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getMonoForPackageId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetMonoForPackageId")
    @ResponseWrapper(localName = "getMonoForPackageIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetMonoForPackageIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.document.Document getMonoForPackageId(
        @WebParam(name = "packId", targetNamespace = "urn:Vidal")
        java.lang.Integer packId
    );

    @WebResult(name = "documentList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getBumForProductId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetBumForProductId")
    @ResponseWrapper(localName = "getBumForProductIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetBumForProductIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.document.ArrayOfDocument getBumForProductId(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        java.lang.Integer productId
    );

    @WebResult(name = "documentList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getFitForProductId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetFitForProductId")
    @ResponseWrapper(localName = "getFitForProductIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.GetFitForProductIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.document.ArrayOfDocument getFitForProductId(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        java.lang.Integer productId
    );

    @WebResult(name = "documentList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByCommonNameGroupId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.SearchByCommonNameGroupId")
    @ResponseWrapper(localName = "searchByCommonNameGroupIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.document.SearchByCommonNameGroupIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.document.ArrayOfDocument searchByCommonNameGroupId(
        @WebParam(name = "commonNameGroupId", targetNamespace = "urn:Vidal")
        java.lang.Integer commonNameGroupId
    );
}
