
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.vidal.merlin.wsclient.composition;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:24 CET 2013
 * Generated source version: 2.2.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "CompositionService",
                      portName = "CompositionServiceHttpPort",
                      targetNamespace = "urn:Vidal",
                      wsdlLocation = "http://localhost:8011/merlin-service/services/CompositionService?wsdl",
                      endpointInterface = "com.vidal.merlin.wsclient.composition.CompositionService")
                      
public class CompositionServiceImpl implements CompositionService {

    private static final Logger LOG = Logger.getLogger(CompositionServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.composition.CompositionService#searchCompositionsByProduct(java.lang.Integer  productId ,)com.vidal.merlin.wsclient.composition.ArrayOfSubstanceType  substanceTypes )*
     */
    public com.vidal.merlin.wsclient.composition.ArrayOfItemCompositionsCouple searchCompositionsByProduct(java.lang.Integer productId,com.vidal.merlin.wsclient.composition.ArrayOfSubstanceType substanceTypes) { 
        LOG.info("Executing operation searchCompositionsByProduct");
        System.out.println(productId);
        System.out.println(substanceTypes);
        try {
            com.vidal.merlin.wsclient.composition.ArrayOfItemCompositionsCouple _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.composition.CompositionService#searchByCommonNameGroupIds(com.vidal.merlin.wsclient.composition.ArrayOfInt  commonNameGroupIds )*
     */
    public com.vidal.merlin.wsclient.composition.ArrayOfCommonNameGroupComposition searchByCommonNameGroupIds(com.vidal.merlin.wsclient.composition.ArrayOfInt commonNameGroupIds) { 
        LOG.info("Executing operation searchByCommonNameGroupIds");
        System.out.println(commonNameGroupIds);
        try {
            com.vidal.merlin.wsclient.composition.ArrayOfCommonNameGroupComposition _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.composition.CompositionService#searchCompositionsByProductIdAndSubstanceType(java.lang.Integer  productId ,)com.vidal.merlin.wsclient.composition.SubstanceType  substanceType )*
     */
    public com.vidal.merlin.wsclient.composition.ArrayOfItemCompositionsCouple searchCompositionsByProductIdAndSubstanceType(java.lang.Integer productId,com.vidal.merlin.wsclient.composition.SubstanceType substanceType) { 
        LOG.info("Executing operation searchCompositionsByProductIdAndSubstanceType");
        System.out.println(productId);
        System.out.println(substanceType);
        try {
            com.vidal.merlin.wsclient.composition.ArrayOfItemCompositionsCouple _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.composition.CompositionService#searchCompositionsByUcdIdAndSubstanceTypes(java.lang.Integer  ucdId ,)com.vidal.merlin.wsclient.composition.ArrayOfSubstanceType  substanceTypes )*
     */
    public com.vidal.merlin.wsclient.composition.ArrayOfItemCompositionsCouple searchCompositionsByUcdIdAndSubstanceTypes(java.lang.Integer ucdId,com.vidal.merlin.wsclient.composition.ArrayOfSubstanceType substanceTypes) { 
        LOG.info("Executing operation searchCompositionsByUcdIdAndSubstanceTypes");
        System.out.println(ucdId);
        System.out.println(substanceTypes);
        try {
            com.vidal.merlin.wsclient.composition.ArrayOfItemCompositionsCouple _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
