
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.vidal.merlin.wsclient.databaseinfo;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:25 CET 2013
 * Generated source version: 2.2.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "DatabaseInfoService",
                      portName = "DatabaseInfoServiceHttpPort",
                      targetNamespace = "urn:Vidal",
                      wsdlLocation = "http://localhost:8011/merlin-service/services/DatabaseInfoService?wsdl",
                      endpointInterface = "com.vidal.merlin.wsclient.databaseinfo.DatabaseInfoService")
                      
public class DatabaseInfoServiceImpl implements DatabaseInfoService {

    private static final Logger LOG = Logger.getLogger(DatabaseInfoServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.databaseinfo.DatabaseInfoService#getExtractionDate(*
     */
    public javax.xml.datatype.XMLGregorianCalendar getExtractionDate() { 
        LOG.info("Executing operation getExtractionDate");
        try {
            javax.xml.datatype.XMLGregorianCalendar _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.databaseinfo.DatabaseInfoService#getVersion(*
     */
    public java.lang.String getVersion() { 
        LOG.info("Executing operation getVersion");
        try {
            java.lang.String _return = "";
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.databaseinfo.DatabaseInfoService#getStillOkDate(*
     */
    public javax.xml.datatype.XMLGregorianCalendar getStillOkDate() { 
        LOG.info("Executing operation getStillOkDate");
        try {
            javax.xml.datatype.XMLGregorianCalendar _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.databaseinfo.DatabaseInfoService#getDataExpiryDate(*
     */
    public javax.xml.datatype.XMLGregorianCalendar getDataExpiryDate() { 
        LOG.info("Executing operation getDataExpiryDate");
        try {
            javax.xml.datatype.XMLGregorianCalendar _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.databaseinfo.DatabaseInfoService#getWarningDate(*
     */
    public javax.xml.datatype.XMLGregorianCalendar getWarningDate() { 
        LOG.info("Executing operation getWarningDate");
        try {
            javax.xml.datatype.XMLGregorianCalendar _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.databaseinfo.DatabaseInfoService#getExpiryDate(*
     */
    public javax.xml.datatype.XMLGregorianCalendar getExpiryDate() { 
        LOG.info("Executing operation getExpiryDate");
        try {
            javax.xml.datatype.XMLGregorianCalendar _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.databaseinfo.DatabaseInfoService#getProductLine(*
     */
    public com.vidal.merlin.wsclient.databaseinfo.ProductLineType getProductLine() { 
        LOG.info("Executing operation getProductLine");
        try {
            com.vidal.merlin.wsclient.databaseinfo.ProductLineType _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
