
package com.vidal.merlin.wsclient.databaseinfo;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:25 CET 2013
 * Generated source version: 2.2.6
 * 
 */

public final class DatabaseInfoService_DatabaseInfoServiceHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("urn:Vidal", "DatabaseInfoService");

    private DatabaseInfoService_DatabaseInfoServiceHttpPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = DatabaseInfoService_Service.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        DatabaseInfoService_Service ss = new DatabaseInfoService_Service(wsdlURL, SERVICE_NAME);
        DatabaseInfoService port = ss.getDatabaseInfoServiceHttpPort();  
        
        {
        System.out.println("Invoking getExtractionDate...");
        javax.xml.datatype.XMLGregorianCalendar _getExtractionDate__return = port.getExtractionDate();
        System.out.println("getExtractionDate.result=" + _getExtractionDate__return);


        }
        {
        System.out.println("Invoking getVersion...");
        java.lang.String _getVersion__return = port.getVersion();
        System.out.println("getVersion.result=" + _getVersion__return);


        }
        {
        System.out.println("Invoking getStillOkDate...");
        javax.xml.datatype.XMLGregorianCalendar _getStillOkDate__return = port.getStillOkDate();
        System.out.println("getStillOkDate.result=" + _getStillOkDate__return);


        }
        {
        System.out.println("Invoking getDataExpiryDate...");
        javax.xml.datatype.XMLGregorianCalendar _getDataExpiryDate__return = port.getDataExpiryDate();
        System.out.println("getDataExpiryDate.result=" + _getDataExpiryDate__return);


        }
        {
        System.out.println("Invoking getWarningDate...");
        javax.xml.datatype.XMLGregorianCalendar _getWarningDate__return = port.getWarningDate();
        System.out.println("getWarningDate.result=" + _getWarningDate__return);


        }
        {
        System.out.println("Invoking getExpiryDate...");
        javax.xml.datatype.XMLGregorianCalendar _getExpiryDate__return = port.getExpiryDate();
        System.out.println("getExpiryDate.result=" + _getExpiryDate__return);


        }
        {
        System.out.println("Invoking getProductLine...");
        com.vidal.merlin.wsclient.databaseinfo.ProductLineType _getProductLine__return = port.getProductLine();
        System.out.println("getProductLine.result=" + _getProductLine__return);


        }

        System.exit(0);
    }

}
