
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.vidal.merlin.wsclient.vidal;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:33 CET 2013
 * Generated source version: 2.2.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "VidalService",
                      portName = "VidalServiceHttpPort",
                      targetNamespace = "urn:Vidal",
                      wsdlLocation = "http://localhost:8011/merlin-service/services/VidalService?wsdl",
                      endpointInterface = "com.vidal.merlin.wsclient.vidal.VidalService")
                      
public class VidalServiceImpl implements VidalService {

    private static final Logger LOG = Logger.getLogger(VidalServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.vidal.VidalService#searchByProductId(java.lang.Integer  productId )*
     */
    public com.vidal.merlin.wsclient.vidal.ArrayOfVidal searchByProductId(java.lang.Integer productId) { 
        LOG.info("Executing operation searchByProductId");
        System.out.println(productId);
        try {
            com.vidal.merlin.wsclient.vidal.ArrayOfVidal _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.vidal.VidalService#searchByName(java.lang.String  name )*
     */
    public com.vidal.merlin.wsclient.vidal.ArrayOfVidal searchByName(java.lang.String name) { 
        LOG.info("Executing operation searchByName");
        System.out.println(name);
        try {
            com.vidal.merlin.wsclient.vidal.ArrayOfVidal _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.vidal.VidalService#getChildren(java.lang.Integer  vidalId )*
     */
    public com.vidal.merlin.wsclient.vidal.ArrayOfVidal getChildren(java.lang.Integer vidalId) { 
        LOG.info("Executing operation getChildren");
        System.out.println(vidalId);
        try {
            com.vidal.merlin.wsclient.vidal.ArrayOfVidal _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.vidal.VidalService#getRootNode(*
     */
    public com.vidal.merlin.wsclient.vidal.Vidal getRootNode() { 
        LOG.info("Executing operation getRootNode");
        try {
            com.vidal.merlin.wsclient.vidal.Vidal _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.vidal.VidalService#searchById(java.lang.Integer  vidalId )*
     */
    public com.vidal.merlin.wsclient.vidal.Vidal searchById(java.lang.Integer vidalId) { 
        LOG.info("Executing operation searchById");
        System.out.println(vidalId);
        try {
            com.vidal.merlin.wsclient.vidal.Vidal _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.vidal.VidalService#getParent(java.lang.Integer  vidalId )*
     */
    public com.vidal.merlin.wsclient.vidal.Vidal getParent(java.lang.Integer vidalId) { 
        LOG.info("Executing operation getParent");
        System.out.println(vidalId);
        try {
            com.vidal.merlin.wsclient.vidal.Vidal _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
