
package com.vidal.merlin.wsclient.posology;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:29 CET 2013
 * Generated source version: 2.2.6
 * 
 */

public final class PosologyService_PosologyServiceHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("urn:Vidal", "PosologyService");

    private PosologyService_PosologyServiceHttpPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = PosologyService_Service.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        PosologyService_Service ss = new PosologyService_Service(wsdlURL, SERVICE_NAME);
        PosologyService port = ss.getPosologyServiceHttpPort();  
        
        {
        System.out.println("Invoking searchPosologyUnitByProductId...");
        java.lang.Integer _searchPosologyUnitByProductId_productId = null;
        com.vidal.merlin.wsclient.posology.ArrayOfPosologyUnit _searchPosologyUnitByProductId__return = port.searchPosologyUnitByProductId(_searchPosologyUnitByProductId_productId);
        System.out.println("searchPosologyUnitByProductId.result=" + _searchPosologyUnitByProductId__return);


        }
        {
        System.out.println("Invoking getAllUnits...");
        java.lang.Integer _getAllUnits_pageNumber = null;
        java.lang.Integer _getAllUnits_pageSize = null;
        com.vidal.merlin.wsclient.posology.PagedResultUnit _getAllUnits__return = port.getAllUnits(_getAllUnits_pageNumber, _getAllUnits_pageSize);
        System.out.println("getAllUnits.result=" + _getAllUnits__return);


        }
        {
        System.out.println("Invoking checkDailyActivePrincipleDoseByProductId...");
        java.lang.Integer _checkDailyActivePrincipleDoseByProductId_productId = null;
        java.lang.Double _checkDailyActivePrincipleDoseByProductId_dose = null;
        com.vidal.merlin.wsclient.posology.DoseUnit _checkDailyActivePrincipleDoseByProductId_doseUnit = null;
        com.vidal.merlin.wsclient.posology.PosologyFrequencyType _checkDailyActivePrincipleDoseByProductId_frequencyType = null;
        com.vidal.merlin.wsclient.posology.Gender _checkDailyActivePrincipleDoseByProductId_gender = null;
        float _checkDailyActivePrincipleDoseByProductId_age = 0.0f;
        float _checkDailyActivePrincipleDoseByProductId_weight = 0.0f;
        java.lang.Integer _checkDailyActivePrincipleDoseByProductId_height = null;
        java.lang.Integer _checkDailyActivePrincipleDoseByProductId_creatinClearance = null;
        com.vidal.merlin.wsclient.posology.HepaticInsufficiency _checkDailyActivePrincipleDoseByProductId_hepaticInsufficiency = null;
        com.vidal.merlin.wsclient.posology.ArrayOfInt _checkDailyActivePrincipleDoseByProductId_indicationIds = null;
        com.vidal.merlin.wsclient.posology.ArrayOfInt _checkDailyActivePrincipleDoseByProductId_routeIds = null;
        com.vidal.merlin.wsclient.posology.PosologyAlerts _checkDailyActivePrincipleDoseByProductId__return = port.checkDailyActivePrincipleDoseByProductId(_checkDailyActivePrincipleDoseByProductId_productId, _checkDailyActivePrincipleDoseByProductId_dose, _checkDailyActivePrincipleDoseByProductId_doseUnit, _checkDailyActivePrincipleDoseByProductId_frequencyType, _checkDailyActivePrincipleDoseByProductId_gender, _checkDailyActivePrincipleDoseByProductId_age, _checkDailyActivePrincipleDoseByProductId_weight, _checkDailyActivePrincipleDoseByProductId_height, _checkDailyActivePrincipleDoseByProductId_creatinClearance, _checkDailyActivePrincipleDoseByProductId_hepaticInsufficiency, _checkDailyActivePrincipleDoseByProductId_indicationIds, _checkDailyActivePrincipleDoseByProductId_routeIds);
        System.out.println("checkDailyActivePrincipleDoseByProductId.result=" + _checkDailyActivePrincipleDoseByProductId__return);


        }
        {
        System.out.println("Invoking searchPosologyUnitByUcdId...");
        java.lang.Integer _searchPosologyUnitByUcdId_ucdId = null;
        com.vidal.merlin.wsclient.posology.ArrayOfPosologyUnit _searchPosologyUnitByUcdId__return = port.searchPosologyUnitByUcdId(_searchPosologyUnitByUcdId_ucdId);
        System.out.println("searchPosologyUnitByUcdId.result=" + _searchPosologyUnitByUcdId__return);


        }
        {
        System.out.println("Invoking checkActivePrincipleDoseForProductIdIndicationIdsRouteIds...");
        java.lang.Integer _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_productId = null;
        java.lang.Double _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_dose = null;
        com.vidal.merlin.wsclient.posology.DoseUnit _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_doseUnit = null;
        java.lang.Boolean _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_administrationDividedPerTimeUnit = null;
        java.lang.Double _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_frequency = null;
        com.vidal.merlin.wsclient.posology.PosologyFrequencyType _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_frequencyType = null;
        java.lang.Integer _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_frequencyTypeDetail = null;
        java.lang.Integer _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_durationValue = null;
        com.vidal.merlin.wsclient.posology.DurationType _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_durationType = null;
        java.lang.Integer _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_secondDurationValue = null;
        com.vidal.merlin.wsclient.posology.DurationType _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_secondDurationType = null;
        java.lang.Integer _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_thirdDurationValue = null;
        com.vidal.merlin.wsclient.posology.DurationType _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_thirdDurationType = null;
        com.vidal.merlin.wsclient.posology.Gender _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_gender = null;
        float _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_age = 0.0f;
        float _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_weight = 0.0f;
        java.lang.Integer _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_height = null;
        java.lang.Integer _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_creatinClearance = null;
        com.vidal.merlin.wsclient.posology.HepaticInsufficiency _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_hepaticInsufficiency = null;
        com.vidal.merlin.wsclient.posology.ArrayOfInt _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_indicationIds = null;
        com.vidal.merlin.wsclient.posology.ArrayOfInt _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_routeIds = null;
        com.vidal.merlin.wsclient.posology.ArrayOfPosologyAlert _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds__return = port.checkActivePrincipleDoseForProductIdIndicationIdsRouteIds(_checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_productId, _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_dose, _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_doseUnit, _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_administrationDividedPerTimeUnit, _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_frequency, _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_frequencyType, _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_frequencyTypeDetail, _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_durationValue, _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_durationType, _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_secondDurationValue, _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_secondDurationType, _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_thirdDurationValue, _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_thirdDurationType, _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_gender, _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_age, _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_weight, _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_height, _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_creatinClearance, _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_hepaticInsufficiency, _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_indicationIds, _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds_routeIds);
        System.out.println("checkActivePrincipleDoseForProductIdIndicationIdsRouteIds.result=" + _checkActivePrincipleDoseForProductIdIndicationIdsRouteIds__return);


        }
        {
        System.out.println("Invoking searchDoseUnitByCommonNameGroupId...");
        java.lang.Integer _searchDoseUnitByCommonNameGroupId_commonNameGroupId = null;
        com.vidal.merlin.wsclient.posology.ArrayOfDoseUnit _searchDoseUnitByCommonNameGroupId__return = port.searchDoseUnitByCommonNameGroupId(_searchDoseUnitByCommonNameGroupId_commonNameGroupId);
        System.out.println("searchDoseUnitByCommonNameGroupId.result=" + _searchDoseUnitByCommonNameGroupId__return);


        }
        {
        System.out.println("Invoking getAmmPosologyByProductId...");
        java.lang.Integer _getAmmPosologyByProductId_productId = null;
        java.lang.String _getAmmPosologyByProductId__return = port.getAmmPosologyByProductId(_getAmmPosologyByProductId_productId);
        System.out.println("getAmmPosologyByProductId.result=" + _getAmmPosologyByProductId__return);


        }
        {
        System.out.println("Invoking checkDailyDoseByProductId...");
        java.lang.Integer _checkDailyDoseByProductId_productId = null;
        java.lang.Double _checkDailyDoseByProductId_dose = null;
        java.lang.Integer _checkDailyDoseByProductId_unitId = null;
        com.vidal.merlin.wsclient.posology.PosologyFrequencyType _checkDailyDoseByProductId_frequencyType = null;
        com.vidal.merlin.wsclient.posology.Gender _checkDailyDoseByProductId_gender = null;
        float _checkDailyDoseByProductId_age = 0.0f;
        float _checkDailyDoseByProductId_weight = 0.0f;
        java.lang.Integer _checkDailyDoseByProductId_height = null;
        java.lang.Integer _checkDailyDoseByProductId_creatinClearance = null;
        com.vidal.merlin.wsclient.posology.HepaticInsufficiency _checkDailyDoseByProductId_hepaticInsufficiency = null;
        com.vidal.merlin.wsclient.posology.ArrayOfInt _checkDailyDoseByProductId_indicationIds = null;
        com.vidal.merlin.wsclient.posology.ArrayOfInt _checkDailyDoseByProductId_routeIds = null;
        com.vidal.merlin.wsclient.posology.PosologyAlerts _checkDailyDoseByProductId__return = port.checkDailyDoseByProductId(_checkDailyDoseByProductId_productId, _checkDailyDoseByProductId_dose, _checkDailyDoseByProductId_unitId, _checkDailyDoseByProductId_frequencyType, _checkDailyDoseByProductId_gender, _checkDailyDoseByProductId_age, _checkDailyDoseByProductId_weight, _checkDailyDoseByProductId_height, _checkDailyDoseByProductId_creatinClearance, _checkDailyDoseByProductId_hepaticInsufficiency, _checkDailyDoseByProductId_indicationIds, _checkDailyDoseByProductId_routeIds);
        System.out.println("checkDailyDoseByProductId.result=" + _checkDailyDoseByProductId__return);


        }
        {
        System.out.println("Invoking searchPosologyRouteByProductId...");
        java.lang.Integer _searchPosologyRouteByProductId_productId = null;
        com.vidal.merlin.wsclient.posology.Gender _searchPosologyRouteByProductId_gender = null;
        java.lang.Float _searchPosologyRouteByProductId_age = null;
        java.lang.Float _searchPosologyRouteByProductId_weight = null;
        java.lang.Integer _searchPosologyRouteByProductId_height = null;
        java.lang.Integer _searchPosologyRouteByProductId_creatinClearance = null;
        com.vidal.merlin.wsclient.posology.HepaticInsufficiency _searchPosologyRouteByProductId_hepaticInsufficiency = null;
        com.vidal.merlin.wsclient.posology.ArrayOfInt _searchPosologyRouteByProductId_indicationIds = null;
        com.vidal.merlin.wsclient.posology.ArrayOfRoute _searchPosologyRouteByProductId__return = port.searchPosologyRouteByProductId(_searchPosologyRouteByProductId_productId, _searchPosologyRouteByProductId_gender, _searchPosologyRouteByProductId_age, _searchPosologyRouteByProductId_weight, _searchPosologyRouteByProductId_height, _searchPosologyRouteByProductId_creatinClearance, _searchPosologyRouteByProductId_hepaticInsufficiency, _searchPosologyRouteByProductId_indicationIds);
        System.out.println("searchPosologyRouteByProductId.result=" + _searchPosologyRouteByProductId__return);


        }
        {
        System.out.println("Invoking checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds...");
        java.lang.Integer _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_commonNameGroupId = null;
        java.lang.Double _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_dose = null;
        java.lang.Integer _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_unitId = null;
        java.lang.Boolean _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_administrationDividedPerTimeUnit = null;
        java.lang.Double _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_frequency = null;
        com.vidal.merlin.wsclient.posology.PosologyFrequencyType _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_frequencyType = null;
        java.lang.Integer _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_frequencyTypeDetail = null;
        java.lang.Integer _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_durationValue = null;
        com.vidal.merlin.wsclient.posology.DurationType _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_durationType = null;
        java.lang.Integer _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_secondDurationValue = null;
        com.vidal.merlin.wsclient.posology.DurationType _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_secondDurationType = null;
        java.lang.Integer _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_thirdDurationValue = null;
        com.vidal.merlin.wsclient.posology.DurationType _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_thirdDurationType = null;
        com.vidal.merlin.wsclient.posology.Gender _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_gender = null;
        float _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_age = 0.0f;
        float _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_weight = 0.0f;
        java.lang.Integer _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_height = null;
        java.lang.Integer _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_creatinClearance = null;
        com.vidal.merlin.wsclient.posology.HepaticInsufficiency _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_hepaticInsufficiency = null;
        com.vidal.merlin.wsclient.posology.ArrayOfInt _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_indicationIds = null;
        com.vidal.merlin.wsclient.posology.ArrayOfInt _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_routeIds = null;
        com.vidal.merlin.wsclient.posology.CommonNameGroupPosologyAlertList _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds__return = port.checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds(_checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_commonNameGroupId, _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_dose, _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_unitId, _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_administrationDividedPerTimeUnit, _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_frequency, _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_frequencyType, _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_frequencyTypeDetail, _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_durationValue, _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_durationType, _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_secondDurationValue, _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_secondDurationType, _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_thirdDurationValue, _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_thirdDurationType, _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_gender, _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_age, _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_weight, _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_height, _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_creatinClearance, _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_hepaticInsufficiency, _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_indicationIds, _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds_routeIds);
        System.out.println("checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds.result=" + _checkNumberOfDoseForCommonNameGroupIdIndicationIdsRouteIds__return);


        }
        {
        System.out.println("Invoking searchActivePrincipleDosesByProductId...");
        java.lang.Integer _searchActivePrincipleDosesByProductId_productId = null;
        com.vidal.merlin.wsclient.posology.Gender _searchActivePrincipleDosesByProductId_gender = null;
        float _searchActivePrincipleDosesByProductId_age = 0.0f;
        float _searchActivePrincipleDosesByProductId_weight = 0.0f;
        java.lang.Integer _searchActivePrincipleDosesByProductId_height = null;
        java.lang.Integer _searchActivePrincipleDosesByProductId_creatinClearance = null;
        com.vidal.merlin.wsclient.posology.HepaticInsufficiency _searchActivePrincipleDosesByProductId_hepaticInsufficiency = null;
        com.vidal.merlin.wsclient.posology.ArrayOfInt _searchActivePrincipleDosesByProductId_indicationIds = null;
        com.vidal.merlin.wsclient.posology.ArrayOfInt _searchActivePrincipleDosesByProductId_routeIds = null;
        com.vidal.merlin.wsclient.posology.ArrayOfActivePrincipleDoses _searchActivePrincipleDosesByProductId__return = port.searchActivePrincipleDosesByProductId(_searchActivePrincipleDosesByProductId_productId, _searchActivePrincipleDosesByProductId_gender, _searchActivePrincipleDosesByProductId_age, _searchActivePrincipleDosesByProductId_weight, _searchActivePrincipleDosesByProductId_height, _searchActivePrincipleDosesByProductId_creatinClearance, _searchActivePrincipleDosesByProductId_hepaticInsufficiency, _searchActivePrincipleDosesByProductId_indicationIds, _searchActivePrincipleDosesByProductId_routeIds);
        System.out.println("searchActivePrincipleDosesByProductId.result=" + _searchActivePrincipleDosesByProductId__return);


        }
        {
        System.out.println("Invoking searchPosologyUnitByCommonNameGroupId...");
        java.lang.Integer _searchPosologyUnitByCommonNameGroupId_commonNameGroupId = null;
        com.vidal.merlin.wsclient.posology.CommonNameGroupPosologyUnitList _searchPosologyUnitByCommonNameGroupId__return = port.searchPosologyUnitByCommonNameGroupId(_searchPosologyUnitByCommonNameGroupId_commonNameGroupId);
        System.out.println("searchPosologyUnitByCommonNameGroupId.result=" + _searchPosologyUnitByCommonNameGroupId__return);


        }
        {
        System.out.println("Invoking checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds...");
        java.lang.Integer _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_commonNameGroupId = null;
        java.lang.Double _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_dose = null;
        com.vidal.merlin.wsclient.posology.DoseUnit _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_doseUnit = null;
        java.lang.Boolean _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_administrationDividedPerTimeUnit = null;
        java.lang.Double _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_frequency = null;
        com.vidal.merlin.wsclient.posology.PosologyFrequencyType _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_frequencyType = null;
        java.lang.Integer _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_frequencyTypeDetail = null;
        java.lang.Integer _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_durationValue = null;
        com.vidal.merlin.wsclient.posology.DurationType _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_durationType = null;
        java.lang.Integer _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_secondDurationValue = null;
        com.vidal.merlin.wsclient.posology.DurationType _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_secondDurationType = null;
        java.lang.Integer _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_thirdDurationValue = null;
        com.vidal.merlin.wsclient.posology.DurationType _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_thirdDurationType = null;
        com.vidal.merlin.wsclient.posology.Gender _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_gender = null;
        float _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_age = 0.0f;
        float _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_weight = 0.0f;
        java.lang.Integer _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_height = null;
        java.lang.Integer _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_creatinClearance = null;
        com.vidal.merlin.wsclient.posology.HepaticInsufficiency _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_hepaticInsufficiency = null;
        com.vidal.merlin.wsclient.posology.ArrayOfInt _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_indicationIds = null;
        com.vidal.merlin.wsclient.posology.ArrayOfInt _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_routeIds = null;
        com.vidal.merlin.wsclient.posology.CommonNameGroupPosologyAlertList _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds__return = port.checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds(_checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_commonNameGroupId, _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_dose, _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_doseUnit, _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_administrationDividedPerTimeUnit, _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_frequency, _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_frequencyType, _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_frequencyTypeDetail, _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_durationValue, _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_durationType, _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_secondDurationValue, _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_secondDurationType, _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_thirdDurationValue, _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_thirdDurationType, _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_gender, _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_age, _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_weight, _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_height, _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_creatinClearance, _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_hepaticInsufficiency, _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_indicationIds, _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds_routeIds);
        System.out.println("checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds.result=" + _checkActivePrincipleDoseForCommonNameGroupIdIndicationIdsRouteIds__return);


        }
        {
        System.out.println("Invoking checkNumberOfDoseForProductIdIndicationIdsRouteIds...");
        java.lang.Integer _checkNumberOfDoseForProductIdIndicationIdsRouteIds_productId = null;
        java.lang.Double _checkNumberOfDoseForProductIdIndicationIdsRouteIds_dose = null;
        java.lang.Integer _checkNumberOfDoseForProductIdIndicationIdsRouteIds_unitId = null;
        java.lang.Boolean _checkNumberOfDoseForProductIdIndicationIdsRouteIds_administrationDividedPerTimeUnit = null;
        java.lang.Double _checkNumberOfDoseForProductIdIndicationIdsRouteIds_frequency = null;
        com.vidal.merlin.wsclient.posology.PosologyFrequencyType _checkNumberOfDoseForProductIdIndicationIdsRouteIds_frequencyType = null;
        java.lang.Integer _checkNumberOfDoseForProductIdIndicationIdsRouteIds_frequencyTypeDetail = null;
        java.lang.Integer _checkNumberOfDoseForProductIdIndicationIdsRouteIds_durationValue = null;
        com.vidal.merlin.wsclient.posology.DurationType _checkNumberOfDoseForProductIdIndicationIdsRouteIds_durationType = null;
        java.lang.Integer _checkNumberOfDoseForProductIdIndicationIdsRouteIds_secondDurationValue = null;
        com.vidal.merlin.wsclient.posology.DurationType _checkNumberOfDoseForProductIdIndicationIdsRouteIds_secondDurationType = null;
        java.lang.Integer _checkNumberOfDoseForProductIdIndicationIdsRouteIds_thirdDurationValue = null;
        com.vidal.merlin.wsclient.posology.DurationType _checkNumberOfDoseForProductIdIndicationIdsRouteIds_thirdDurationType = null;
        com.vidal.merlin.wsclient.posology.Gender _checkNumberOfDoseForProductIdIndicationIdsRouteIds_gender = null;
        float _checkNumberOfDoseForProductIdIndicationIdsRouteIds_age = 0.0f;
        float _checkNumberOfDoseForProductIdIndicationIdsRouteIds_weight = 0.0f;
        java.lang.Integer _checkNumberOfDoseForProductIdIndicationIdsRouteIds_height = null;
        java.lang.Integer _checkNumberOfDoseForProductIdIndicationIdsRouteIds_creatinClearance = null;
        com.vidal.merlin.wsclient.posology.HepaticInsufficiency _checkNumberOfDoseForProductIdIndicationIdsRouteIds_hepaticInsufficiency = null;
        com.vidal.merlin.wsclient.posology.ArrayOfInt _checkNumberOfDoseForProductIdIndicationIdsRouteIds_indicationIds = null;
        com.vidal.merlin.wsclient.posology.ArrayOfInt _checkNumberOfDoseForProductIdIndicationIdsRouteIds_routeIds = null;
        com.vidal.merlin.wsclient.posology.ArrayOfPosologyAlert _checkNumberOfDoseForProductIdIndicationIdsRouteIds__return = port.checkNumberOfDoseForProductIdIndicationIdsRouteIds(_checkNumberOfDoseForProductIdIndicationIdsRouteIds_productId, _checkNumberOfDoseForProductIdIndicationIdsRouteIds_dose, _checkNumberOfDoseForProductIdIndicationIdsRouteIds_unitId, _checkNumberOfDoseForProductIdIndicationIdsRouteIds_administrationDividedPerTimeUnit, _checkNumberOfDoseForProductIdIndicationIdsRouteIds_frequency, _checkNumberOfDoseForProductIdIndicationIdsRouteIds_frequencyType, _checkNumberOfDoseForProductIdIndicationIdsRouteIds_frequencyTypeDetail, _checkNumberOfDoseForProductIdIndicationIdsRouteIds_durationValue, _checkNumberOfDoseForProductIdIndicationIdsRouteIds_durationType, _checkNumberOfDoseForProductIdIndicationIdsRouteIds_secondDurationValue, _checkNumberOfDoseForProductIdIndicationIdsRouteIds_secondDurationType, _checkNumberOfDoseForProductIdIndicationIdsRouteIds_thirdDurationValue, _checkNumberOfDoseForProductIdIndicationIdsRouteIds_thirdDurationType, _checkNumberOfDoseForProductIdIndicationIdsRouteIds_gender, _checkNumberOfDoseForProductIdIndicationIdsRouteIds_age, _checkNumberOfDoseForProductIdIndicationIdsRouteIds_weight, _checkNumberOfDoseForProductIdIndicationIdsRouteIds_height, _checkNumberOfDoseForProductIdIndicationIdsRouteIds_creatinClearance, _checkNumberOfDoseForProductIdIndicationIdsRouteIds_hepaticInsufficiency, _checkNumberOfDoseForProductIdIndicationIdsRouteIds_indicationIds, _checkNumberOfDoseForProductIdIndicationIdsRouteIds_routeIds);
        System.out.println("checkNumberOfDoseForProductIdIndicationIdsRouteIds.result=" + _checkNumberOfDoseForProductIdIndicationIdsRouteIds__return);


        }
        {
        System.out.println("Invoking searchPosologyRouteByCommonNameGroupId...");
        java.lang.Integer _searchPosologyRouteByCommonNameGroupId_commonNameGroupId = null;
        com.vidal.merlin.wsclient.posology.Gender _searchPosologyRouteByCommonNameGroupId_gender = null;
        java.lang.Float _searchPosologyRouteByCommonNameGroupId_age = null;
        java.lang.Float _searchPosologyRouteByCommonNameGroupId_weight = null;
        java.lang.Integer _searchPosologyRouteByCommonNameGroupId_height = null;
        java.lang.Integer _searchPosologyRouteByCommonNameGroupId_creatinClearance = null;
        com.vidal.merlin.wsclient.posology.HepaticInsufficiency _searchPosologyRouteByCommonNameGroupId_hepaticInsufficiency = null;
        com.vidal.merlin.wsclient.posology.ArrayOfInt _searchPosologyRouteByCommonNameGroupId_indicationIds = null;
        com.vidal.merlin.wsclient.posology.CommonNameGroupPosologyRouteList _searchPosologyRouteByCommonNameGroupId__return = port.searchPosologyRouteByCommonNameGroupId(_searchPosologyRouteByCommonNameGroupId_commonNameGroupId, _searchPosologyRouteByCommonNameGroupId_gender, _searchPosologyRouteByCommonNameGroupId_age, _searchPosologyRouteByCommonNameGroupId_weight, _searchPosologyRouteByCommonNameGroupId_height, _searchPosologyRouteByCommonNameGroupId_creatinClearance, _searchPosologyRouteByCommonNameGroupId_hepaticInsufficiency, _searchPosologyRouteByCommonNameGroupId_indicationIds);
        System.out.println("searchPosologyRouteByCommonNameGroupId.result=" + _searchPosologyRouteByCommonNameGroupId__return);


        }
        {
        System.out.println("Invoking searchDoseUnitByProductId...");
        java.lang.Integer _searchDoseUnitByProductId_productId = null;
        com.vidal.merlin.wsclient.posology.ArrayOfDoseUnit _searchDoseUnitByProductId__return = port.searchDoseUnitByProductId(_searchDoseUnitByProductId_productId);
        System.out.println("searchDoseUnitByProductId.result=" + _searchDoseUnitByProductId__return);


        }
        {
        System.out.println("Invoking searchDosesByProductId...");
        java.lang.Integer _searchDosesByProductId_productId = null;
        com.vidal.merlin.wsclient.posology.Gender _searchDosesByProductId_gender = null;
        float _searchDosesByProductId_age = 0.0f;
        float _searchDosesByProductId_weight = 0.0f;
        java.lang.Integer _searchDosesByProductId_height = null;
        java.lang.Integer _searchDosesByProductId_creatinClearance = null;
        com.vidal.merlin.wsclient.posology.HepaticInsufficiency _searchDosesByProductId_hepaticInsufficiency = null;
        com.vidal.merlin.wsclient.posology.ArrayOfInt _searchDosesByProductId_indicationIds = null;
        com.vidal.merlin.wsclient.posology.ArrayOfInt _searchDosesByProductId_routeIds = null;
        com.vidal.merlin.wsclient.posology.ArrayOfNumberOfDoses _searchDosesByProductId__return = port.searchDosesByProductId(_searchDosesByProductId_productId, _searchDosesByProductId_gender, _searchDosesByProductId_age, _searchDosesByProductId_weight, _searchDosesByProductId_height, _searchDosesByProductId_creatinClearance, _searchDosesByProductId_hepaticInsufficiency, _searchDosesByProductId_indicationIds, _searchDosesByProductId_routeIds);
        System.out.println("searchDosesByProductId.result=" + _searchDosesByProductId__return);


        }
        {
        System.out.println("Invoking checkTreatmentDurationByProductId...");
        java.lang.Integer _checkTreatmentDurationByProductId_productId = null;
        java.lang.Integer _checkTreatmentDurationByProductId_durationValue = null;
        com.vidal.merlin.wsclient.posology.DurationType _checkTreatmentDurationByProductId_durationType = null;
        com.vidal.merlin.wsclient.posology.Gender _checkTreatmentDurationByProductId_gender = null;
        float _checkTreatmentDurationByProductId_age = 0.0f;
        float _checkTreatmentDurationByProductId_weight = 0.0f;
        java.lang.Integer _checkTreatmentDurationByProductId_height = null;
        java.lang.Integer _checkTreatmentDurationByProductId_creatinClearance = null;
        com.vidal.merlin.wsclient.posology.HepaticInsufficiency _checkTreatmentDurationByProductId_hepaticInsufficiency = null;
        com.vidal.merlin.wsclient.posology.ArrayOfInt _checkTreatmentDurationByProductId_indicationIds = null;
        com.vidal.merlin.wsclient.posology.ArrayOfInt _checkTreatmentDurationByProductId_routeIds = null;
        com.vidal.merlin.wsclient.posology.PosologyAlerts _checkTreatmentDurationByProductId__return = port.checkTreatmentDurationByProductId(_checkTreatmentDurationByProductId_productId, _checkTreatmentDurationByProductId_durationValue, _checkTreatmentDurationByProductId_durationType, _checkTreatmentDurationByProductId_gender, _checkTreatmentDurationByProductId_age, _checkTreatmentDurationByProductId_weight, _checkTreatmentDurationByProductId_height, _checkTreatmentDurationByProductId_creatinClearance, _checkTreatmentDurationByProductId_hepaticInsufficiency, _checkTreatmentDurationByProductId_indicationIds, _checkTreatmentDurationByProductId_routeIds);
        System.out.println("checkTreatmentDurationByProductId.result=" + _checkTreatmentDurationByProductId__return);


        }

        System.exit(0);
    }

}
