
/*
 * 
 */

package com.vidal.merlin.wsclient.administrationRoute;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:19 CET 2013
 * Generated source version: 2.2.6
 * 
 */


@WebServiceClient(name = "AdministrationRouteService", 
                  wsdlLocation = "http://localhost:8011/merlin-service/services/AdministrationRouteService?wsdl",
                  targetNamespace = "urn:Vidal") 
public class AdministrationRouteService_Service extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("urn:Vidal", "AdministrationRouteService");
    public final static QName AdministrationRouteServiceHttpPort = new QName("urn:Vidal", "AdministrationRouteServiceHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8011/merlin-service/services/AdministrationRouteService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8011/merlin-service/services/AdministrationRouteService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public AdministrationRouteService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AdministrationRouteService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdministrationRouteService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns AdministrationRouteService
     */
    @WebEndpoint(name = "AdministrationRouteServiceHttpPort")
    public AdministrationRouteService getAdministrationRouteServiceHttpPort() {
        return super.getPort(AdministrationRouteServiceHttpPort, AdministrationRouteService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AdministrationRouteService
     */
    @WebEndpoint(name = "AdministrationRouteServiceHttpPort")
    public AdministrationRouteService getAdministrationRouteServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(AdministrationRouteServiceHttpPort, AdministrationRouteService.class, features);
    }

}
