
package com.vidal.merlin.wsclient.administrationRoute;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:19 CET 2013
 * Generated source version: 2.2.6
 * 
 */

public final class AdministrationRouteService_AdministrationRouteServiceHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("urn:Vidal", "AdministrationRouteService");

    private AdministrationRouteService_AdministrationRouteServiceHttpPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = AdministrationRouteService_Service.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AdministrationRouteService_Service ss = new AdministrationRouteService_Service(wsdlURL, SERVICE_NAME);
        AdministrationRouteService port = ss.getAdministrationRouteServiceHttpPort();  
        
        {
        System.out.println("Invoking searchByName...");
        java.lang.String _searchByName_name = "";
        com.vidal.merlin.wsclient.administrationRoute.ArrayOfRoute _searchByName__return = port.searchByName(_searchByName_name);
        System.out.println("searchByName.result=" + _searchByName__return);


        }
        {
        System.out.println("Invoking getAllRoutes...");
        java.lang.Integer _getAllRoutes_pageNumber = null;
        java.lang.Integer _getAllRoutes_pageSize = null;
        com.vidal.merlin.wsclient.administrationRoute.PagedResultRoute _getAllRoutes__return = port.getAllRoutes(_getAllRoutes_pageNumber, _getAllRoutes_pageSize);
        System.out.println("getAllRoutes.result=" + _getAllRoutes__return);


        }
        {
        System.out.println("Invoking searchByIds...");
        com.vidal.merlin.wsclient.administrationRoute.ArrayOfInt _searchByIds_routeIds = null;
        com.vidal.merlin.wsclient.administrationRoute.ArrayOfRoute _searchByIds__return = port.searchByIds(_searchByIds_routeIds);
        System.out.println("searchByIds.result=" + _searchByIds__return);


        }

        System.exit(0);
    }

}
