
package com.vidal.merlin.wsclient.productRange;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:30 CET 2013
 * Generated source version: 2.2.6
 * 
 */

public final class ProductRangeService_ProductRangeServiceHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("urn:Vidal", "ProductRangeService");

    private ProductRangeService_ProductRangeServiceHttpPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = ProductRangeService_Service.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ProductRangeService_Service ss = new ProductRangeService_Service(wsdlURL, SERVICE_NAME);
        ProductRangeService port = ss.getProductRangeServiceHttpPort();  
        
        {
        System.out.println("Invoking getAllProductRanges...");
        java.lang.Integer _getAllProductRanges_pageNumber = null;
        java.lang.Integer _getAllProductRanges_pageSize = null;
        com.vidal.merlin.wsclient.productRange.PagedResultProductRange _getAllProductRanges__return = port.getAllProductRanges(_getAllProductRanges_pageNumber, _getAllProductRanges_pageSize);
        System.out.println("getAllProductRanges.result=" + _getAllProductRanges__return);


        }
        {
        System.out.println("Invoking searchByName...");
        java.lang.String _searchByName_productRangeName = "";
        com.vidal.merlin.wsclient.productRange.ArrayOfProductRange _searchByName__return = port.searchByName(_searchByName_productRangeName);
        System.out.println("searchByName.result=" + _searchByName__return);


        }
        {
        System.out.println("Invoking searchByProductIds...");
        com.vidal.merlin.wsclient.productRange.ArrayOfInt _searchByProductIds_productIds = null;
        com.vidal.merlin.wsclient.productRange.ArrayOfProductRangeProductCouple _searchByProductIds__return = port.searchByProductIds(_searchByProductIds_productIds);
        System.out.println("searchByProductIds.result=" + _searchByProductIds__return);


        }
        {
        System.out.println("Invoking searchByUcdIds...");
        com.vidal.merlin.wsclient.productRange.ArrayOfInt _searchByUcdIds_ucdIds = null;
        com.vidal.merlin.wsclient.productRange.ArrayOfProductRangeUcdCouple _searchByUcdIds__return = port.searchByUcdIds(_searchByUcdIds_ucdIds);
        System.out.println("searchByUcdIds.result=" + _searchByUcdIds__return);


        }
        {
        System.out.println("Invoking searchByIds...");
        com.vidal.merlin.wsclient.productRange.ArrayOfInt _searchByIds_productRangeIds = null;
        com.vidal.merlin.wsclient.productRange.ArrayOfProductRange _searchByIds__return = port.searchByIds(_searchByIds_productRangeIds);
        System.out.println("searchByIds.result=" + _searchByIds__return);


        }
        {
        System.out.println("Invoking searchByPackIds...");
        com.vidal.merlin.wsclient.productRange.ArrayOfInt _searchByPackIds_packIds = null;
        com.vidal.merlin.wsclient.productRange.ArrayOfProductRangePackCouple _searchByPackIds__return = port.searchByPackIds(_searchByPackIds_packIds);
        System.out.println("searchByPackIds.result=" + _searchByPackIds__return);


        }

        System.exit(0);
    }

}
