
package com.vidal.merlin.wsclient.atc;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:22 CET 2013
 * Generated source version: 2.2.6
 * 
 */

public final class AtcService_AtcServiceHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("urn:Vidal", "AtcService");

    private AtcService_AtcServiceHttpPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = AtcService_Service.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AtcService_Service ss = new AtcService_Service(wsdlURL, SERVICE_NAME);
        AtcService port = ss.getAtcServiceHttpPort();  
        
        {
        System.out.println("Invoking searchByCode...");
        java.lang.String _searchByCode_code = "";
        com.vidal.merlin.wsclient.atc.ArrayOfAtc _searchByCode__return = port.searchByCode(_searchByCode_code);
        System.out.println("searchByCode.result=" + _searchByCode__return);


        }
        {
        System.out.println("Invoking searchByProductId...");
        java.lang.Integer _searchByProductId_productId = null;
        com.vidal.merlin.wsclient.atc.ArrayOfAtc _searchByProductId__return = port.searchByProductId(_searchByProductId_productId);
        System.out.println("searchByProductId.result=" + _searchByProductId__return);


        }
        {
        System.out.println("Invoking searchByName...");
        java.lang.String _searchByName_name = "";
        com.vidal.merlin.wsclient.atc.ArrayOfAtc _searchByName__return = port.searchByName(_searchByName_name);
        System.out.println("searchByName.result=" + _searchByName__return);


        }
        {
        System.out.println("Invoking getChildren...");
        java.lang.Integer _getChildren_atcId = null;
        com.vidal.merlin.wsclient.atc.ArrayOfAtc _getChildren__return = port.getChildren(_getChildren_atcId);
        System.out.println("getChildren.result=" + _getChildren__return);


        }
        {
        System.out.println("Invoking getRootNode...");
        com.vidal.merlin.wsclient.atc.Atc _getRootNode__return = port.getRootNode();
        System.out.println("getRootNode.result=" + _getRootNode__return);


        }
        {
        System.out.println("Invoking searchById...");
        java.lang.Integer _searchById_atcId = null;
        com.vidal.merlin.wsclient.atc.Atc _searchById__return = port.searchById(_searchById_atcId);
        System.out.println("searchById.result=" + _searchById__return);


        }
        {
        System.out.println("Invoking getAllAtcs...");
        java.lang.Integer _getAllAtcs_pageNumber = null;
        java.lang.Integer _getAllAtcs_pageSize = null;
        com.vidal.merlin.wsclient.atc.PagedResultAtc _getAllAtcs__return = port.getAllAtcs(_getAllAtcs_pageNumber, _getAllAtcs_pageSize);
        System.out.println("getAllAtcs.result=" + _getAllAtcs__return);


        }
        {
        System.out.println("Invoking getParent...");
        java.lang.Integer _getParent_atcId = null;
        com.vidal.merlin.wsclient.atc.Atc _getParent__return = port.getParent(_getParent_atcId);
        System.out.println("getParent.result=" + _getParent__return);


        }
        {
        System.out.println("Invoking searchByCommonNameGroupId...");
        java.lang.Integer _searchByCommonNameGroupId_commonNameGroupId = null;
        com.vidal.merlin.wsclient.atc.ArrayOfAtc _searchByCommonNameGroupId__return = port.searchByCommonNameGroupId(_searchByCommonNameGroupId_commonNameGroupId);
        System.out.println("searchByCommonNameGroupId.result=" + _searchByCommonNameGroupId__return);


        }
        {
        System.out.println("Invoking findByProductId...");
        java.lang.Integer _findByProductId_productId = null;
        com.vidal.merlin.wsclient.atc.ArrayOfAtc _findByProductId__return = port.findByProductId(_findByProductId_productId);
        System.out.println("findByProductId.result=" + _findByProductId__return);


        }

        System.exit(0);
    }

}
