package com.vidal.merlin.wsclient.allergy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:20 CET 2013
 * Generated source version: 2.2.6
 * 
 */
 
@WebService(targetNamespace = "urn:Vidal", name = "allergyService")
@XmlSeeAlso({ObjectFactory.class})
public interface AllergyService {

    @WebResult(name = "commonNameGroupAllergyCoupleList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getAlertsOnCommonNameGroupActivePrincipleAllergiesClass", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.allergy.GetAlertsOnCommonNameGroupActivePrincipleAllergiesClass")
    @ResponseWrapper(localName = "getAlertsOnCommonNameGroupActivePrincipleAllergiesClassResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.allergy.GetAlertsOnCommonNameGroupActivePrincipleAllergiesClassResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.allergy.ArrayOfCommonNameGroupAllergyCouple getAlertsOnCommonNameGroupActivePrincipleAllergiesClass(
        @WebParam(name = "commonNameGroupIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.allergy.ArrayOfInt commonNameGroupIds,
        @WebParam(name = "allergyIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.allergy.ArrayOfInt allergyIds
    );

    @WebResult(name = "allergyList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByProductId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.allergy.SearchByProductId")
    @ResponseWrapper(localName = "searchByProductIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.allergy.SearchByProductIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.allergy.ArrayOfAllergy searchByProductId(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        java.lang.Integer productId
    );

    @WebResult(name = "allergyList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByMoleculeId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.allergy.SearchByMoleculeId")
    @ResponseWrapper(localName = "searchByMoleculeIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.allergy.SearchByMoleculeIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.allergy.ArrayOfAllergy searchByMoleculeId(
        @WebParam(name = "moleculeId", targetNamespace = "urn:Vidal")
        java.lang.Integer moleculeId
    );

    @WebResult(name = "allergyList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByName", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.allergy.SearchByName")
    @ResponseWrapper(localName = "searchByNameResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.allergy.SearchByNameResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.allergy.ArrayOfAllergy searchByName(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        java.lang.String name
    );

    @WebResult(name = "commonNameGroupAllergyCouples", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchCommonNameGroupAllergyClassAlerts", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.allergy.SearchCommonNameGroupAllergyClassAlerts")
    @ResponseWrapper(localName = "searchCommonNameGroupAllergyClassAlertsResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.allergy.SearchCommonNameGroupAllergyClassAlertsResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.allergy.CommonNameGroupAllergyCouples searchCommonNameGroupAllergyClassAlerts(
        @WebParam(name = "commonNameGroupIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.allergy.ArrayOfInt commonNameGroupIds,
        @WebParam(name = "allergyIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.allergy.ArrayOfInt allergyIds
    );

    @WebResult(name = "commonNameGroupMoleculeCoupleList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getAlertsOnCommonNameGroupActivePrincipleAllergiesMolecules", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.allergy.GetAlertsOnCommonNameGroupActivePrincipleAllergiesMolecules")
    @ResponseWrapper(localName = "getAlertsOnCommonNameGroupActivePrincipleAllergiesMoleculesResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.allergy.GetAlertsOnCommonNameGroupActivePrincipleAllergiesMoleculesResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.allergy.ArrayOfCommonNameGroupMoleculeCouple getAlertsOnCommonNameGroupActivePrincipleAllergiesMolecules(
        @WebParam(name = "commonNameGroupIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.allergy.ArrayOfInt commonNameGroupIds,
        @WebParam(name = "moleculeIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.allergy.ArrayOfInt moleculeIds
    );

    @WebResult(name = "productAllergyCoupleList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getAlertsOnAllergiesClass", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.allergy.GetAlertsOnAllergiesClass")
    @ResponseWrapper(localName = "getAlertsOnAllergiesClassResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.allergy.GetAlertsOnAllergiesClassResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.allergy.ArrayOfProductAllergyCouple getAlertsOnAllergiesClass(
        @WebParam(name = "productIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.allergy.ArrayOfInt productIds,
        @WebParam(name = "allergyIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.allergy.ArrayOfInt allergyIds
    );

    @WebResult(name = "allergy", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchById", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.allergy.SearchById")
    @ResponseWrapper(localName = "searchByIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.allergy.SearchByIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.allergy.Allergy searchById(
        @WebParam(name = "allergyId", targetNamespace = "urn:Vidal")
        java.lang.Integer allergyId
    );

    @WebResult(name = "pagedResultAllergy", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getAllAllergies", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.allergy.GetAllAllergies")
    @ResponseWrapper(localName = "getAllAllergiesResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.allergy.GetAllAllergiesResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.allergy.PagedResultAllergy getAllAllergies(
        @WebParam(name = "pageNumber", targetNamespace = "urn:Vidal")
        java.lang.Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "urn:Vidal")
        java.lang.Integer pageSize
    );

    @WebResult(name = "commonNameGroupMoleculeCouples", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchCommonNameGroupAllergyMoleculeAlerts", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.allergy.SearchCommonNameGroupAllergyMoleculeAlerts")
    @ResponseWrapper(localName = "searchCommonNameGroupAllergyMoleculeAlertsResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.allergy.SearchCommonNameGroupAllergyMoleculeAlertsResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.allergy.CommonNameGroupMoleculeCouples searchCommonNameGroupAllergyMoleculeAlerts(
        @WebParam(name = "commonNameGroupIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.allergy.ArrayOfInt commonNameGroupIds,
        @WebParam(name = "moleculeIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.allergy.ArrayOfInt moleculeIds
    );

    @WebResult(name = "productMoleculeCoupleList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getAlertsOnAllergiesMolecules", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.allergy.GetAlertsOnAllergiesMolecules")
    @ResponseWrapper(localName = "getAlertsOnAllergiesMoleculesResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.allergy.GetAlertsOnAllergiesMoleculesResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.allergy.ArrayOfProductMoleculeCouple getAlertsOnAllergiesMolecules(
        @WebParam(name = "productIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.allergy.ArrayOfInt productIds,
        @WebParam(name = "moleculeIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.allergy.ArrayOfInt moleculeIds
    );

    @WebResult(name = "allergyList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByCommonNameGroupId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.allergy.SearchByCommonNameGroupId")
    @ResponseWrapper(localName = "searchByCommonNameGroupIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.allergy.SearchByCommonNameGroupIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.allergy.CommonNameGroupAllergyList searchByCommonNameGroupId(
        @WebParam(name = "commonNameGroupId", targetNamespace = "urn:Vidal")
        java.lang.Integer commonNameGroupId
    );

    @WebResult(name = "allergyList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchLinkedAllergyByAllergyId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.allergy.SearchLinkedAllergyByAllergyId")
    @ResponseWrapper(localName = "searchLinkedAllergyByAllergyIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.allergy.SearchLinkedAllergyByAllergyIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.allergy.ArrayOfAllergy searchLinkedAllergyByAllergyId(
        @WebParam(name = "allergyId", targetNamespace = "urn:Vidal")
        java.lang.Integer allergyId
    );
}
