package com.vidal.merlin.wsclient.cisp;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:22 CET 2013
 * Generated source version: 2.2.6
 * 
 */
 
@WebService(targetNamespace = "urn:Vidal", name = "cispService")
@XmlSeeAlso({ObjectFactory.class})
public interface CispService {

    @WebResult(name = "cispList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByCode", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.cisp.SearchByCode")
    @ResponseWrapper(localName = "searchByCodeResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.cisp.SearchByCodeResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.cisp.ArrayOfCisp searchByCode(
        @WebParam(name = "code", targetNamespace = "urn:Vidal")
        java.lang.String code
    );

    @WebResult(name = "indicationGroupList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getIndicationGroup", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.cisp.GetIndicationGroup")
    @ResponseWrapper(localName = "getIndicationGroupResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.cisp.GetIndicationGroupResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.cisp.ArrayOfIndicationGroup getIndicationGroup(
        @WebParam(name = "cispId", targetNamespace = "urn:Vidal")
        java.lang.Integer cispId
    );

    @WebResult(name = "cispList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByName", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.cisp.SearchByName")
    @ResponseWrapper(localName = "searchByNameResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.cisp.SearchByNameResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.cisp.ArrayOfCisp searchByName(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        java.lang.String name
    );

    @WebResult(name = "cispList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getChildren", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.cisp.GetChildren")
    @ResponseWrapper(localName = "getChildrenResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.cisp.GetChildrenResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.cisp.ArrayOfCisp getChildren(
        @WebParam(name = "cispId", targetNamespace = "urn:Vidal")
        java.lang.Integer cispId
    );

    @WebResult(name = "cisp", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getRootNode", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.cisp.GetRootNode")
    @ResponseWrapper(localName = "getRootNodeResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.cisp.GetRootNodeResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.cisp.Cisp getRootNode();

    @WebResult(name = "cispList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByIndicationGroupId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.cisp.SearchByIndicationGroupId")
    @ResponseWrapper(localName = "searchByIndicationGroupIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.cisp.SearchByIndicationGroupIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.cisp.ArrayOfCisp searchByIndicationGroupId(
        @WebParam(name = "indicationGroupId", targetNamespace = "urn:Vidal")
        java.lang.Integer indicationGroupId
    );

    @WebResult(name = "cisp", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchById", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.cisp.SearchById")
    @ResponseWrapper(localName = "searchByIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.cisp.SearchByIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.cisp.Cisp searchById(
        @WebParam(name = "cispId", targetNamespace = "urn:Vidal")
        java.lang.Integer cispId
    );

    @WebResult(name = "cisp", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getParent", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.cisp.GetParent")
    @ResponseWrapper(localName = "getParentResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.cisp.GetParentResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.cisp.Cisp getParent(
        @WebParam(name = "cispId", targetNamespace = "urn:Vidal")
        java.lang.Integer cispId
    );
}
