
package com.vidal.merlin.wsclient.lppr;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:28 CET 2013
 * Generated source version: 2.2.6
 * 
 */

public final class LpprService_LpprServiceHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("urn:Vidal", "LpprService");

    private LpprService_LpprServiceHttpPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = LpprService_Service.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        LpprService_Service ss = new LpprService_Service(wsdlURL, SERVICE_NAME);
        LpprService port = ss.getLpprServiceHttpPort();  
        
        {
        System.out.println("Invoking searchByPartialCode...");
        java.lang.String _searchByPartialCode_prefix = "";
        com.vidal.merlin.wsclient.lppr.ArrayOfLppr _searchByPartialCode__return = port.searchByPartialCode(_searchByPartialCode_prefix);
        System.out.println("searchByPartialCode.result=" + _searchByPartialCode__return);


        }
        {
        System.out.println("Invoking searchByCode...");
        java.lang.String _searchByCode_code = "";
        com.vidal.merlin.wsclient.lppr.ArrayOfLppr _searchByCode__return = port.searchByCode(_searchByCode_code);
        System.out.println("searchByCode.result=" + _searchByCode__return);


        }
        {
        System.out.println("Invoking searchByName...");
        java.lang.String _searchByName_lpprName = "";
        com.vidal.merlin.wsclient.lppr.ArrayOfLppr _searchByName__return = port.searchByName(_searchByName_lpprName);
        System.out.println("searchByName.result=" + _searchByName__return);


        }
        {
        System.out.println("Invoking searchByPackId...");
        java.lang.Integer _searchByPackId_packId = null;
        com.vidal.merlin.wsclient.lppr.ArrayOfLppr _searchByPackId__return = port.searchByPackId(_searchByPackId_packId);
        System.out.println("searchByPackId.result=" + _searchByPackId__return);


        }
        {
        System.out.println("Invoking getChildren...");
        java.lang.Integer _getChildren_id = null;
        com.vidal.merlin.wsclient.lppr.ArrayOfLppr _getChildren__return = port.getChildren(_getChildren_id);
        System.out.println("getChildren.result=" + _getChildren__return);


        }
        {
        System.out.println("Invoking getClassificationRootNode...");
        com.vidal.merlin.wsclient.lppr.Lppr _getClassificationRootNode__return = port.getClassificationRootNode();
        System.out.println("getClassificationRootNode.result=" + _getClassificationRootNode__return);


        }
        {
        System.out.println("Invoking getAllParents...");
        java.lang.Integer _getAllParents_id = null;
        com.vidal.merlin.wsclient.lppr.ArrayOfLppr _getAllParents__return = port.getAllParents(_getAllParents_id);
        System.out.println("getAllParents.result=" + _getAllParents__return);


        }
        {
        System.out.println("Invoking getAllChildren...");
        java.lang.Integer _getAllChildren_id = null;
        com.vidal.merlin.wsclient.lppr.ArrayOfLppr _getAllChildren__return = port.getAllChildren(_getAllChildren_id);
        System.out.println("getAllChildren.result=" + _getAllChildren__return);


        }
        {
        System.out.println("Invoking searchById...");
        java.lang.Integer _searchById_lpprId = null;
        com.vidal.merlin.wsclient.lppr.Lppr _searchById__return = port.searchById(_searchById_lpprId);
        System.out.println("searchById.result=" + _searchById__return);


        }
        {
        System.out.println("Invoking getParent...");
        java.lang.Integer _getParent_id = null;
        com.vidal.merlin.wsclient.lppr.Lppr _getParent__return = port.getParent(_getParent_id);
        System.out.println("getParent.result=" + _getParent__return);


        }
        {
        System.out.println("Invoking getReimbursementSchedule...");
        com.vidal.merlin.wsclient.lppr.ArrayOfInt _getReimbursementSchedule_lpprIds = null;
        com.vidal.merlin.wsclient.lppr.ReimbursementScheduleFilter _getReimbursementSchedule_reimbursementScheduleFilter = null;
        com.vidal.merlin.wsclient.lppr.ArrayOfLpprReimbursementCouple _getReimbursementSchedule__return = port.getReimbursementSchedule(_getReimbursementSchedule_lpprIds, _getReimbursementSchedule_reimbursementScheduleFilter);
        System.out.println("getReimbursementSchedule.result=" + _getReimbursementSchedule__return);


        }
        {
        System.out.println("Invoking decompositionPackByPackIds...");
        com.vidal.merlin.wsclient.lppr.ArrayOfInt _decompositionPackByPackIds_packageIds = null;
        com.vidal.merlin.wsclient.lppr.ArrayOfPackageLpprListCoupleSimplified _decompositionPackByPackIds__return = port.decompositionPackByPackIds(_decompositionPackByPackIds_packageIds);
        System.out.println("decompositionPackByPackIds.result=" + _decompositionPackByPackIds__return);


        }
        {
        System.out.println("Invoking searchByPackIds...");
        com.vidal.merlin.wsclient.lppr.ArrayOfInt _searchByPackIds_ids = null;
        com.vidal.merlin.wsclient.lppr.ArrayOfLppr _searchByPackIds__return = port.searchByPackIds(_searchByPackIds_ids);
        System.out.println("searchByPackIds.result=" + _searchByPackIds__return);


        }

        System.exit(0);
    }

}
