package com.vidal.merlin.wsclient.lppr;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:28 CET 2013
 * Generated source version: 2.2.6
 * 
 */
 
@WebService(targetNamespace = "urn:Vidal", name = "lpprService")
@XmlSeeAlso({ObjectFactory.class})
public interface LpprService {

    @WebResult(name = "lpprList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByPartialCode", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.lppr.SearchByPartialCode")
    @ResponseWrapper(localName = "searchByPartialCodeResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.lppr.SearchByPartialCodeResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.lppr.ArrayOfLppr searchByPartialCode(
        @WebParam(name = "prefix", targetNamespace = "urn:Vidal")
        java.lang.String prefix
    );

    @WebResult(name = "lpprList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByCode", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.lppr.SearchByCode")
    @ResponseWrapper(localName = "searchByCodeResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.lppr.SearchByCodeResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.lppr.ArrayOfLppr searchByCode(
        @WebParam(name = "code", targetNamespace = "urn:Vidal")
        java.lang.String code
    );

    @WebResult(name = "lpprList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByName", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.lppr.SearchByName")
    @ResponseWrapper(localName = "searchByNameResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.lppr.SearchByNameResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.lppr.ArrayOfLppr searchByName(
        @WebParam(name = "lpprName", targetNamespace = "urn:Vidal")
        java.lang.String lpprName
    );

    @WebResult(name = "lpprList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByPackId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.lppr.SearchByPackId")
    @ResponseWrapper(localName = "searchByPackIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.lppr.SearchByPackIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.lppr.ArrayOfLppr searchByPackId(
        @WebParam(name = "packId", targetNamespace = "urn:Vidal")
        java.lang.Integer packId
    );

    @WebResult(name = "lpprList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getChildren", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.lppr.GetChildren")
    @ResponseWrapper(localName = "getChildrenResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.lppr.GetChildrenResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.lppr.ArrayOfLppr getChildren(
        @WebParam(name = "id", targetNamespace = "urn:Vidal")
        java.lang.Integer id
    );

    @WebResult(name = "lppr", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getClassificationRootNode", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.lppr.GetClassificationRootNode")
    @ResponseWrapper(localName = "getClassificationRootNodeResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.lppr.GetClassificationRootNodeResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.lppr.Lppr getClassificationRootNode();

    @WebResult(name = "lpprList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getAllParents", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.lppr.GetAllParents")
    @ResponseWrapper(localName = "getAllParentsResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.lppr.GetAllParentsResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.lppr.ArrayOfLppr getAllParents(
        @WebParam(name = "id", targetNamespace = "urn:Vidal")
        java.lang.Integer id
    );

    @WebResult(name = "lpprList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getAllChildren", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.lppr.GetAllChildren")
    @ResponseWrapper(localName = "getAllChildrenResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.lppr.GetAllChildrenResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.lppr.ArrayOfLppr getAllChildren(
        @WebParam(name = "id", targetNamespace = "urn:Vidal")
        java.lang.Integer id
    );

    @WebResult(name = "lppr", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchById", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.lppr.SearchById")
    @ResponseWrapper(localName = "searchByIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.lppr.SearchByIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.lppr.Lppr searchById(
        @WebParam(name = "lpprId", targetNamespace = "urn:Vidal")
        java.lang.Integer lpprId
    );

    @WebResult(name = "lppr", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getParent", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.lppr.GetParent")
    @ResponseWrapper(localName = "getParentResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.lppr.GetParentResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.lppr.Lppr getParent(
        @WebParam(name = "id", targetNamespace = "urn:Vidal")
        java.lang.Integer id
    );

    @WebResult(name = "lpprReimbursementCoupleList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getReimbursementSchedule", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.lppr.GetReimbursementSchedule")
    @ResponseWrapper(localName = "getReimbursementScheduleResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.lppr.GetReimbursementScheduleResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.lppr.ArrayOfLpprReimbursementCouple getReimbursementSchedule(
        @WebParam(name = "lpprIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.lppr.ArrayOfInt lpprIds,
        @WebParam(name = "reimbursementScheduleFilter", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.lppr.ReimbursementScheduleFilter reimbursementScheduleFilter
    );

    @WebResult(name = "packageLpprList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "decompositionPackByPackIds", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.lppr.DecompositionPackByPackIds")
    @ResponseWrapper(localName = "decompositionPackByPackIdsResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.lppr.DecompositionPackByPackIdsResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.lppr.ArrayOfPackageLpprListCoupleSimplified decompositionPackByPackIds(
        @WebParam(name = "packageIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.lppr.ArrayOfInt packageIds
    );

    @WebResult(name = "lpprList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByPackIds", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.lppr.SearchByPackIds")
    @ResponseWrapper(localName = "searchByPackIdsResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.lppr.SearchByPackIdsResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.lppr.ArrayOfLppr searchByPackIds(
        @WebParam(name = "ids", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.lppr.ArrayOfInt ids
    );
}
