
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.vidal.merlin.wsclient.lppr;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:28 CET 2013
 * Generated source version: 2.2.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "LpprService",
                      portName = "LpprServiceHttpPort",
                      targetNamespace = "urn:Vidal",
                      wsdlLocation = "http://localhost:8011/merlin-service/services/LpprService?wsdl",
                      endpointInterface = "com.vidal.merlin.wsclient.lppr.LpprService")
                      
public class LpprServiceImpl implements LpprService {

    private static final Logger LOG = Logger.getLogger(LpprServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.lppr.LpprService#searchByPartialCode(java.lang.String  prefix )*
     */
    public com.vidal.merlin.wsclient.lppr.ArrayOfLppr searchByPartialCode(java.lang.String prefix) { 
        LOG.info("Executing operation searchByPartialCode");
        System.out.println(prefix);
        try {
            com.vidal.merlin.wsclient.lppr.ArrayOfLppr _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.lppr.LpprService#searchByCode(java.lang.String  code )*
     */
    public com.vidal.merlin.wsclient.lppr.ArrayOfLppr searchByCode(java.lang.String code) { 
        LOG.info("Executing operation searchByCode");
        System.out.println(code);
        try {
            com.vidal.merlin.wsclient.lppr.ArrayOfLppr _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.lppr.LpprService#searchByName(java.lang.String  lpprName )*
     */
    public com.vidal.merlin.wsclient.lppr.ArrayOfLppr searchByName(java.lang.String lpprName) { 
        LOG.info("Executing operation searchByName");
        System.out.println(lpprName);
        try {
            com.vidal.merlin.wsclient.lppr.ArrayOfLppr _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.lppr.LpprService#searchByPackId(java.lang.Integer  packId )*
     */
    public com.vidal.merlin.wsclient.lppr.ArrayOfLppr searchByPackId(java.lang.Integer packId) { 
        LOG.info("Executing operation searchByPackId");
        System.out.println(packId);
        try {
            com.vidal.merlin.wsclient.lppr.ArrayOfLppr _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.lppr.LpprService#getChildren(java.lang.Integer  id )*
     */
    public com.vidal.merlin.wsclient.lppr.ArrayOfLppr getChildren(java.lang.Integer id) { 
        LOG.info("Executing operation getChildren");
        System.out.println(id);
        try {
            com.vidal.merlin.wsclient.lppr.ArrayOfLppr _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.lppr.LpprService#getClassificationRootNode(*
     */
    public com.vidal.merlin.wsclient.lppr.Lppr getClassificationRootNode() { 
        LOG.info("Executing operation getClassificationRootNode");
        try {
            com.vidal.merlin.wsclient.lppr.Lppr _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.lppr.LpprService#getAllParents(java.lang.Integer  id )*
     */
    public com.vidal.merlin.wsclient.lppr.ArrayOfLppr getAllParents(java.lang.Integer id) { 
        LOG.info("Executing operation getAllParents");
        System.out.println(id);
        try {
            com.vidal.merlin.wsclient.lppr.ArrayOfLppr _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.lppr.LpprService#getAllChildren(java.lang.Integer  id )*
     */
    public com.vidal.merlin.wsclient.lppr.ArrayOfLppr getAllChildren(java.lang.Integer id) { 
        LOG.info("Executing operation getAllChildren");
        System.out.println(id);
        try {
            com.vidal.merlin.wsclient.lppr.ArrayOfLppr _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.lppr.LpprService#searchById(java.lang.Integer  lpprId )*
     */
    public com.vidal.merlin.wsclient.lppr.Lppr searchById(java.lang.Integer lpprId) { 
        LOG.info("Executing operation searchById");
        System.out.println(lpprId);
        try {
            com.vidal.merlin.wsclient.lppr.Lppr _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.lppr.LpprService#getParent(java.lang.Integer  id )*
     */
    public com.vidal.merlin.wsclient.lppr.Lppr getParent(java.lang.Integer id) { 
        LOG.info("Executing operation getParent");
        System.out.println(id);
        try {
            com.vidal.merlin.wsclient.lppr.Lppr _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.lppr.LpprService#getReimbursementSchedule(com.vidal.merlin.wsclient.lppr.ArrayOfInt  lpprIds ,)com.vidal.merlin.wsclient.lppr.ReimbursementScheduleFilter  reimbursementScheduleFilter )*
     */
    public com.vidal.merlin.wsclient.lppr.ArrayOfLpprReimbursementCouple getReimbursementSchedule(com.vidal.merlin.wsclient.lppr.ArrayOfInt lpprIds,com.vidal.merlin.wsclient.lppr.ReimbursementScheduleFilter reimbursementScheduleFilter) { 
        LOG.info("Executing operation getReimbursementSchedule");
        System.out.println(lpprIds);
        System.out.println(reimbursementScheduleFilter);
        try {
            com.vidal.merlin.wsclient.lppr.ArrayOfLpprReimbursementCouple _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.lppr.LpprService#decompositionPackByPackIds(com.vidal.merlin.wsclient.lppr.ArrayOfInt  packageIds )*
     */
    public com.vidal.merlin.wsclient.lppr.ArrayOfPackageLpprListCoupleSimplified decompositionPackByPackIds(com.vidal.merlin.wsclient.lppr.ArrayOfInt packageIds) { 
        LOG.info("Executing operation decompositionPackByPackIds");
        System.out.println(packageIds);
        try {
            com.vidal.merlin.wsclient.lppr.ArrayOfPackageLpprListCoupleSimplified _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.lppr.LpprService#searchByPackIds(com.vidal.merlin.wsclient.lppr.ArrayOfInt  ids )*
     */
    public com.vidal.merlin.wsclient.lppr.ArrayOfLppr searchByPackIds(com.vidal.merlin.wsclient.lppr.ArrayOfInt ids) { 
        LOG.info("Executing operation searchByPackIds");
        System.out.println(ids);
        try {
            com.vidal.merlin.wsclient.lppr.ArrayOfLppr _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
