
package com.vidal.merlin.wsclient.commonnamegroup;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:23 CET 2013
 * Generated source version: 2.2.6
 * 
 */

public final class CommonNameGroupService_CommonNameGroupServiceHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("urn:Vidal", "CommonNameGroupService");

    private CommonNameGroupService_CommonNameGroupServiceHttpPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = CommonNameGroupService_Service.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CommonNameGroupService_Service ss = new CommonNameGroupService_Service(wsdlURL, SERVICE_NAME);
        CommonNameGroupService port = ss.getCommonNameGroupServiceHttpPort();  
        
        {
        System.out.println("Invoking searchByActivePrincipleIds...");
        com.vidal.merlin.wsclient.commonnamegroup.ArrayOfInt _searchByActivePrincipleIds_moleculeIds = null;
        com.vidal.merlin.wsclient.commonnamegroup.ArrayOfCommonNameGroup _searchByActivePrincipleIds__return = port.searchByActivePrincipleIds(_searchByActivePrincipleIds_moleculeIds);
        System.out.println("searchByActivePrincipleIds.result=" + _searchByActivePrincipleIds__return);


        }
        {
        System.out.println("Invoking getGalenicForm...");
        java.lang.Integer _getGalenicForm_commonNameGroupId = null;
        com.vidal.merlin.wsclient.commonnamegroup.GalenicForm _getGalenicForm__return = port.getGalenicForm(_getGalenicForm_commonNameGroupId);
        System.out.println("getGalenicForm.result=" + _getGalenicForm__return);


        }
        {
        System.out.println("Invoking searchByProductId...");
        java.lang.Integer _searchByProductId_productId = null;
        com.vidal.merlin.wsclient.commonnamegroup.CommonNameGroup _searchByProductId__return = port.searchByProductId(_searchByProductId_productId);
        System.out.println("searchByProductId.result=" + _searchByProductId__return);


        }
        {
        System.out.println("Invoking searchByName...");
        java.lang.String _searchByName_name = "";
        com.vidal.merlin.wsclient.commonnamegroup.ArrayOfCommonNameGroup _searchByName__return = port.searchByName(_searchByName_name);
        System.out.println("searchByName.result=" + _searchByName__return);


        }
        {
        System.out.println("Invoking searchByPackId...");
        java.lang.Integer _searchByPackId_packId = null;
        com.vidal.merlin.wsclient.commonnamegroup.CommonNameGroup _searchByPackId__return = port.searchByPackId(_searchByPackId_packId);
        System.out.println("searchByPackId.result=" + _searchByPackId__return);


        }
        {
        System.out.println("Invoking getRoute...");
        java.lang.Integer _getRoute_commonNameGroupId = null;
        com.vidal.merlin.wsclient.commonnamegroup.ArrayOfRoute _getRoute__return = port.getRoute(_getRoute_commonNameGroupId);
        System.out.println("getRoute.result=" + _getRoute__return);


        }
        {
        System.out.println("Invoking getCommonNameGroupFullByIds...");
        com.vidal.merlin.wsclient.commonnamegroup.ArrayOfInt _getCommonNameGroupFullByIds_commonNameGroupIds = null;
        com.vidal.merlin.wsclient.commonnamegroup.ArrayOfAggregate _getCommonNameGroupFullByIds_aggregates = null;
        com.vidal.merlin.wsclient.commonnamegroup.ArrayOfCommonNameGroupFull _getCommonNameGroupFullByIds__return = port.getCommonNameGroupFullByIds(_getCommonNameGroupFullByIds_commonNameGroupIds, _getCommonNameGroupFullByIds_aggregates);
        System.out.println("getCommonNameGroupFullByIds.result=" + _getCommonNameGroupFullByIds__return);


        }
        {
        System.out.println("Invoking getAllCommonNameGroupFulls...");
        java.lang.String _getAllCommonNameGroupFulls_name = "";
        com.vidal.merlin.wsclient.commonnamegroup.ArrayOfAggregate _getAllCommonNameGroupFulls_aggregates = null;
        java.lang.Integer _getAllCommonNameGroupFulls_pageSize = null;
        java.lang.Integer _getAllCommonNameGroupFulls_pageNumber = null;
        com.vidal.merlin.wsclient.commonnamegroup.PagedResultCommonNameGroupFull _getAllCommonNameGroupFulls__return = port.getAllCommonNameGroupFulls(_getAllCommonNameGroupFulls_name, _getAllCommonNameGroupFulls_aggregates, _getAllCommonNameGroupFulls_pageSize, _getAllCommonNameGroupFulls_pageNumber);
        System.out.println("getAllCommonNameGroupFulls.result=" + _getAllCommonNameGroupFulls__return);


        }
        {
        System.out.println("Invoking searchById...");
        java.lang.Integer _searchById_commonNameGroupId = null;
        com.vidal.merlin.wsclient.commonnamegroup.CommonNameGroup _searchById__return = port.searchById(_searchById_commonNameGroupId);
        System.out.println("searchById.result=" + _searchById__return);


        }
        {
        System.out.println("Invoking searchCommonNameGroupIndicatorsByCommonNameGroupIds...");
        com.vidal.merlin.wsclient.commonnamegroup.ArrayOfInt _searchCommonNameGroupIndicatorsByCommonNameGroupIds_commonNameGroupIds = null;
        com.vidal.merlin.wsclient.commonnamegroup.ArrayOfCommonNameGroupIndicators _searchCommonNameGroupIndicatorsByCommonNameGroupIds__return = port.searchCommonNameGroupIndicatorsByCommonNameGroupIds(_searchCommonNameGroupIndicatorsByCommonNameGroupIds_commonNameGroupIds);
        System.out.println("searchCommonNameGroupIndicatorsByCommonNameGroupIds.result=" + _searchCommonNameGroupIndicatorsByCommonNameGroupIds__return);


        }
        {
        System.out.println("Invoking searchByAtcIds...");
        com.vidal.merlin.wsclient.commonnamegroup.ArrayOfInt _searchByAtcIds_atcIds = null;
        com.vidal.merlin.wsclient.commonnamegroup.ArrayOfCommonNameGroup _searchByAtcIds__return = port.searchByAtcIds(_searchByAtcIds_atcIds);
        System.out.println("searchByAtcIds.result=" + _searchByAtcIds__return);


        }
        {
        System.out.println("Invoking searchByIds...");
        com.vidal.merlin.wsclient.commonnamegroup.ArrayOfInt _searchByIds_commonNameGroupIds = null;
        com.vidal.merlin.wsclient.commonnamegroup.ArrayOfCommonNameGroup _searchByIds__return = port.searchByIds(_searchByIds_commonNameGroupIds);
        System.out.println("searchByIds.result=" + _searchByIds__return);


        }
        {
        System.out.println("Invoking searchByAtcId...");
        java.lang.Integer _searchByAtcId_atcId = null;
        com.vidal.merlin.wsclient.commonnamegroup.ArrayOfCommonNameGroup _searchByAtcId__return = port.searchByAtcId(_searchByAtcId_atcId);
        System.out.println("searchByAtcId.result=" + _searchByAtcId__return);


        }
        {
        System.out.println("Invoking searchByUcdId...");
        java.lang.Integer _searchByUcdId_ucdId = null;
        com.vidal.merlin.wsclient.commonnamegroup.ArrayOfCommonNameGroup _searchByUcdId__return = port.searchByUcdId(_searchByUcdId_ucdId);
        System.out.println("searchByUcdId.result=" + _searchByUcdId__return);


        }

        System.exit(0);
    }

}
