package com.vidal.merlin.wsclient.commonnamegroup;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:23 CET 2013
 * Generated source version: 2.2.6
 * 
 */
 
@WebService(targetNamespace = "urn:Vidal", name = "commonNameGroupService")
@XmlSeeAlso({ObjectFactory.class})
public interface CommonNameGroupService {

    @WebResult(name = "commonNameGroupList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByActivePrincipleIds", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.commonnamegroup.SearchByActivePrincipleIds")
    @ResponseWrapper(localName = "searchByActivePrincipleIdsResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.commonnamegroup.SearchByActivePrincipleIdsResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.commonnamegroup.ArrayOfCommonNameGroup searchByActivePrincipleIds(
        @WebParam(name = "moleculeIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.commonnamegroup.ArrayOfInt moleculeIds
    );

    @WebResult(name = "galenicForm", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getGalenicForm", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.commonnamegroup.GetGalenicForm")
    @ResponseWrapper(localName = "getGalenicFormResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.commonnamegroup.GetGalenicFormResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.commonnamegroup.GalenicForm getGalenicForm(
        @WebParam(name = "commonNameGroupId", targetNamespace = "urn:Vidal")
        java.lang.Integer commonNameGroupId
    );

    @WebResult(name = "commonNameGroup", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByProductId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.commonnamegroup.SearchByProductId")
    @ResponseWrapper(localName = "searchByProductIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.commonnamegroup.SearchByProductIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.commonnamegroup.CommonNameGroup searchByProductId(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        java.lang.Integer productId
    );

    @WebResult(name = "commonNameGroupList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByName", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.commonnamegroup.SearchByName")
    @ResponseWrapper(localName = "searchByNameResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.commonnamegroup.SearchByNameResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.commonnamegroup.ArrayOfCommonNameGroup searchByName(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        java.lang.String name
    );

    @WebResult(name = "commonNameGroup", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByPackId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.commonnamegroup.SearchByPackId")
    @ResponseWrapper(localName = "searchByPackIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.commonnamegroup.SearchByPackIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.commonnamegroup.CommonNameGroup searchByPackId(
        @WebParam(name = "packId", targetNamespace = "urn:Vidal")
        java.lang.Integer packId
    );

    @WebResult(name = "routeList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getRoute", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.commonnamegroup.GetRoute")
    @ResponseWrapper(localName = "getRouteResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.commonnamegroup.GetRouteResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.commonnamegroup.ArrayOfRoute getRoute(
        @WebParam(name = "commonNameGroupId", targetNamespace = "urn:Vidal")
        java.lang.Integer commonNameGroupId
    );

    @WebResult(name = "commonNameGroupFullList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getCommonNameGroupFullByIds", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.commonnamegroup.GetCommonNameGroupFullByIds")
    @ResponseWrapper(localName = "getCommonNameGroupFullByIdsResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.commonnamegroup.GetCommonNameGroupFullByIdsResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.commonnamegroup.ArrayOfCommonNameGroupFull getCommonNameGroupFullByIds(
        @WebParam(name = "commonNameGroupIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.commonnamegroup.ArrayOfInt commonNameGroupIds,
        @WebParam(name = "aggregates", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.commonnamegroup.ArrayOfAggregate aggregates
    );

    @WebResult(name = "pagedResultCommonNameGroupFull", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getAllCommonNameGroupFulls", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.commonnamegroup.GetAllCommonNameGroupFulls")
    @ResponseWrapper(localName = "getAllCommonNameGroupFullsResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.commonnamegroup.GetAllCommonNameGroupFullsResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.commonnamegroup.PagedResultCommonNameGroupFull getAllCommonNameGroupFulls(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        java.lang.String name,
        @WebParam(name = "aggregates", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.commonnamegroup.ArrayOfAggregate aggregates,
        @WebParam(name = "pageSize", targetNamespace = "urn:Vidal")
        java.lang.Integer pageSize,
        @WebParam(name = "pageNumber", targetNamespace = "urn:Vidal")
        java.lang.Integer pageNumber
    );

    @WebResult(name = "commonNameGroup", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchById", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.commonnamegroup.SearchById")
    @ResponseWrapper(localName = "searchByIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.commonnamegroup.SearchByIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.commonnamegroup.CommonNameGroup searchById(
        @WebParam(name = "commonNameGroupId", targetNamespace = "urn:Vidal")
        java.lang.Integer commonNameGroupId
    );

    @WebResult(name = "commonNameGroupIndicatorsList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchCommonNameGroupIndicatorsByCommonNameGroupIds", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.commonnamegroup.SearchCommonNameGroupIndicatorsByCommonNameGroupIds")
    @ResponseWrapper(localName = "searchCommonNameGroupIndicatorsByCommonNameGroupIdsResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.commonnamegroup.SearchCommonNameGroupIndicatorsByCommonNameGroupIdsResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.commonnamegroup.ArrayOfCommonNameGroupIndicators searchCommonNameGroupIndicatorsByCommonNameGroupIds(
        @WebParam(name = "commonNameGroupIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.commonnamegroup.ArrayOfInt commonNameGroupIds
    );

    @WebResult(name = "commonNameGroupList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByAtcIds", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.commonnamegroup.SearchByAtcIds")
    @ResponseWrapper(localName = "searchByAtcIdsResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.commonnamegroup.SearchByAtcIdsResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.commonnamegroup.ArrayOfCommonNameGroup searchByAtcIds(
        @WebParam(name = "atcIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.commonnamegroup.ArrayOfInt atcIds
    );

    @WebResult(name = "commonNameGroupList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByIds", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.commonnamegroup.SearchByIds")
    @ResponseWrapper(localName = "searchByIdsResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.commonnamegroup.SearchByIdsResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.commonnamegroup.ArrayOfCommonNameGroup searchByIds(
        @WebParam(name = "commonNameGroupIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.commonnamegroup.ArrayOfInt commonNameGroupIds
    );

    @WebResult(name = "commonNameGroupList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByAtcId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.commonnamegroup.SearchByAtcId")
    @ResponseWrapper(localName = "searchByAtcIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.commonnamegroup.SearchByAtcIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.commonnamegroup.ArrayOfCommonNameGroup searchByAtcId(
        @WebParam(name = "atcId", targetNamespace = "urn:Vidal")
        java.lang.Integer atcId
    );

    @WebResult(name = "commonNameGroupList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByUcdId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.commonnamegroup.SearchByUcdId")
    @ResponseWrapper(localName = "searchByUcdIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.commonnamegroup.SearchByUcdIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.commonnamegroup.ArrayOfCommonNameGroup searchByUcdId(
        @WebParam(name = "ucdId", targetNamespace = "urn:Vidal")
        java.lang.Integer ucdId
    );
}
