
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.vidal.merlin.wsclient.molecule;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:28 CET 2013
 * Generated source version: 2.2.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "MoleculeService",
                      portName = "MoleculeServiceHttpPort",
                      targetNamespace = "urn:Vidal",
                      wsdlLocation = "http://localhost:8011/merlin-service/services/MoleculeService?wsdl",
                      endpointInterface = "com.vidal.merlin.wsclient.molecule.MoleculeService")
                      
public class MoleculeServiceImpl implements MoleculeService {

    private static final Logger LOG = Logger.getLogger(MoleculeServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.molecule.MoleculeService#searchByProductId(java.lang.Integer  productId )*
     */
    public com.vidal.merlin.wsclient.molecule.ArrayOfMolecule searchByProductId(java.lang.Integer productId) { 
        LOG.info("Executing operation searchByProductId");
        System.out.println(productId);
        try {
            com.vidal.merlin.wsclient.molecule.ArrayOfMolecule _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.molecule.MoleculeService#searchByName(java.lang.String  name )*
     */
    public com.vidal.merlin.wsclient.molecule.ArrayOfMolecule searchByName(java.lang.String name) { 
        LOG.info("Executing operation searchByName");
        System.out.println(name);
        try {
            com.vidal.merlin.wsclient.molecule.ArrayOfMolecule _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.molecule.MoleculeService#searchActivePrincipleByUcdId(java.lang.Integer  ucdId )*
     */
    public com.vidal.merlin.wsclient.molecule.ArrayOfMolecule searchActivePrincipleByUcdId(java.lang.Integer ucdId) { 
        LOG.info("Executing operation searchActivePrincipleByUcdId");
        System.out.println(ucdId);
        try {
            com.vidal.merlin.wsclient.molecule.ArrayOfMolecule _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.molecule.MoleculeService#searchOnlySecuredMoleculeByName(java.lang.String  name )*
     */
    public com.vidal.merlin.wsclient.molecule.ArrayOfMolecule searchOnlySecuredMoleculeByName(java.lang.String name) { 
        LOG.info("Executing operation searchOnlySecuredMoleculeByName");
        System.out.println(name);
        try {
            com.vidal.merlin.wsclient.molecule.ArrayOfMolecule _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.molecule.MoleculeService#getChildrenById(java.lang.Integer  moleculeId )*
     */
    public com.vidal.merlin.wsclient.molecule.ArrayOfMolecule getChildrenById(java.lang.Integer moleculeId) { 
        LOG.info("Executing operation getChildrenById");
        System.out.println(moleculeId);
        try {
            com.vidal.merlin.wsclient.molecule.ArrayOfMolecule _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.molecule.MoleculeService#searchActivePrincipleByProductId(java.lang.Integer  productId )*
     */
    public com.vidal.merlin.wsclient.molecule.ArrayOfMolecule searchActivePrincipleByProductId(java.lang.Integer productId) { 
        LOG.info("Executing operation searchActivePrincipleByProductId");
        System.out.println(productId);
        try {
            com.vidal.merlin.wsclient.molecule.ArrayOfMolecule _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.molecule.MoleculeService#searchById(java.lang.Integer  moleculeId )*
     */
    public com.vidal.merlin.wsclient.molecule.Molecule searchById(java.lang.Integer moleculeId) { 
        LOG.info("Executing operation searchById");
        System.out.println(moleculeId);
        try {
            com.vidal.merlin.wsclient.molecule.Molecule _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.molecule.MoleculeService#searchByNameAndRoleWithIndexedVidalWithUsedInComposition(java.lang.String  name ,)com.vidal.merlin.wsclient.molecule.SubstanceRole  role )*
     */
    public com.vidal.merlin.wsclient.molecule.ArrayOfMolecule searchByNameAndRoleWithIndexedVidalWithUsedInComposition(java.lang.String name,com.vidal.merlin.wsclient.molecule.SubstanceRole role) { 
        LOG.info("Executing operation searchByNameAndRoleWithIndexedVidalWithUsedInComposition");
        System.out.println(name);
        System.out.println(role);
        try {
            com.vidal.merlin.wsclient.molecule.ArrayOfMolecule _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.molecule.MoleculeService#searchActivePrincipleByCommonNameGroupId(java.lang.Integer  commonNameGroupId )*
     */
    public com.vidal.merlin.wsclient.molecule.ArrayOfMolecule searchActivePrincipleByCommonNameGroupId(java.lang.Integer commonNameGroupId) { 
        LOG.info("Executing operation searchActivePrincipleByCommonNameGroupId");
        System.out.println(commonNameGroupId);
        try {
            com.vidal.merlin.wsclient.molecule.ArrayOfMolecule _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.molecule.MoleculeService#getAllMolecules(com.vidal.merlin.wsclient.molecule.SubstanceRole  role ,)java.lang.Integer  pageNumber ,)java.lang.Integer  pageSize )*
     */
    public com.vidal.merlin.wsclient.molecule.PagedResultMolecule getAllMolecules(com.vidal.merlin.wsclient.molecule.SubstanceRole role,java.lang.Integer pageNumber,java.lang.Integer pageSize) { 
        LOG.info("Executing operation getAllMolecules");
        System.out.println(role);
        System.out.println(pageNumber);
        System.out.println(pageSize);
        try {
            com.vidal.merlin.wsclient.molecule.PagedResultMolecule _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.molecule.MoleculeService#searchOnlySecuredMoleculeByIds(com.vidal.merlin.wsclient.molecule.ArrayOfInt  moleculeIds )*
     */
    public com.vidal.merlin.wsclient.molecule.ArrayOfMolecule searchOnlySecuredMoleculeByIds(com.vidal.merlin.wsclient.molecule.ArrayOfInt moleculeIds) { 
        LOG.info("Executing operation searchOnlySecuredMoleculeByIds");
        System.out.println(moleculeIds);
        try {
            com.vidal.merlin.wsclient.molecule.ArrayOfMolecule _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.molecule.MoleculeService#searchByIds(com.vidal.merlin.wsclient.molecule.ArrayOfInt  moleculeIds )*
     */
    public com.vidal.merlin.wsclient.molecule.ArrayOfMolecule searchByIds(com.vidal.merlin.wsclient.molecule.ArrayOfInt moleculeIds) { 
        LOG.info("Executing operation searchByIds");
        System.out.println(moleculeIds);
        try {
            com.vidal.merlin.wsclient.molecule.ArrayOfMolecule _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.molecule.MoleculeService#getParentsById(java.lang.Integer  moleculeId )*
     */
    public com.vidal.merlin.wsclient.molecule.ArrayOfMolecule getParentsById(java.lang.Integer moleculeId) { 
        LOG.info("Executing operation getParentsById");
        System.out.println(moleculeId);
        try {
            com.vidal.merlin.wsclient.molecule.ArrayOfMolecule _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.molecule.MoleculeService#searchByAllergyId(java.lang.Integer  allergyId )*
     */
    public com.vidal.merlin.wsclient.molecule.ArrayOfMolecule searchByAllergyId(java.lang.Integer allergyId) { 
        LOG.info("Executing operation searchByAllergyId");
        System.out.println(allergyId);
        try {
            com.vidal.merlin.wsclient.molecule.ArrayOfMolecule _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
