package com.vidal.merlin.wsclient.molecule;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:28 CET 2013
 * Generated source version: 2.2.6
 * 
 */
 
@WebService(targetNamespace = "urn:Vidal", name = "moleculeService")
@XmlSeeAlso({ObjectFactory.class})
public interface MoleculeService {

    @WebResult(name = "moleculeList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByProductId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.molecule.SearchByProductId")
    @ResponseWrapper(localName = "searchByProductIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.molecule.SearchByProductIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.molecule.ArrayOfMolecule searchByProductId(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        java.lang.Integer productId
    );

    @WebResult(name = "moleculeList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByName", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.molecule.SearchByName")
    @ResponseWrapper(localName = "searchByNameResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.molecule.SearchByNameResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.molecule.ArrayOfMolecule searchByName(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        java.lang.String name
    );

    @WebResult(name = "moleculeList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchActivePrincipleByUcdId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.molecule.SearchActivePrincipleByUcdId")
    @ResponseWrapper(localName = "searchActivePrincipleByUcdIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.molecule.SearchActivePrincipleByUcdIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.molecule.ArrayOfMolecule searchActivePrincipleByUcdId(
        @WebParam(name = "ucdId", targetNamespace = "urn:Vidal")
        java.lang.Integer ucdId
    );

    @WebResult(name = "moleculeList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchOnlySecuredMoleculeByName", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.molecule.SearchOnlySecuredMoleculeByName")
    @ResponseWrapper(localName = "searchOnlySecuredMoleculeByNameResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.molecule.SearchOnlySecuredMoleculeByNameResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.molecule.ArrayOfMolecule searchOnlySecuredMoleculeByName(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        java.lang.String name
    );

    @WebResult(name = "moleculeList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getChildrenById", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.molecule.GetChildrenById")
    @ResponseWrapper(localName = "getChildrenByIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.molecule.GetChildrenByIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.molecule.ArrayOfMolecule getChildrenById(
        @WebParam(name = "moleculeId", targetNamespace = "urn:Vidal")
        java.lang.Integer moleculeId
    );

    @WebResult(name = "moleculeList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchActivePrincipleByProductId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.molecule.SearchActivePrincipleByProductId")
    @ResponseWrapper(localName = "searchActivePrincipleByProductIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.molecule.SearchActivePrincipleByProductIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.molecule.ArrayOfMolecule searchActivePrincipleByProductId(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        java.lang.Integer productId
    );

    @WebResult(name = "molecule", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchById", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.molecule.SearchById")
    @ResponseWrapper(localName = "searchByIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.molecule.SearchByIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.molecule.Molecule searchById(
        @WebParam(name = "moleculeId", targetNamespace = "urn:Vidal")
        java.lang.Integer moleculeId
    );

    @WebResult(name = "moleculeList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByNameAndRoleWithIndexedVidalWithUsedInComposition", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.molecule.SearchByNameAndRoleWithIndexedVidalWithUsedInComposition")
    @ResponseWrapper(localName = "searchByNameAndRoleWithIndexedVidalWithUsedInCompositionResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.molecule.SearchByNameAndRoleWithIndexedVidalWithUsedInCompositionResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.molecule.ArrayOfMolecule searchByNameAndRoleWithIndexedVidalWithUsedInComposition(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        java.lang.String name,
        @WebParam(name = "role", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.molecule.SubstanceRole role
    );

    @WebResult(name = "moleculeList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchActivePrincipleByCommonNameGroupId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.molecule.SearchActivePrincipleByCommonNameGroupId")
    @ResponseWrapper(localName = "searchActivePrincipleByCommonNameGroupIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.molecule.SearchActivePrincipleByCommonNameGroupIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.molecule.ArrayOfMolecule searchActivePrincipleByCommonNameGroupId(
        @WebParam(name = "commonNameGroupId", targetNamespace = "urn:Vidal")
        java.lang.Integer commonNameGroupId
    );

    @WebResult(name = "pagedResultMolecule", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getAllMolecules", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.molecule.GetAllMolecules")
    @ResponseWrapper(localName = "getAllMoleculesResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.molecule.GetAllMoleculesResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.molecule.PagedResultMolecule getAllMolecules(
        @WebParam(name = "role", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.molecule.SubstanceRole role,
        @WebParam(name = "pageNumber", targetNamespace = "urn:Vidal")
        java.lang.Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "urn:Vidal")
        java.lang.Integer pageSize
    );

    @WebResult(name = "moleculeList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchOnlySecuredMoleculeByIds", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.molecule.SearchOnlySecuredMoleculeByIds")
    @ResponseWrapper(localName = "searchOnlySecuredMoleculeByIdsResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.molecule.SearchOnlySecuredMoleculeByIdsResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.molecule.ArrayOfMolecule searchOnlySecuredMoleculeByIds(
        @WebParam(name = "moleculeIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.molecule.ArrayOfInt moleculeIds
    );

    @WebResult(name = "moleculeList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByIds", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.molecule.SearchByIds")
    @ResponseWrapper(localName = "searchByIdsResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.molecule.SearchByIdsResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.molecule.ArrayOfMolecule searchByIds(
        @WebParam(name = "moleculeIds", targetNamespace = "urn:Vidal")
        com.vidal.merlin.wsclient.molecule.ArrayOfInt moleculeIds
    );

    @WebResult(name = "moleculeList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getParentsById", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.molecule.GetParentsById")
    @ResponseWrapper(localName = "getParentsByIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.molecule.GetParentsByIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.molecule.ArrayOfMolecule getParentsById(
        @WebParam(name = "moleculeId", targetNamespace = "urn:Vidal")
        java.lang.Integer moleculeId
    );

    @WebResult(name = "moleculeList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByAllergyId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.molecule.SearchByAllergyId")
    @ResponseWrapper(localName = "searchByAllergyIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.molecule.SearchByAllergyIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.molecule.ArrayOfMolecule searchByAllergyId(
        @WebParam(name = "allergyId", targetNamespace = "urn:Vidal")
        java.lang.Integer allergyId
    );
}
