
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.vidal.merlin.wsclient.indication;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:27 CET 2013
 * Generated source version: 2.2.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "IndicationService",
                      portName = "IndicationServiceHttpPort",
                      targetNamespace = "urn:Vidal",
                      wsdlLocation = "http://localhost:8011/merlin-service/services/IndicationService?wsdl",
                      endpointInterface = "com.vidal.merlin.wsclient.indication.IndicationService")
                      
public class IndicationServiceImpl implements IndicationService {

    private static final Logger LOG = Logger.getLogger(IndicationServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.indication.IndicationService#searchByProductId(java.lang.Integer  productId )*
     */
    public com.vidal.merlin.wsclient.indication.ArrayOfIndication searchByProductId(java.lang.Integer productId) { 
        LOG.info("Executing operation searchByProductId");
        System.out.println(productId);
        try {
            com.vidal.merlin.wsclient.indication.ArrayOfIndication _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.indication.IndicationService#searchByName(java.lang.String  name )*
     */
    public com.vidal.merlin.wsclient.indication.ArrayOfIndication searchByName(java.lang.String name) { 
        LOG.info("Executing operation searchByName");
        System.out.println(name);
        try {
            com.vidal.merlin.wsclient.indication.ArrayOfIndication _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.indication.IndicationService#getAllIndications(java.lang.Integer  pageNumber ,)java.lang.Integer  pageSize )*
     */
    public com.vidal.merlin.wsclient.indication.PagedResultIndication getAllIndications(java.lang.Integer pageNumber,java.lang.Integer pageSize) { 
        LOG.info("Executing operation getAllIndications");
        System.out.println(pageNumber);
        System.out.println(pageSize);
        try {
            com.vidal.merlin.wsclient.indication.PagedResultIndication _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.indication.IndicationService#searchByIndicationGroupId(java.lang.Integer  indicationGroupId )*
     */
    public com.vidal.merlin.wsclient.indication.ArrayOfIndication searchByIndicationGroupId(java.lang.Integer indicationGroupId) { 
        LOG.info("Executing operation searchByIndicationGroupId");
        System.out.println(indicationGroupId);
        try {
            com.vidal.merlin.wsclient.indication.ArrayOfIndication _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.indication.IndicationService#searchById(java.lang.Integer  indicationId )*
     */
    public com.vidal.merlin.wsclient.indication.Indication searchById(java.lang.Integer indicationId) { 
        LOG.info("Executing operation searchById");
        System.out.println(indicationId);
        try {
            com.vidal.merlin.wsclient.indication.Indication _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.indication.IndicationService#searchByIndicationsGroupId(java.lang.Integer  indicationsGroupId )*
     */
    public com.vidal.merlin.wsclient.indication.ArrayOfIndication searchByIndicationsGroupId(java.lang.Integer indicationsGroupId) { 
        LOG.info("Executing operation searchByIndicationsGroupId");
        System.out.println(indicationsGroupId);
        try {
            com.vidal.merlin.wsclient.indication.ArrayOfIndication _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.vidal.merlin.wsclient.indication.IndicationService#searchByCommonNameGroupId(java.lang.Integer  commonNameGroupId )*
     */
    public com.vidal.merlin.wsclient.indication.CommonNameGroupIndicationList searchByCommonNameGroupId(java.lang.Integer commonNameGroupId) { 
        LOG.info("Executing operation searchByCommonNameGroupId");
        System.out.println(commonNameGroupId);
        try {
            com.vidal.merlin.wsclient.indication.CommonNameGroupIndicationList _return = null;
            return _return;
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
