package com.vidal.merlin.wsclient.indication;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:27 CET 2013
 * Generated source version: 2.2.6
 * 
 */
 
@WebService(targetNamespace = "urn:Vidal", name = "indicationService")
@XmlSeeAlso({ObjectFactory.class})
public interface IndicationService {

    @WebResult(name = "indicationList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByProductId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.indication.SearchByProductId")
    @ResponseWrapper(localName = "searchByProductIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.indication.SearchByProductIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.indication.ArrayOfIndication searchByProductId(
        @WebParam(name = "productId", targetNamespace = "urn:Vidal")
        java.lang.Integer productId
    );

    @WebResult(name = "indicationList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByName", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.indication.SearchByName")
    @ResponseWrapper(localName = "searchByNameResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.indication.SearchByNameResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.indication.ArrayOfIndication searchByName(
        @WebParam(name = "name", targetNamespace = "urn:Vidal")
        java.lang.String name
    );

    @WebResult(name = "pagedResultIndication", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "getAllIndications", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.indication.GetAllIndications")
    @ResponseWrapper(localName = "getAllIndicationsResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.indication.GetAllIndicationsResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.indication.PagedResultIndication getAllIndications(
        @WebParam(name = "pageNumber", targetNamespace = "urn:Vidal")
        java.lang.Integer pageNumber,
        @WebParam(name = "pageSize", targetNamespace = "urn:Vidal")
        java.lang.Integer pageSize
    );

    @WebResult(name = "indicationList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByIndicationGroupId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.indication.SearchByIndicationGroupId")
    @ResponseWrapper(localName = "searchByIndicationGroupIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.indication.SearchByIndicationGroupIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.indication.ArrayOfIndication searchByIndicationGroupId(
        @WebParam(name = "indicationGroupId", targetNamespace = "urn:Vidal")
        java.lang.Integer indicationGroupId
    );

    @WebResult(name = "indication", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchById", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.indication.SearchById")
    @ResponseWrapper(localName = "searchByIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.indication.SearchByIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.indication.Indication searchById(
        @WebParam(name = "indicationId", targetNamespace = "urn:Vidal")
        java.lang.Integer indicationId
    );

    @WebResult(name = "indicationList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByIndicationsGroupId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.indication.SearchByIndicationsGroupId")
    @ResponseWrapper(localName = "searchByIndicationsGroupIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.indication.SearchByIndicationsGroupIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.indication.ArrayOfIndication searchByIndicationsGroupId(
        @WebParam(name = "indicationsGroupId", targetNamespace = "urn:Vidal")
        java.lang.Integer indicationsGroupId
    );

    @WebResult(name = "indicationList", targetNamespace = "urn:Vidal")
    @RequestWrapper(localName = "searchByCommonNameGroupId", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.indication.SearchByCommonNameGroupId")
    @ResponseWrapper(localName = "searchByCommonNameGroupIdResponse", targetNamespace = "urn:Vidal", className = "com.vidal.merlin.wsclient.indication.SearchByCommonNameGroupIdResponse")
    @WebMethod
    public com.vidal.merlin.wsclient.indication.CommonNameGroupIndicationList searchByCommonNameGroupId(
        @WebParam(name = "commonNameGroupId", targetNamespace = "urn:Vidal")
        java.lang.Integer commonNameGroupId
    );
}
