
package com.vidal.merlin.wsclient.indication;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.6
 * Mon Oct 28 23:24:27 CET 2013
 * Generated source version: 2.2.6
 * 
 */

public final class IndicationService_IndicationServiceHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("urn:Vidal", "IndicationService");

    private IndicationService_IndicationServiceHttpPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = IndicationService_Service.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        IndicationService_Service ss = new IndicationService_Service(wsdlURL, SERVICE_NAME);
        IndicationService port = ss.getIndicationServiceHttpPort();  
        
        {
        System.out.println("Invoking searchByProductId...");
        java.lang.Integer _searchByProductId_productId = null;
        com.vidal.merlin.wsclient.indication.ArrayOfIndication _searchByProductId__return = port.searchByProductId(_searchByProductId_productId);
        System.out.println("searchByProductId.result=" + _searchByProductId__return);


        }
        {
        System.out.println("Invoking searchByName...");
        java.lang.String _searchByName_name = "";
        com.vidal.merlin.wsclient.indication.ArrayOfIndication _searchByName__return = port.searchByName(_searchByName_name);
        System.out.println("searchByName.result=" + _searchByName__return);


        }
        {
        System.out.println("Invoking getAllIndications...");
        java.lang.Integer _getAllIndications_pageNumber = null;
        java.lang.Integer _getAllIndications_pageSize = null;
        com.vidal.merlin.wsclient.indication.PagedResultIndication _getAllIndications__return = port.getAllIndications(_getAllIndications_pageNumber, _getAllIndications_pageSize);
        System.out.println("getAllIndications.result=" + _getAllIndications__return);


        }
        {
        System.out.println("Invoking searchByIndicationGroupId...");
        java.lang.Integer _searchByIndicationGroupId_indicationGroupId = null;
        com.vidal.merlin.wsclient.indication.ArrayOfIndication _searchByIndicationGroupId__return = port.searchByIndicationGroupId(_searchByIndicationGroupId_indicationGroupId);
        System.out.println("searchByIndicationGroupId.result=" + _searchByIndicationGroupId__return);


        }
        {
        System.out.println("Invoking searchById...");
        java.lang.Integer _searchById_indicationId = null;
        com.vidal.merlin.wsclient.indication.Indication _searchById__return = port.searchById(_searchById_indicationId);
        System.out.println("searchById.result=" + _searchById__return);


        }
        {
        System.out.println("Invoking searchByIndicationsGroupId...");
        java.lang.Integer _searchByIndicationsGroupId_indicationsGroupId = null;
        com.vidal.merlin.wsclient.indication.ArrayOfIndication _searchByIndicationsGroupId__return = port.searchByIndicationsGroupId(_searchByIndicationsGroupId_indicationsGroupId);
        System.out.println("searchByIndicationsGroupId.result=" + _searchByIndicationsGroupId__return);


        }
        {
        System.out.println("Invoking searchByCommonNameGroupId...");
        java.lang.Integer _searchByCommonNameGroupId_commonNameGroupId = null;
        com.vidal.merlin.wsclient.indication.CommonNameGroupIndicationList _searchByCommonNameGroupId__return = port.searchByCommonNameGroupId(_searchByCommonNameGroupId_commonNameGroupId);
        System.out.println("searchByCommonNameGroupId.result=" + _searchByCommonNameGroupId__return);


        }

        System.exit(0);
    }

}
